import type { CourseSpec, RosterFixture, TimeSlot } from "./types";

const slot = (
  weekday: TimeSlot["weekday"],
  start: string,
  end: string,
  room: string,
): TimeSlot => ({ weekday, start, end, room });

const course = (
  value: Omit<CourseSpec, "id" | "catalogVersion" | "offeredSemesters">,
): CourseSpec => ({
  ...value,
  id: `course-spec-${value.code.toLowerCase()}`,
  catalogVersion: "catalog-2026-fall-fixture-r3",
  offeredSemesters: ["2026-Fall"],
});

export const ROSTER_FIXTURE: RosterFixture = {
  schemaVersion: "1.0.0",
  dataMode: "fixture",
  studentId: "student-nan-fixture",
  semester: "2026-Fall",
  catalogVersion: "catalog-2026-fall-fixture-r3",
  sourceBoundary:
    "这 12 门课和它们的班次、容量、先修条件都是演示数据，只用来试排课；不会连接学校选课系统，也不代表真实名额。",
  creditRange: { min: 15, max: 18 },
  catalog: [
    course({
      code: "SLS201",
      title: "信号与线性系统",
      credits: 3,
      role: "required",
      department: "电子信息",
      attributes: ["专业必修", "主赛程"],
      prerequisites: [{ courseId: "CAL101", relation: "before" }],
      corequisites: [],
      substitutes: [],
      exclusions: [],
      offerings: [
        {
          id: "sls201-a",
          instructor: "林老师（演示）",
          modality: "in_person",
          capacity: 64,
          enrolled: 51,
          timeSlots: [
            slot("Mon", "09:00", "10:30", "工科楼 A201"),
            slot("Wed", "09:00", "10:30", "工科楼 A201"),
          ],
        },
      ],
    }),
    course({
      code: "CIR220",
      title: "电子电路",
      credits: 3,
      role: "required",
      department: "电子信息",
      attributes: ["专业必修"],
      prerequisites: [{ courseId: "PHY101", relation: "before" }],
      corequisites: [],
      substitutes: [],
      exclusions: [],
      offerings: [
        {
          id: "cir220-a",
          instructor: "周老师（演示）",
          modality: "in_person",
          capacity: 56,
          enrolled: 48,
          timeSlots: [
            slot("Tue", "10:30", "12:00", "工科楼 B310"),
            slot("Thu", "10:30", "12:00", "工科楼 B310"),
          ],
        },
        {
          id: "cir220-b",
          instructor: "周老师（演示）",
          modality: "in_person",
          capacity: 56,
          enrolled: 37,
          timeSlots: [
            slot("Mon", "09:00", "10:30", "工科楼 B307"),
            slot("Wed", "09:00", "10:30", "工科楼 B307"),
          ],
        },
      ],
    }),
    course({
      code: "MAT313",
      title: "高等数学专题",
      credits: 3,
      role: "required",
      department: "数学",
      attributes: ["专业基础"],
      prerequisites: [{ courseId: "CAL101", relation: "before" }],
      corequisites: [],
      substitutes: [],
      exclusions: [],
      offerings: [
        {
          id: "mat313-a",
          instructor: "陈老师（演示）",
          modality: "in_person",
          capacity: 72,
          enrolled: 59,
          timeSlots: [
            slot("Tue", "08:00", "09:30", "理科楼 105"),
            slot("Thu", "08:00", "09:30", "理科楼 105"),
          ],
        },
        {
          id: "mat313-b",
          instructor: "陈老师（演示）",
          modality: "hybrid",
          capacity: 72,
          enrolled: 61,
          timeSlots: [
            slot("Tue", "14:00", "15:30", "理科楼 105"),
            slot("Thu", "14:00", "15:30", "理科楼 105"),
          ],
        },
      ],
    }),
    course({
      code: "OPT210",
      title: "应用光学",
      credits: 3,
      role: "elective",
      department: "物理",
      attributes: ["方向选修"],
      prerequisites: [{ courseId: "PHY101", relation: "before" }],
      corequisites: [],
      substitutes: ["PHY240"],
      exclusions: ["PHY240"],
      offerings: [
        {
          id: "opt210-a",
          instructor: "许老师（演示）",
          modality: "in_person",
          capacity: 42,
          enrolled: 34,
          timeSlots: [
            slot("Mon", "14:00", "15:30", "理科楼 408"),
            slot("Wed", "14:00", "15:30", "理科楼 408"),
          ],
        },
      ],
    }),
    course({
      code: "ENG210",
      title: "学术英语",
      credits: 2,
      role: "general_ed",
      department: "外国语",
      attributes: ["通识"],
      prerequisites: [],
      corequisites: [],
      substitutes: ["WRT201"],
      exclusions: [],
      offerings: [
        {
          id: "eng210-a",
          instructor: "Taylor（演示）",
          modality: "hybrid",
          capacity: 36,
          enrolled: 29,
          timeSlots: [slot("Fri", "08:00", "10:00", "文科楼 214")],
        },
        {
          id: "eng210-b",
          instructor: "Taylor（演示）",
          modality: "hybrid",
          capacity: 36,
          enrolled: 31,
          timeSlots: [slot("Fri", "14:00", "16:00", "文科楼 214")],
        },
      ],
    }),
    course({
      code: "EGR201",
      title: "工程训练实验",
      credits: 2,
      role: "lab",
      department: "工程实践",
      attributes: ["实验", "并修"],
      prerequisites: [],
      corequisites: ["CIR220"],
      substitutes: [],
      exclusions: [],
      offerings: [
        {
          id: "egr201-a",
          instructor: "工程中心（演示）",
          modality: "in_person",
          capacity: 24,
          enrolled: 19,
          timeSlots: [slot("Wed", "14:00", "17:00", "工程中心 L2")],
        },
      ],
    }),
    course({
      code: "DAT210",
      title: "数据与社会",
      credits: 2,
      role: "general_ed",
      department: "公共事务",
      attributes: ["跨学科"],
      prerequisites: [],
      corequisites: [],
      substitutes: [],
      exclusions: [],
      offerings: [
        {
          id: "dat210-a",
          instructor: "高老师（演示）",
          modality: "hybrid",
          capacity: 80,
          enrolled: 63,
          timeSlots: [slot("Tue", "16:00", "17:30", "公共楼 301")],
        },
      ],
    }),
    course({
      code: "HCI205",
      title: "人因与交互设计",
      credits: 2,
      role: "elective",
      department: "设计",
      attributes: ["跨学科", "项目制"],
      prerequisites: [],
      corequisites: [],
      substitutes: [],
      exclusions: ["AI220"],
      offerings: [
        {
          id: "hci205-a",
          instructor: "顾老师（演示）",
          modality: "in_person",
          capacity: 32,
          enrolled: 24,
          timeSlots: [slot("Fri", "10:00", "12:00", "设计楼 Studio 3")],
        },
      ],
    }),
    course({
      code: "AI220",
      title: "机器智能导论",
      credits: 3,
      role: "elective",
      department: "计算机",
      attributes: ["方向选修"],
      prerequisites: [{ courseId: "PRG100", relation: "before" }],
      corequisites: [],
      substitutes: [],
      exclusions: ["HCI205"],
      offerings: [
        {
          id: "ai220-a",
          instructor: "魏老师（演示）",
          modality: "hybrid",
          capacity: 48,
          enrolled: 45,
          timeSlots: [slot("Fri", "10:00", "12:00", "信息楼 C402")],
        },
      ],
    }),
    course({
      code: "RES101",
      title: "科研方法与选题",
      credits: 2,
      role: "elective",
      department: "创新学院",
      attributes: ["科研入门"],
      prerequisites: [],
      corequisites: [],
      substitutes: [],
      exclusions: [],
      offerings: [
        {
          id: "res101-a",
          instructor: "导师组（演示）",
          modality: "hybrid",
          capacity: 40,
          enrolled: 33,
          timeSlots: [slot("Mon", "16:00", "17:30", "创新楼 102")],
        },
      ],
    }),
    course({
      code: "PHY240",
      title: "现代物理",
      credits: 3,
      role: "elective",
      department: "物理",
      attributes: ["方向选修"],
      prerequisites: [{ courseId: "PHY101", relation: "before" }],
      corequisites: [],
      substitutes: ["OPT210"],
      exclusions: ["OPT210"],
      offerings: [
        {
          id: "phy240-a",
          instructor: "赵老师（演示）",
          modality: "in_person",
          capacity: 46,
          enrolled: 38,
          timeSlots: [slot("Wed", "10:30", "12:00", "理科楼 207")],
        },
      ],
    }),
    course({
      code: "WRT201",
      title: "技术写作",
      credits: 2,
      role: "general_ed",
      department: "写作中心",
      attributes: ["表达"],
      prerequisites: [],
      corequisites: [],
      substitutes: ["ENG210"],
      exclusions: [],
      offerings: [
        {
          id: "wrt201-a",
          instructor: "写作中心（演示）",
          modality: "hybrid",
          capacity: 30,
          enrolled: 26,
          timeSlots: [slot("Thu", "16:00", "17:30", "文科楼 118")],
        },
      ],
    }),
  ],
  prefix: {
    id: "prefix-nan-2026-fall-v3",
    studentId: "student-nan-fixture",
    version: 3,
    completed: [
      { courseId: "CAL101", semester: "2025-Fall", creditsEarned: 4 },
      { courseId: "PHY101", semester: "2025-Fall", creditsEarned: 4 },
      { courseId: "PRG100", semester: "2026-Spring", creditsEarned: 3 },
    ],
    inProgress: [
      { courseId: "SLS200", semester: "2026-Spring", status: "enrolled" },
    ],
    planned: [
      {
        courseId: "SLS201",
        offeringId: "sls201-a",
        targetSemester: "2026-Fall",
        priority: 1,
      },
      {
        courseId: "CIR220",
        offeringId: "cir220-a",
        targetSemester: "2026-Fall",
        priority: 2,
      },
      {
        courseId: "MAT313",
        offeringId: "mat313-a",
        targetSemester: "2026-Fall",
        priority: 3,
      },
      {
        courseId: "OPT210",
        offeringId: "opt210-a",
        targetSemester: "2026-Fall",
        priority: 4,
      },
      {
        courseId: "ENG210",
        offeringId: "eng210-a",
        targetSemester: "2026-Fall",
        priority: 5,
      },
      {
        courseId: "DAT210",
        offeringId: "dat210-a",
        targetSemester: "2026-Fall",
        priority: 6,
      },
    ],
    dropped: [
      {
        courseId: "WRT201",
        semester: "2026-Fall",
        reason: "仅作为 What-if 备选",
      },
    ],
    totalCreditsEarned: 11,
  },
  pins: [
    {
      id: "pin-sls-section",
      type: "required_course",
      courseId: "SLS201",
      offeringId: "sls201-a",
      timeSlot: null,
      semester: "2026-Fall",
      lockReason: "专业培养方案核心课；保留已确认班次",
      lockedBy: "student",
    },
    {
      id: "pin-friday-commitment",
      type: "personal_commitment",
      courseId: null,
      offeringId: null,
      timeSlot: slot("Fri", "12:00", "13:30", "学生个人安排"),
      semester: "2026-Fall",
      lockReason: "每周固定个人承诺，不允许求解器移动",
      lockedBy: "student",
    },
    {
      id: "pin-circuits-section",
      type: "required_course",
      courseId: "CIR220",
      offeringId: "cir220-a",
      timeSlot: null,
      semester: "2026-Fall",
      lockReason: "希望与实验搭配；启用后锁定当前班次",
      lockedBy: "student",
    },
  ],
  preferences: {
    timeOfDay: "daytime",
    compactness: 2,
    variety: 2,
    stability: 3,
  },
  goalOrder: [
    "hard_constraints",
    "graduation_progress",
    "minimal_change",
    "personal_preference",
    "minimal_gaps",
  ],
  planTemplates: [
    {
      id: "template-baseline",
      label: "方案 A · 稳定阵容",
      strategy: "最少改动，保留当前 Prefix 的六门拟选与已确认班次。",
      selections: [
        { courseId: "SLS201", offeringId: "sls201-a" },
        { courseId: "CIR220", offeringId: "cir220-a" },
        { courseId: "MAT313", offeringId: "mat313-a" },
        { courseId: "OPT210", offeringId: "opt210-a" },
        { courseId: "ENG210", offeringId: "eng210-a" },
        { courseId: "DAT210", offeringId: "dat210-a" },
      ],
    },
    {
      id: "template-late",
      label: "方案 B · 午后专注",
      strategy: "避开早课，加入实验和科研方法；迁移成本高于方案 A。",
      selections: [
        { courseId: "SLS201", offeringId: "sls201-a" },
        { courseId: "CIR220", offeringId: "cir220-a" },
        { courseId: "MAT313", offeringId: "mat313-b" },
        { courseId: "EGR201", offeringId: "egr201-a" },
        { courseId: "ENG210", offeringId: "eng210-b" },
        { courseId: "RES101", offeringId: "res101-a" },
      ],
    },
    {
      id: "template-explore",
      label: "方案 C · 跨域探索",
      strategy: "保留专业主线，并加入人因设计与科研方法两个跨域入口。",
      selections: [
        { courseId: "SLS201", offeringId: "sls201-a" },
        { courseId: "CIR220", offeringId: "cir220-a" },
        { courseId: "MAT313", offeringId: "mat313-b" },
        { courseId: "OPT210", offeringId: "opt210-a" },
        { courseId: "HCI205", offeringId: "hci205-a" },
        { courseId: "RES101", offeringId: "res101-a" },
      ],
    },
    {
      id: "template-deep-tech",
      label: "方案 D · 技术纵深",
      strategy: "用现代物理与机器智能替代应用光学，专业负荷更集中。",
      selections: [
        { courseId: "SLS201", offeringId: "sls201-a" },
        { courseId: "CIR220", offeringId: "cir220-a" },
        { courseId: "MAT313", offeringId: "mat313-b" },
        { courseId: "PHY240", offeringId: "phy240-a" },
        { courseId: "AI220", offeringId: "ai220-a" },
      ],
    },
    {
      id: "template-writing",
      label: "方案 E · 表达与项目",
      strategy: "加入工程实验和技术写作，平衡专业训练与表达能力。",
      selections: [
        { courseId: "SLS201", offeringId: "sls201-a" },
        { courseId: "CIR220", offeringId: "cir220-a" },
        { courseId: "MAT313", offeringId: "mat313-b" },
        { courseId: "EGR201", offeringId: "egr201-a" },
        { courseId: "WRT201", offeringId: "wrt201-a" },
        { courseId: "DAT210", offeringId: "dat210-a" },
      ],
    },
  ],
};
