import type {
  RoleDestination,
  RoleFixture,
  RoleNavigationItem,
  RoleProfile,
} from "./types";

const home = (): RoleDestination => ({ type: "home" });
const panel = (
  panelName: "courses" | "evidence",
): RoleDestination => ({ type: "panel", panel: panelName });
const module = (
  experience: Extract<RoleDestination, { type: "module" }>["experience"],
  smartCourseEntry?: Extract<
    RoleDestination,
    { type: "module" }
  >["smartCourseEntry"],
): RoleDestination => ({
  type: "module",
  experience,
  ...(smartCourseEntry ? { smartCourseEntry } : {}),
});
const planned = (label: string): RoleDestination => ({
  type: "planned",
  label,
});

const studentNavigation: RoleNavigationItem[] = [
  { id: "schedule", label: "我的赛程", icon: "home", destination: home() },
  {
    id: "courses",
    label: "课程与考试",
    icon: "course",
    destination: panel("courses"),
  },
  {
    id: "mirror",
    label: "Academic Mirror",
    icon: "mirror",
    destination: module("academicmirror"),
  },
  {
    id: "roster",
    label: "Roster Lab",
    icon: "roster",
    destination: module("rosterlab"),
  },
  {
    id: "exams",
    label: "World Finals",
    icon: "exam",
    destination: module("worldexam"),
  },
  {
    id: "performance",
    label: "生涯数据",
    icon: "performance",
    destination: module("performancecenter"),
  },
  {
    id: "opportunities",
    label: "机会市场",
    icon: "opportunity",
    destination: module("opportunitymarket"),
  },
  {
    id: "scouting",
    label: "课程球探",
    icon: "scouting",
    destination: module("coachscouting"),
  },
  {
    id: "campus",
    label: "校园生活",
    icon: "campus",
    destination: module("campuslife"),
  },
  {
    id: "campuspass",
    label: "校园通行",
    icon: "pass",
    destination: module("campuspass"),
  },
];

const student: RoleProfile = {
  id: "student",
  formalRole: "学生",
  gameMode: "MYCAREER",
  shortLabel: "学生端",
  displayName: "南同学 NAN（Fixture）",
  organization: "电子信息学院 · 2026 春季",
  identityLine: "本科第 4 / 8 赛季 · SLS 240 必修",
  roleSummary: "学习、选课、成长、机会与校园生活的本人视角。",
  periodLabel: "第 4 / 8 赛季",
  headline: "把大学四到八年变成可解释、可回放的生涯",
  briefing:
    "学生只看到与本人任务有关的镜像、建议和证据；正式成绩、学籍、支付与门禁决定仍留在学校权威系统。",
  coachNote: "先看来源，再做选择；卡住不是判负，换条路径继续。",
  primaryActionLabel: "继续今日赛程",
  primaryDestination: module("smartcourse", "student"),
  accent: "orange",
  authority: "demo_fixture",
  requiresProductionSso: true,
  navigation: studentNavigation,
  priorities: [],
  metrics: [],
  visibleScope: ["本人课程与进度", "本人授权档案", "本人选择与申诉入口"],
  prohibitedScope: ["他人私密数据", "教师人事材料", "学校内部审批意见"],
};

const teacher: RoleProfile = {
  id: "teacher",
  formalRole: "教师",
  gameMode: "COACH STUDIO",
  shortLabel: "教师端",
  displayName: "林老师（Fixture）",
  organization: "电子信息学院 · SLS 240 课程组",
  identityLine: "课程负责人 · 信号与线性系统 · 2026 春季",
  roleSummary: "设计课程、审核 AI 内容、解释反馈并留下改进证据。",
  periodLabel: "2026 春季教学赛季",
  headline: "把 3 条教学证据变成下一轮可审核改进",
  briefing:
    "今天先处理来源完整的内容审核，再检查一个学习难点。所有建议都只是候选，教师保留发布与课程调整决定权。",
  coachNote: "学生反馈描述的是学习体验，不是教师人格，也不是一张 OVR。",
  primaryActionLabel: "进入内容审核席",
  primaryDestination: module("smartcourse", "review"),
  accent: "blue",
  authority: "demo_fixture",
  requiresProductionSso: true,
  navigation: [
    { id: "coach-home", label: "今日教练席", icon: "home", destination: home() },
    {
      id: "course-studio",
      label: "课程工作坊",
      icon: "course",
      destination: module("smartcourse", "authoring"),
    },
    {
      id: "review-queue",
      label: "内容审核席",
      icon: "evidence",
      destination: module("smartcourse", "review"),
    },
    {
      id: "teaching-replay",
      label: "Teaching Replay",
      icon: "performance",
      destination: module("smartcourse", "replay"),
    },
    {
      id: "course-film-room",
      label: "课程 Film Room",
      icon: "scouting",
      destination: module("coachscouting"),
    },
    {
      id: "research-opportunities",
      label: "科研与机会",
      icon: "opportunity",
      destination: module("opportunitymarket"),
    },
    {
      id: "faculty-portfolio",
      label: "教学档案",
      icon: "policy",
      destination: planned("F-013 教学档案与晋升证据"),
    },
  ],
  priorities: [
    {
      id: "teacher-review",
      kicker: "P0 · 来源先于发布",
      title: "审核 12 项 AI 教学草稿",
      detail: "逐项查看来源、修改、通过或移除；未通过内容不能进入学生端。",
      status: "12 待审核",
      sourceLabel: "F-001 Fixture",
      icon: "evidence",
      destination: module("smartcourse", "review"),
    },
    {
      id: "teacher-bottleneck",
      kicker: "FILM ROOM · 不轻率归因",
      title: "复核 Bode 图学习难点",
      detail: "区分前置知识、题目表述、材料对齐和样本不足，再选择干预。",
      status: "3 条证据",
      sourceLabel: "F-007 Fixture",
      icon: "scouting",
      destination: module("coachscouting"),
    },
    {
      id: "teacher-alignment",
      kicker: "NEXT MOVE · 教师确认",
      title: "检查目标—活动—考核对齐",
      detail: "系统只提供候选缺口和替代方案，不自动修改课程或评分规则。",
      status: "1 待确认",
      sourceLabel: "F-013 Vision",
      icon: "course",
      destination: module("smartcourse", "authoring"),
    },
  ],
  metrics: [
    {
      label: "待审核",
      value: "12",
      detail: "只含有来源对象",
      tone: "orange",
    },
    {
      label: "来源覆盖",
      value: "100%",
      detail: "Fixture 发布门禁",
      tone: "green",
    },
    {
      label: "改进回合",
      value: "3",
      detail: "保留版本与 Replay",
      tone: "blue",
    },
    {
      label: "公开教师排名",
      value: "0",
      detail: "禁止 OVR 与天梯",
      tone: "violet",
    },
  ],
  visibleScope: ["本人课程", "本人教学档案", "授权聚合反馈", "课程组协作材料"],
  prohibitedScope: ["学生无关隐私", "匿名反馈身份", "他人教师人事材料", "自动绩效结论"],
};

const advisor: RoleProfile = {
  id: "advisor",
  formalRole: "辅导员 / 学业导师",
  gameMode: "PLAYER DEVELOPMENT",
  shortLabel: "辅导员端",
  displayName: "陈辅导员（Fixture）",
  organization: "学生发展中心 · 电子信息学院",
  identityLine: "授权 Case 视图 · 48 名学生 · 非诊断系统",
  roleSummary: "围绕预约、学业路径、转介和跟进提供人本支持。",
  periodLabel: "2026 春季支持周期",
  headline: "先处理 3 个可解释、可退出的学生支持 Case",
  briefing:
    "每项提醒必须说明触发原因、数据时间和正式责任方。敏感健康、消费与门禁数据不会进入暗中画像。",
  coachNote: "提醒不是判决；先联系本人、核对情况，再决定是否需要支持。",
  primaryActionLabel: "打开学业路径 Case",
  primaryDestination: module("rosterlab"),
  accent: "teal",
  authority: "demo_fixture",
  requiresProductionSso: true,
  navigation: [
    { id: "advisor-home", label: "支持工作台", icon: "home", destination: home() },
    {
      id: "advisor-cases",
      label: "Case Desk",
      icon: "people",
      destination: planned("F-014 Advising / Case Management"),
    },
    {
      id: "advisor-mirror",
      label: "授权档案镜像",
      icon: "mirror",
      destination: module("academicmirror"),
    },
    {
      id: "advisor-roster",
      label: "学业路径",
      icon: "roster",
      destination: module("rosterlab"),
    },
    {
      id: "advisor-support",
      label: "校园支持",
      icon: "campus",
      destination: module("campuslife"),
    },
    {
      id: "advisor-opportunity",
      label: "机会与转介",
      icon: "opportunity",
      destination: module("opportunitymarket"),
    },
    {
      id: "advisor-evidence",
      label: "本人可见回执",
      icon: "evidence",
      destination: panel("evidence"),
    },
  ],
  priorities: [
    {
      id: "advisor-path",
      kicker: "PATH CASE · 本人参与",
      title: "核对一项先修冲突与替代路径",
      detail: "与学生共同比较三套方案；辅导员不能代替学生锁定正式选课。",
      status: "今天 16:00",
      sourceLabel: "F-004 Fixture",
      icon: "roster",
      destination: module("rosterlab"),
    },
    {
      id: "advisor-followup",
      kicker: "FOLLOW-UP · 最小披露",
      title: "跟进一项校园支持转介",
      detail: "只查看服务状态与下一步，不展示无关诊断、金额或谈话原文。",
      status: "1 待回复",
      sourceLabel: "F-008 Fixture",
      icon: "campus",
      destination: module("campuslife"),
    },
    {
      id: "advisor-opportunity",
      kicker: "OPPORTUNITY · 资格可解释",
      title: "复核科研机会的资格缺口",
      detail: "显示规则、未知项和正式申请入口；不自动投递，也不公开学生排名。",
      status: "2 个候选",
      sourceLabel: "F-009 Fixture",
      icon: "opportunity",
      destination: module("opportunitymarket"),
    },
  ],
  metrics: [
    {
      label: "待跟进 Case",
      value: "3",
      detail: "按责任与时限排序",
      tone: "orange",
    },
    {
      label: "本人可见状态",
      value: "100%",
      detail: "必要状态可纠错",
      tone: "green",
    },
    {
      label: "已记录转介",
      value: "4",
      detail: "目的与期限可见",
      tone: "blue",
    },
    {
      label: "敏感诊断",
      value: "0",
      detail: "不采集、不推断",
      tone: "violet",
    },
  ],
  visibleScope: ["本人负责的 Case", "学生授权目标", "必要学业状态", "转介状态"],
  prohibitedScope: ["无关诊断", "完整消费记录", "精细门禁轨迹", "隐藏风险分与处分建议"],
};

const programLead: RoleProfile = {
  id: "program_lead",
  formalRole: "专业负责人 / 系主任",
  gameMode: "PROGRAM FRONT OFFICE",
  shortLabel: "专业端",
  displayName: "周主任（Fixture）",
  organization: "电子信息工程专业 · 培养方案工作组",
  identityLine: "专业版本 2026.1 · 课程依赖与资源 What-if",
  roleSummary: "管理培养方案、课程依赖、跨院协商与质量改进。",
  periodLabel: "2026 培养方案周期",
  headline: "模拟先修课调整，先看影响再提交",
  briefing:
    "培养方案修改先进入沙盒：展示受影响学生路径、课程容量、跨院依赖和未知项，正式发布仍走学校审批。",
  coachNote: "课程不是孤岛；改一条前置规则，先把四年路径和受影响人群都看清。",
  primaryActionLabel: "进入培养方案 What-if",
  primaryDestination: module("rosterlab"),
  accent: "gold",
  authority: "demo_fixture",
  requiresProductionSso: true,
  navigation: [
    { id: "program-home", label: "专业战情室", icon: "home", destination: home() },
    {
      id: "program-curriculum",
      label: "培养方案图谱",
      icon: "roster",
      destination: module("rosterlab"),
    },
    {
      id: "program-course",
      label: "课程版本",
      icon: "course",
      destination: module("smartcourse", "review"),
    },
    {
      id: "program-mirror",
      label: "来源与版本",
      icon: "mirror",
      destination: module("academicmirror"),
    },
    {
      id: "program-quality",
      label: "课程质量",
      icon: "scouting",
      destination: module("coachscouting"),
    },
    {
      id: "program-capacity",
      label: "容量与资源",
      icon: "policy",
      destination: planned("F-014 课程、教室与容量优化"),
    },
  ],
  priorities: [
    {
      id: "program-prerequisite",
      kicker: "WHAT-IF · 不直接发布",
      title: "模拟 SLS 240 先修规则调整",
      detail: "比较严格前置、并修支持和替代诊断三种方案及最小冲突集。",
      status: "3 个方案",
      sourceLabel: "F-004 Fixture",
      icon: "roster",
      destination: module("rosterlab"),
    },
    {
      id: "program-version",
      kicker: "VERSION · 一数一源",
      title: "复核课程目录与大纲版本冲突",
      detail: "查看字段血缘、新鲜度和责任方，再决定退回修订还是进入审批。",
      status: "1 个冲突",
      sourceLabel: "F-003 Fixture",
      icon: "mirror",
      destination: module("academicmirror"),
    },
    {
      id: "program-quality",
      kicker: "QUALITY · 多源证据",
      title: "检查一项课程改进假设",
      detail: "学生体验、同行观察和学习证据分开呈现，不生成教师总分。",
      status: "待讨论",
      sourceLabel: "F-007 / F-013",
      icon: "scouting",
      destination: module("coachscouting"),
    },
  ],
  metrics: [
    {
      label: "培养方案版本",
      value: "4",
      detail: "适用人群可追溯",
      tone: "blue",
    },
    {
      label: "待协商课程",
      value: "2",
      detail: "跨院依赖未确认",
      tone: "orange",
    },
    {
      label: "受影响路径",
      value: "18",
      detail: "Fixture 情景估算",
      tone: "violet",
    },
    {
      label: "自动正式发布",
      value: "0",
      detail: "必须人工审批",
      tone: "green",
    },
  ],
  visibleScope: ["本专业培养方案", "课程聚合证据", "跨院依赖", "资源 What-if"],
  prohibitedScope: ["学生私密反思", "教师个人黑箱排名", "自动停课或处分", "未经审批正式发布"],
};

const undergraduateOffice: RoleProfile = {
  id: "undergraduate_office",
  formalRole: "本科生院 / 教务处",
  gameMode: "LEAGUE OFFICE",
  shortLabel: "学校端",
  displayName: "本科生院课程治理席（Fixture）",
  organization: "University2K26 Institutional Front Office",
  identityLine: "全校规则镜像 · 分级权限 · 政策 What-if",
  roleSummary: "处理课程治理、学籍服务、资源规划和政策影响模拟。",
  periodLabel: "2026 校级治理周期",
  headline: "审阅一项课程规则变更及其全校影响",
  briefing:
    "本界面只汇总带来源的只读镜像和模拟结果。课程、学籍、人事、资助与处分的正式决定仍留在责任部门。",
  coachNote: "学校端看到更多，不代表可以看见一切；权限还要同时满足范围、目的和时限。",
  primaryActionLabel: "打开校级影响审阅",
  primaryDestination: module("academicmirror"),
  accent: "violet",
  authority: "demo_fixture",
  requiresProductionSso: true,
  navigation: [
    { id: "office-home", label: "校级 Front Office", icon: "home", destination: home() },
    {
      id: "office-governance",
      label: "课程治理",
      icon: "policy",
      destination: module("rosterlab"),
    },
    {
      id: "office-mirror",
      label: "权威来源镜像",
      icon: "mirror",
      destination: module("academicmirror"),
    },
    {
      id: "office-quality",
      label: "教学质量",
      icon: "scouting",
      destination: module("coachscouting"),
    },
    {
      id: "office-support",
      label: "学生支持",
      icon: "people",
      destination: module("campuslife"),
    },
    {
      id: "office-policy",
      label: "政策 What-if",
      icon: "action",
      destination: planned("F-014 政策 What-if 与治理"),
    },
    {
      id: "office-audit",
      label: "Evidence Pack",
      icon: "evidence",
      destination: panel("evidence"),
    },
  ],
  priorities: [
    {
      id: "office-impact",
      kicker: "GOVERNANCE · 版本化审批",
      title: "复核课程规则变更的影响包",
      detail: "检查假设、数据版本、受影响群体、跨院意见和回滚条件。",
      status: "5 个审批节点",
      sourceLabel: "F-014 Vision",
      icon: "policy",
      destination: module("rosterlab"),
    },
    {
      id: "office-source",
      kicker: "SOURCE DOCK · 权威与镜像分离",
      title: "处理一项课程目录数据冲突",
      detail: "学校系统保留权威记录；体验层只做复核、解释和纠错入口。",
      status: "需责任方确认",
      sourceLabel: "F-003 Fixture",
      icon: "mirror",
      destination: module("academicmirror"),
    },
    {
      id: "office-teaching",
      kicker: "QUALITY · 不做教师 OVR",
      title: "审阅多模态教学改进证据",
      detail: "课程调查、同行观察、教师自评和成果证据分别展示上下文。",
      status: "4 类证据",
      sourceLabel: "F-007 / F-013",
      icon: "scouting",
      destination: module("coachscouting"),
    },
  ],
  metrics: [
    {
      label: "审批节点",
      value: "5",
      detail: "责任人与时限明确",
      tone: "orange",
    },
    {
      label: "待核验假设",
      value: "4",
      detail: "禁止伪装确定性",
      tone: "violet",
    },
    {
      label: "受影响群体",
      value: "3",
      detail: "仅聚合 Fixture",
      tone: "blue",
    },
    {
      label: "AI 正式决定",
      value: "0",
      detail: "人工责任不外包",
      tone: "green",
    },
  ],
  visibleScope: ["职责范围内聚合数据", "课程与政策版本", "审批状态", "影响模拟"],
  prohibitedScope: ["无目的个人明细", "学生私密反思", "隐藏教师排名", "AI 自动正式决定"],
};

export const ROLE_FIXTURE: RoleFixture = {
  schemaVersion: "1.0.0",
  generatedAt: "2026-07-24T14:45:00+08:00",
  authority: "demo_fixture",
  productionAuthentication: "external_sso_required",
  productionAuthorization: "server_enforced_required",
  workflow: ["Briefing", "Choose", "Execute", "Replay", "Next Move"],
  profiles: [student, teacher, advisor, programLead, undergraduateOffice],
};
