import type { InstitutionalState } from "./types";

export const INSTITUTIONAL_FIXTURE: InstitutionalState = {
  assignedStudents: [
    {
      id: "student-nan-fixture",
      displayName: "南同学 NAN（演示）",
      program: "电子信息工程",
      season: "本科第 4 / 8 赛季",
      consentScope: "学业路径 + 本人提交申请",
      openCaseCount: 2,
    },
    {
      id: "student-lin-fixture",
      displayName: "林同学（演示）",
      program: "自动化",
      season: "本科第 6 / 8 赛季",
      consentScope: "超修申请材料",
      openCaseCount: 1,
    },
    {
      id: "student-xu-fixture",
      displayName: "徐同学（演示）",
      program: "通信工程",
      season: "本科第 2 / 8 赛季",
      consentScope: "学习支持转介状态",
      openCaseCount: 1,
    },
  ],
  advisorCases: [
    {
      id: "case-accessibility-001",
      studentId: "student-nan-fixture",
      type: "accessibility",
      title: "考试无障碍安排申请",
      receivedAt: "2026-07-24 09:10",
      dueAt: "2026-07-25 16:00",
      status: "received",
      request: "学生申请低干扰考场与可访问的电子题面；具体安排需责任部门确认。",
      nextStep: "核对本人授权和材料完整性，再转介无障碍服务办公室。",
      purpose: "仅用于本次考试安排申请，不用于能力画像或课程排名。",
      permittedFields: ["申请项目", "课程与考试时段", "材料完整状态", "转介状态"],
      prohibitedFields: ["无关诊断原文", "消费记录", "门禁轨迹", "隐藏风险分"],
      sourceIds: ["case-fixture-accessibility-001", "policy-fixture-access-2026.1"],
    },
    {
      id: "case-path-002",
      studentId: "student-nan-fixture",
      type: "study_path",
      title: "SLS 240 前置冲突与替代路径",
      receivedAt: "2026-07-24 10:20",
      dueAt: "2026-07-27 18:00",
      status: "accepted_for_review",
      request: "学生希望比较并修支持、替代诊断和延后修读三条路径。",
      nextStep: "与学生共同查看 Roster Lab 三方案，不代替本人锁定正式选课。",
      purpose: "生成可解释的学业路径对话材料。",
      permittedFields: ["课程修读状态", "公开先修规则", "本人偏好", "时间冲突"],
      prohibitedFields: ["教师私密材料", "他人成绩", "自动毕业承诺"],
      sourceIds: ["roster-fixture-plan-001", "catalog-fixture-sls240-2026.1"],
    },
    {
      id: "case-overload-003",
      studentId: "student-lin-fixture",
      type: "course_overload",
      title: "超学分修读申请",
      receivedAt: "2026-07-24 11:05",
      dueAt: "2026-07-28 12:00",
      status: "awaiting_student",
      request: "学生申请下学期增加 3 学分，当前缺少时间负荷说明。",
      nextStep: "向学生请求负荷计划；系统不通过消费、睡眠或门禁数据补猜。",
      purpose: "受理学生主动提交的超修申请。",
      permittedFields: ["拟选课程", "公开学分规则", "本人负荷计划"],
      prohibitedFields: ["支付历史", "宿舍出入", "健康推断"],
      sourceIds: ["case-fixture-overload-003", "policy-fixture-credit-cap-2026.2"],
    },
    {
      id: "case-support-004",
      studentId: "student-xu-fixture",
      type: "study_path",
      title: "学习支持服务转介回执",
      receivedAt: "2026-07-23 16:40",
      dueAt: "2026-07-26 17:00",
      status: "referred",
      request: "学生本人请求学习策略门诊；辅导员只跟进预约状态。",
      nextStep: "等待服务中心返回预约是否成功，不读取谈话原文。",
      purpose: "本人授权的最小范围转介跟进。",
      permittedFields: ["预约状态", "下一步", "撤回入口"],
      prohibitedFields: ["咨询内容", "诊断", "与目的无关的记录"],
      sourceIds: ["support-referral-fixture-004"],
    },
  ],
  selectedStudentId: "student-nan-fixture",
  selectedCaseId: "case-accessibility-001",
  teachingItems: [
    {
      id: "teaching-bode-001",
      title: "Bode 图截止频率难点复盘",
      lane: "teaching_experiment",
      status: "ready_for_teacher",
      hypothesis: "学生混淆幅频截止点、带宽与横轴单位，单靠再讲一遍定义不足。",
      evidence: [
        "两道自动保存练习出现同类解释错误",
        "课程 Film Room 显示单位换算错误集中",
        "样本仍是演示数据，不能推断真实班级效果",
      ],
      sourceIds: ["sls240-node-frequency-response", "exam-fixture-f005-q1"],
    },
    {
      id: "teaching-review-002",
      title: "训练三 MATLAB/Python 现代化草稿",
      lane: "content_review",
      status: "needs_evidence",
      hypothesis: "把过时 API 改为现代等价写法，同时保留原始教学意图。",
      evidence: ["19 条技术问题审计", "原课件 65/65 页已完成视觉覆盖"],
      sourceIds: ["course-audit-sig-01-19", "course-source-coverage-6-files"],
    },
    {
      id: "teaching-research-003",
      title: "传感系统复现性研究方向",
      lane: "research_direction",
      status: "ready_for_teacher",
      hypothesis: "把时延、抖动与复现性作为课程 Capstone 的真实研究变量。",
      evidence: ["课程训练一至三形成模型—仿真—实测链", "公开作品证据可脱敏导出"],
      sourceIds: ["sls240-capstone-reproducibility", "portfolio-fixture-sls240"],
    },
  ],
  selectedTeachingItemId: "teaching-bode-001",
  curriculumChanges: [
    {
      id: "curriculum-sls240-prereq",
      title: "SLS 240 先修规则调整",
      currentRule: "MATH 201 通过后方可修读",
      proposedRule: "MATH 201 通过，或完成诊断 + 并修支持单元",
      affectedStudents: 18,
      capacityDelta: "支持课每周需新增 2 个助教时段",
      crossCollegeDependency: "数学学院需确认诊断题与等价能力边界",
      rollbackPoint: "2026.1 培养方案版本",
      status: "sandbox",
      sourceIds: ["catalog-fixture-sls240-2026.1", "roster-fixture-impact-018"],
    },
    {
      id: "curriculum-capstone-sequence",
      title: "Capstone 研究方法前置",
      currentRule: "第 7 赛季独立开课",
      proposedRule: "第 5 赛季嵌入复现性微单元，第 7 赛季完成综合项目",
      affectedStudents: 42,
      capacityDelta: "实验室峰值需求下降，导师检查点增加 1 次",
      crossCollegeDependency: "创新实践中心需确认开放实验室时段",
      rollbackPoint: "保留独立 Capstone 旧路径",
      status: "needs_revision",
      sourceIds: ["program-fixture-capstone-2026.1", "capacity-fixture-lab-02"],
    },
  ],
  selectedCurriculumChangeId: "curriculum-sls240-prereq",
  governanceCases: [
    {
      id: "governance-credit-policy-001",
      title: "跨院课程学分互认规则 What-if",
      version: "policy-sandbox-2026.3",
      affectedGroups: [
        { label: "2026 级电子信息", impact: "可识别 6 学分替代路径", unknown: "跨院容量未确认" },
        { label: "转专业学生", impact: "减少重复修读候选", unknown: "旧成绩映射需人工复核" },
        { label: "交换生", impact: "增加可解释匹配", unknown: "外校课程大纲版本差异" },
      ],
      approvalChain: [
        { owner: "专业工作组", state: "ready", reason: "影响说明已提交" },
        { owner: "学院教学委员会", state: "waiting", reason: "等待跨院意见" },
        { owner: "本科生院", state: "blocked", reason: "两个未知项尚未关闭" },
      ],
      rollbackCondition: "任一适用人群无法解释学分去向时退回 2026.2 规则。",
      status: "impact_review",
      sourceIds: ["policy-fixture-credit-transfer-2026.3", "mirror-fixture-catalog-conflict-01"],
    },
  ],
  selectedGovernanceCaseId: "governance-credit-policy-001",
  audit: [],
  advice: null,
  adviceState: "idle",
  message: "角色工作台已就位；当前人物和记录均为脱敏演示数据。",
};
