import type { PerformanceState } from "./types";

export const PERFORMANCE_FIXTURE: PerformanceState = {
  schemaVersion: "1.0.0",
  dataMode: "fixture",
  studentId: "student-nan-fixture",
  privateByDefault: true,
  comparisonMode: "self_only",
  step: "baseline",
  offline: false,
  simplified: false,
  reducedMotion: false,
  selectedMetricId: "metric-revision-quality",
  climateEnabled: false,
  climateVariant: "c_dimensions",
  sourceBoundary:
    "这里只看学习过程和本人主动填写的感受；GPA、排名、门禁、消费、深夜在线和健康数据不进场。",
  lastUpdatedAt: "2026-07-24T11:40:00+08:00",
  metrics: [
    {
      id: "metric-revision-quality",
      label: "有依据的修订",
      unit: "次 / 14 天",
      definition: "学生在查看来源后，对学习对象作出的可回放有效修订次数。",
      purpose: "观察近期迭代行为，并寻找可继续复用的学习策略。",
      limitation: "次数不代表质量、能力或成绩；缺少教师反馈时只描述行为。",
      correctionRoute: "从 Replay 指出误计事件，进入人工校对队列。",
      version: "metric-r1",
      sourceTypes: ["learning_event", "review_object"],
      canCorrect: true,
      comparisonMode: "self_only",
    },
    {
      id: "metric-source-checks",
      label: "主动核对来源",
      unit: "次 / 14 天",
      definition: "在答题、复习或修改前主动打开定位来源的次数。",
      purpose: "帮助学生发现哪些任务需要先核对证据。",
      limitation: "打开来源不等于理解来源，也不能用于公开排名。",
      correctionRoute: "从 Evidence Pack 报告重复或错误事件。",
      version: "metric-r1",
      sourceTypes: ["learning_event"],
      canCorrect: true,
      comparisonMode: "self_only",
    },
    {
      id: "metric-task-clarity",
      label: "任务清晰度",
      unit: "有 Done 与来源的任务",
      definition: "未来七天任务中，同时具有要求、完成口径、来源和下一步的任务数。",
      purpose: "把模糊要求暴露给学生和教师，而不是归咎学生。",
      limitation: "只表示任务信息完整度，不表示任务容易或学生能力。",
      correctionRoute: "课程任务信息有误时，提交课程镜像校对。",
      version: "metric-r1",
      sourceTypes: ["academic_mirror", "review_object"],
      canCorrect: true,
      comparisonMode: "self_only",
    },
    {
      id: "metric-deadline-density",
      label: "期限密度",
      unit: "个 / 7 天",
      definition: "未来七天已知截止任务数量与冲突情况。",
      purpose: "提前发现聚集风险并安排缓冲。",
      limitation: "只包含已授权、仍新鲜的任务；遗漏不等于没有任务。",
      correctionRoute: "从 Academic Mirror 核对课程日历与到期时间。",
      version: "metric-r1",
      sourceTypes: ["academic_mirror"],
      canCorrect: true,
      comparisonMode: "self_only",
    },
    {
      id: "metric-capacity",
      label: "承诺 / 可用容量",
      unit: "小时 / 周",
      definition: "本人主动填写的本周可用时间与已承诺任务时间。",
      purpose: "帮助调整计划，不把资源不足写成个人失败。",
      limitation: "完全依赖本人短期自报；不从设备、门禁或在线时段推断。",
      correctionRoute: "本人可随时修改或删除自报时间。",
      version: "metric-r1",
      sourceTypes: ["self_report"],
      canCorrect: true,
      comparisonMode: "self_only",
    },
    {
      id: "metric-recovery",
      label: "恢复感受",
      unit: "本人自报",
      definition: "本人可选填写的短期恢复感受，仅用于当前计划调整。",
      purpose: "让减压动作以本人感受为依据，而不是监控推断。",
      limitation: "不是医学或心理诊断；不提供时不影响任何基本权益。",
      correctionRoute: "本人可立即修改、撤回或删除。",
      version: "metric-r1",
      sourceTypes: ["self_report"],
      canCorrect: true,
      comparisonMode: "self_only",
    },
  ],
  observations: [
    {
      id: "obs-revision-quality",
      metricId: "metric-revision-quality",
      value: 3,
      displayValue: "3 次",
      rangeLabel: "比本人前一窗口多 1 次",
      periodStart: "2026-07-11",
      periodEnd: "2026-07-24",
      updatedAt: "2026-07-24T10:39:00+08:00",
      expiresAt: "2026-08-01T10:39:00+08:00",
      sourceIds: ["ev-revision-001", "ev-review-001"],
      confidence: "medium",
      confidenceReason: "事件可回放，但样本窗口只有 14 天。",
      dataGaps: ["7 月 17 日离线学习未产生结构化修订事件。"],
      trend: [
        { period: "W1", label: "6/27", value: 1, status: "observed" },
        { period: "W2", label: "7/04", value: 2, status: "observed" },
        { period: "W3", label: "7/11", value: null, status: "gap" },
        { period: "W4", label: "7/18", value: 3, status: "observed" },
        { period: "W5", label: "7/24", value: 3, status: "observed" },
      ],
    },
    {
      id: "obs-source-checks",
      metricId: "metric-source-checks",
      value: 5,
      displayValue: "5 次",
      rangeLabel: "本人近期窗口：3–5 次",
      periodStart: "2026-07-11",
      periodEnd: "2026-07-24",
      updatedAt: "2026-07-24T10:39:00+08:00",
      expiresAt: "2026-08-01T10:39:00+08:00",
      sourceIds: ["ev-source-open-001", "ev-exam-source-001"],
      confidence: "medium",
      confidenceReason: "只计算显式打开 Evidence 的事件，不推断是否真正阅读。",
      dataGaps: ["纸面笔记与外部阅读不在此记录。"],
      trend: [
        { period: "W1", label: "6/27", value: 2, status: "observed" },
        { period: "W2", label: "7/04", value: 3, status: "observed" },
        { period: "W3", label: "7/11", value: 3, status: "observed" },
        { period: "W4", label: "7/18", value: 4, status: "observed" },
        { period: "W5", label: "7/24", value: 5, status: "observed" },
      ],
    },
    {
      id: "obs-task-clarity",
      metricId: "metric-task-clarity",
      value: 5,
      displayValue: "5 / 6",
      rangeLabel: "1 项仍缺少清晰 Done",
      periodStart: "2026-07-24",
      periodEnd: "2026-07-31",
      updatedAt: "2026-07-24T11:20:00+08:00",
      expiresAt: "2026-07-25T11:20:00+08:00",
      sourceIds: ["ev-mirror-course-001", "ev-review-001"],
      confidence: "low",
      confidenceReason: "课程目录接近过期，且有一项要求待教师确认。",
      dataGaps: ["工程训练任务的完成口径仍未知。"],
      trend: [
        { period: "D1", label: "周一", value: 4, status: "observed" },
        { period: "D2", label: "周二", value: 4, status: "observed" },
        { period: "D3", label: "周三", value: null, status: "gap" },
        { period: "D4", label: "周四", value: 5, status: "observed" },
      ],
    },
    {
      id: "obs-deadline-density",
      metricId: "metric-deadline-density",
      value: 4,
      displayValue: "4 个",
      rangeLabel: "其中 2 个集中在 48 小时内",
      periodStart: "2026-07-24",
      periodEnd: "2026-07-31",
      updatedAt: "2026-07-24T11:20:00+08:00",
      expiresAt: "2026-07-25T11:20:00+08:00",
      sourceIds: ["ev-mirror-course-001", "ev-season-deadline-001"],
      confidence: "medium",
      confidenceReason: "只包含当前授权课程镜像；可能遗漏未导入活动。",
      dataGaps: ["未授权社团与个人事务不在系统中。"],
      trend: [
        { period: "D1", label: "周五", value: 1, status: "observed" },
        { period: "D2", label: "周六", value: 0, status: "observed" },
        { period: "D3", label: "周日", value: 2, status: "observed" },
        { period: "D4", label: "周一", value: 1, status: "observed" },
      ],
    },
    {
      id: "obs-capacity",
      metricId: "metric-capacity",
      value: 34,
      displayValue: "34 / 36 小时",
      rangeLabel: "本人保留 2 小时缓冲",
      periodStart: "2026-07-21",
      periodEnd: "2026-07-27",
      updatedAt: "2026-07-24T11:32:00+08:00",
      expiresAt: null,
      sourceIds: ["ev-self-capacity-001"],
      confidence: "low",
      confidenceReason: "本人自报计划，不等于实际投入。",
      dataGaps: ["临时照护、通勤与不可预见任务可能改变容量。"],
      trend: [
        { period: "W1", label: "上周", value: 31, status: "observed" },
        { period: "W2", label: "本周", value: 34, status: "observed" },
      ],
    },
    {
      id: "obs-recovery",
      metricId: "metric-recovery",
      value: null,
      displayValue: "需要缓冲",
      rangeLabel: "本人主动填写 · 可删除",
      periodStart: "2026-07-24",
      periodEnd: "2026-07-27",
      updatedAt: "2026-07-24T11:33:00+08:00",
      expiresAt: "2026-07-27T23:59:00+08:00",
      sourceIds: ["ev-self-recovery-001"],
      confidence: "low",
      confidenceReason: "敏感自报只描述本人当下感受，不转成分数。",
      dataGaps: [],
      trend: [],
    },
  ],
  abilities: [
    {
      id: "ability-knowledge",
      label: "知识理解",
      observedLabel: "4 / 5 次证据检查后答对",
      description: "只描述本期有来源的理解检查，不折算永久能力。",
      sourceIds: ["ev-exam-source-001"],
      confidence: "medium",
    },
    {
      id: "ability-applied",
      label: "应用与修订",
      observedLabel: "3 次可回放修订",
      description: "展示可观察作品行为，不把作品数量当能力等级。",
      sourceIds: ["ev-revision-001", "ev-review-001"],
      confidence: "medium",
    },
    {
      id: "ability-collaboration",
      label: "协作",
      observedLabel: "数据不足，暂不展示精确值",
      description: "没有授权的同伴反馈或小组事件，因此不猜测。",
      sourceIds: [],
      confidence: "insufficient",
    },
    {
      id: "ability-habit",
      label: "学习习惯",
      observedLabel: "5 / 7 个计划检查点已完成",
      description: "只比较本人近期计划，不追踪深夜在线或设备行为。",
      sourceIds: ["ev-season-deadline-001"],
      confidence: "low",
    },
  ],
  loadSignals: [
    {
      id: "load-credits",
      label: "课程承诺",
      displayValue: "18 学分",
      severity: "watch",
      textEquivalent: "这周课程安排偏满；学分来自演示课表，不代表学校正式状态。",
      sourceIds: ["ev-mirror-course-001"],
    },
    {
      id: "load-deadlines",
      label: "截止期限",
      displayValue: "4 个 / 7 天",
      severity: "high",
      textEquivalent: "未来七天有四个已知截止任务，其中两个集中在四十八小时内。",
      sourceIds: ["ev-season-deadline-001"],
    },
    {
      id: "load-time",
      label: "时间容量",
      displayValue: "34 / 36 小时",
      severity: "high",
      textEquivalent: "本人计划只剩两小时缓冲；临时责任可能尚未计入。",
      sourceIds: ["ev-self-capacity-001"],
    },
    {
      id: "load-feeling",
      label: "本人感受",
      displayValue: "需要缓冲",
      severity: "watch",
      textEquivalent: "本人主动填写短期恢复感受；不是医学或心理判断。",
      sourceIds: ["ev-self-recovery-001"],
    },
  ],
  supportActions: [
    {
      id: "support-plan-buffer",
      title: "先保留缓冲",
      action: "把工程训练草稿移动到周六上午，释放周日晚间 90 分钟。",
      availability: "可立即在 What-if 中预演，不修改正式课表。",
      sourceId: "ev-season-deadline-001",
    },
    {
      id: "support-office-hour",
      title: "带证据提问",
      action: "整理 1 个卷积来源冲突，预约信号与线性系统 Office Hours。",
      availability: "演示联系入口；真实预约请走课程官方渠道。",
      sourceId: "ev-support-001",
    },
    {
      id: "support-pause",
      title: "关闭状态提示",
      action: "暂时关闭 Academic Climate 和建议提醒，保留原始任务列表。",
      availability: "本机立即生效，不影响任何权益。",
      sourceId: "ev-self-recovery-001",
    },
  ],
  badges: [
    {
      id: "badge-source-challenger",
      title: "SOURCE CHALLENGER",
      subtitle: "来源挑战者",
      criteria: "在至少 3 个不同学习对象中主动查看并质疑可定位来源。",
      evidenceIds: ["ev-source-open-001", "ev-exam-source-001"],
      status: "earned",
      earnedAt: "2026-07-24T10:39:00+08:00",
      progressLabel: "3 / 3 个对象",
      private: true,
      affectsRights: false,
    },
    {
      id: "badge-revision-builder",
      title: "REVISION BUILDER",
      subtitle: "持续修订",
      criteria: "完成 3 次带前后版本与来源的有效修订。",
      evidenceIds: ["ev-revision-001", "ev-review-001"],
      status: "earned",
      earnedAt: "2026-07-24T10:38:00+08:00",
      progressLabel: "3 / 3 次修订",
      private: true,
      affectsRights: false,
    },
    {
      id: "badge-assist-play",
      title: "ASSIST PLAY",
      subtitle: "协作传球",
      criteria: "在本人同意的协作中留下 2 次可确认、非人气化的帮助记录。",
      evidenceIds: [],
      status: "in_progress",
      earnedAt: null,
      progressLabel: "数据不足 · 不猜测",
      private: true,
      affectsRights: false,
    },
  ],
  statusLabel: {
    id: "status-week-2026-30",
    words: "稳态，但期限密集",
    numberPreview: "98.6°F · 稳态（仅 A 版研究文案）",
    basisIds: [
      "obs-revision-quality",
      "obs-deadline-density",
      "obs-capacity",
      "obs-recovery",
    ],
    startsAt: "2026-07-24T00:00:00+08:00",
    expiresAt: "2026-07-28T00:00:00+08:00",
    withdrawnAt: null,
    private: true,
    nonMedical: true,
  },
  recommendations: [
    {
      id: "rec-buffer",
      title: "先腾出 90 分钟缓冲",
      basisIds: ["obs-deadline-density", "obs-capacity", "obs-recovery"],
      cost: "需要移动一个还没开始的演示任务。",
      expectedEffect: "减少 48 小时内的任务重叠；不保证成绩或效率提升。",
      alternative: "保留原计划，仅关闭非紧急提醒并寻求人工支持。",
      unknowns: ["临时通勤与照护时间尚未录入。"],
      generationMode: "rule_fixture",
      status: "open",
    },
    {
      id: "rec-source",
      title: "把一个来源冲突带进 Office Hours",
      basisIds: ["obs-source-checks", "obs-task-clarity"],
      cost: "整理问题约 10 分钟；预约时间由课程官方渠道决定。",
      expectedEffect: "让模糊要求由教师澄清，而不是继续猜测。",
      alternative: "先在智课工坊提交私密 Challenge Call。",
      unknowns: ["真实 Office Hours 可用性未连接。"],
      generationMode: "rule_fixture",
      status: "open",
    },
    {
      id: "rec-collaboration",
      title: "暂不生成协作能力建议",
      basisIds: [],
      cost: "无。",
      expectedEffect: "避免用缺失数据给学生贴标签。",
      alternative: "本人可主动导入一条授权协作记录，或继续保持空白。",
      unknowns: ["没有授权同伴反馈，也没有可验证协作事件。"],
      generationMode: "rule_fixture",
      status: "open",
    },
  ],
  shareGrants: [],
  corrections: [],
  harmSignals: [
    {
      id: "harm-climate-a-preflight",
      category: "score_misread",
      description: "数字版可能被误解为百分制成绩、医学体温或越高越好。",
      severity: "watch",
      status: "mitigated",
      actionTaken: "默认关闭数字隐喻；A 版只在明确研究预览中出现。",
      createdAt: "2026-07-24T09:00:00+08:00",
    },
  ],
  evidence: [
    {
      id: "ev-revision-001",
      type: "learning_event",
      sourceId: "F-001:interaction-sls-003",
      label: "信号与线性系统 · 三次来源后修订",
      locator: "Replay event 003–005",
      updatedAt: "2026-07-24T10:38:00+08:00",
      authority: "demo_fixture",
      freshness: "fresh",
      detail: "只记录已发布演示内容中的修订行为，不复制原课程材料。",
    },
    {
      id: "ev-review-001",
      type: "review_object",
      sourceId: "F-001:generated-sls-explainer-001",
      label: "教师审核对象与版本差异",
      locator: "review revision 3",
      updatedAt: "2026-07-24T10:35:00+08:00",
      authority: "demo_fixture",
      freshness: "fresh",
      detail: "教师审核来自演示流程，不代表真实教师评价。",
    },
    {
      id: "ev-source-open-001",
      type: "learning_event",
      sourceId: "F-001:evidence-open-bundle",
      label: "Evidence Drawer 主动打开事件",
      locator: "Replay source_open × 3",
      updatedAt: "2026-07-24T10:39:00+08:00",
      authority: "demo_fixture",
      freshness: "fresh",
      detail: "打开次数不等于理解程度。",
    },
    {
      id: "ev-exam-source-001",
      type: "learning_event",
      sourceId: "F-005:exam-source-challenge",
      label: "World Exam 来源挑战",
      locator: "match replay q-001",
      updatedAt: "2026-07-24T10:42:00+08:00",
      authority: "demo_fixture",
      freshness: "fresh",
      detail: "模拟赛事事件，不是正式考试或成绩。",
    },
    {
      id: "ev-mirror-course-001",
      type: "academic_mirror",
      sourceId: "F-003:nr-course-sls201",
      label: "课程目录镜像与字段来源",
      locator: "snapshot snap-catalog-001",
      updatedAt: "2026-07-23T16:00:00+08:00",
      authority: "demo_fixture",
      freshness: "warning",
      detail: "来源标为官方参考，但当前公开演示仍不是学校正式记录。",
    },
    {
      id: "ev-season-deadline-001",
      type: "academic_mirror",
      sourceId: "F-002:season-deadlines",
      label: "第 4 / 8 赛季截止日演示",
      locator: "career dashboard deadline deck",
      updatedAt: "2026-07-24T10:30:00+08:00",
      authority: "demo_fixture",
      freshness: "fresh",
      detail: "只用于演示期限聚集，不是学校正式日历。",
    },
    {
      id: "ev-self-capacity-001",
      type: "self_report",
      sourceId: "student-nan-fixture:capacity-week-30",
      label: "本人本周可用时间与承诺",
      locator: "private local input",
      updatedAt: "2026-07-24T11:32:00+08:00",
      authority: "self_declared",
      freshness: "no_expiry",
      detail: "本人可删除；不从行为日志反推。",
    },
    {
      id: "ev-self-recovery-001",
      type: "self_report",
      sourceId: "student-nan-fixture:recovery-2026-07-24",
      label: "本人短期恢复感受",
      locator: "private local input",
      updatedAt: "2026-07-24T11:33:00+08:00",
      authority: "self_declared",
      freshness: "fresh",
      detail: "不是医学或心理数据，不上传、不影响任何权益。",
    },
    {
      id: "ev-support-001",
      type: "support_directory",
      sourceId: "fixture:sls201-office-hours",
      label: "课程支持渠道样例",
      locator: "course detail support rail",
      updatedAt: "2026-07-24T10:30:00+08:00",
      authority: "demo_fixture",
      freshness: "warning",
      detail: "仅演示人工通道形态；真实时间需课程官方确认。",
    },
  ],
  researchGate: {
    status: "deferred_pending_human_evidence",
    defaultVariant: "c_dimensions",
    evidenceCount: 0,
    requiredParticipants: "6-10",
    variants: [
      {
        id: "a_numbers",
        label: "A · 数字隐喻",
        description: "60 / 70 / 98.6 / 100°F 离散文案；仅用于盲测，不作计算。",
      },
      {
        id: "b_words",
        label: "B · 文字状态",
        description: "回暖中 / 室温 / 稳态 / 过热，不显示数字。",
      },
      {
        id: "c_dimensions",
        label: "C · 无隐喻",
        description: "只显示负荷、期限、进度、清晰度、支持和未知项。",
      },
    ],
    stopConditions: [
      "重复被理解为正式成绩、医学诊断或越高越好。",
      "无法找到关闭、依据、纠错或减压入口。",
      "引发明显羞辱、焦虑或身份标签。",
    ],
  },
  audit: [
    {
      id: "perf-event-001",
      sequence: 1,
      action: "climate_toggle",
      targetId: "status-week-2026-30",
      detail: "数字隐喻默认关闭；C 版多维面板作为安全基线。",
      occurredAt: "2026-07-24T09:00:00+08:00",
      previousEventHash: null,
      eventHash: "fnv1a-perf-event-001",
    },
    {
      id: "perf-event-002",
      sequence: 2,
      action: "correction_request",
      targetId: "metric-catalog",
      detail: "指标目录已冻结为 self_only；没有跨人比较与 OVR。",
      occurredAt: "2026-07-24T09:05:00+08:00",
      previousEventHash: "fnv1a-perf-event-001",
      eventHash: "fnv1a-perf-event-002",
    },
  ],
  message:
    "私密演示记录已载入：每个数字都能回看出处；协作资料不足的地方不会硬凑精确值。",
};
