import type {
  CoachScoutingFixture,
  EvidenceSource,
  SourcedField,
} from "./types";

const source = (
  value: Omit<EvidenceSource, "correctionRoute" | "verified">,
): EvidenceSource => ({
  ...value,
  correctionRoute:
    "Fixture 信息可在 Coach Studio 提交纠错；正式课程信息请回到学校权威系统核对。",
  verified: value.tier !== "system_inference",
});

const field = (
  id: string,
  label: string,
  value: string,
  sourceId: string,
  effectiveTerm = "2026 Spring",
): SourcedField => ({
  id,
  label,
  value,
  sourceId,
  effectiveTerm,
});

export const COACH_SCOUTING_FIXTURE: CoachScoutingFixture = {
  schemaVersion: "1.0.0",
  dataMode: "demo_fixture",
  generatedAt: "2026-07-24T08:45:00+08:00",
  lastUpdatedAt: "2026-07-24T08:45:00+08:00",
  sources: [
    source({
      id: "src-teacher-confirmed",
      tier: "teacher_confirmed",
      label: "教师确认",
      owner: "林老师（Fixture）",
      version: "teacher-note-r3",
      updatedAt: "2026-07-23T16:20:00+08:00",
      expiresAt: "2026-09-01T00:00:00+08:00",
    }),
    source({
      id: "src-official-syllabus",
      tier: "official_syllabus",
      label: "官方大纲",
      owner: "示例大学课程目录",
      version: "SLS201-2026SP-v2",
      updatedAt: "2026-07-22T10:00:00+08:00",
      expiresAt: "2026-09-01T00:00:00+08:00",
    }),
    source({
      id: "src-history-2025",
      tier: "historical_version",
      label: "历史版本",
      owner: "2025 Spring 归档（Fixture）",
      version: "SLS201-2025SP-v4",
      updatedAt: "2025-06-30T12:00:00+08:00",
      expiresAt: null,
    }),
    source({
      id: "src-student-aggregate",
      tier: "student_aggregate",
      label: "学生自愿汇总",
      owner: "8 份结构化反馈（Fixture）",
      version: "aggregate-2026SP-r1",
      updatedAt: "2026-07-23T20:00:00+08:00",
      expiresAt: "2026-08-31T23:59:00+08:00",
    }),
    source({
      id: "src-system-inference",
      tier: "system_inference",
      label: "系统推断",
      owner: "University2K26 规则引擎",
      version: "rule-envelope-r1",
      updatedAt: "2026-07-24T08:30:00+08:00",
      expiresAt: "2026-07-31T23:59:00+08:00",
    }),
  ],
  course: {
    id: "course-profile-sls201-2026sp",
    courseId: "SLS201",
    offeringId: "offering-sls201-2026sp",
    term: "2026 Spring",
    title: "信号与线性系统",
    instructorId: "faculty-lin-fixture",
    instructorAssignmentId: "assignment-lin-sls201-2026sp",
    instructorDisplayName: "林老师（Fixture）",
    summary: field(
      "course-summary",
      "课程简介",
      "以连续与离散信号、系统性质、卷积、频域方法和工程证据为主线。",
      "src-official-syllabus",
    ),
    objectives: [
      field(
        "objective-model",
        "学习目标 1",
        "能把物理或工程现象转译为信号与系统模型。",
        "src-official-syllabus",
      ),
      field(
        "objective-evidence",
        "学习目标 2",
        "能用来源、推导和实验结果说明判断，而不是只给答案。",
        "src-teacher-confirmed",
      ),
    ],
    assessments: [
      { label: "每周练习", weight: 20, sourceId: "src-official-syllabus" },
      { label: "实验与复盘", weight: 25, sourceId: "src-official-syllabus" },
      { label: "期中检查", weight: 20, sourceId: "src-official-syllabus" },
      { label: "期末综合任务", weight: 35, sourceId: "src-teacher-confirmed" },
    ],
    textbooks: [
      field(
        "textbook-main",
        "主要材料",
        "课程讲义与经教师确认的公开参考章节；无强制付费平台。",
        "src-teacher-confirmed",
      ),
    ],
    prerequisites: [
      field(
        "prerequisite-calculus",
        "先修基础",
        "微积分、线性代数与基础电路；缺口可在开课前咨询。",
        "src-official-syllabus",
      ),
    ],
    updatedAt: "2026-07-23T16:20:00+08:00",
  },
  teaching: {
    offeringId: "offering-sls201-2026sp",
    activities: [
      {
        id: "activity-lecture",
        label: "讲授与推导",
        share: 40,
        frequency: "每周 2 次",
        sourceId: "src-teacher-confirmed",
      },
      {
        id: "activity-discussion",
        label: "讨论与直觉检验",
        share: 20,
        frequency: "每周 1 次",
        sourceId: "src-teacher-confirmed",
      },
      {
        id: "activity-lab",
        label: "实验与仿真",
        share: 25,
        frequency: "双周",
        sourceId: "src-official-syllabus",
      },
      {
        id: "activity-project",
        label: "小型项目",
        share: 15,
        frequency: "学期 2 次",
        sourceId: "src-official-syllabus",
      },
    ],
    homeworkFrequency: field(
      "homework-frequency",
      "作业频率",
      "通常每周一组；期中周可能调整，以课程公告为准。",
      "src-teacher-confirmed",
    ),
    feedbackMethod: field(
      "feedback-method",
      "反馈方式",
      "课堂讲评、Rubric、实验复盘与 Office Hours；不承诺固定返回日。",
      "src-teacher-confirmed",
    ),
    groupShare: field(
      "group-share",
      "小组占比",
      "项目部分约占总评 15%；个人贡献需要单独说明。",
      "src-official-syllabus",
    ),
  },
  officeHours: [
    {
      id: "office-hours-current",
      instructorAssignmentId: "assignment-lin-sls201-2026sp",
      schedule: "周二 16:00–17:30",
      location: "教学楼 B214 / 可预约在线",
      appointmentMethod: "课程系统预约或课后确认",
      suitableTopics: ["概念澄清", "实验设计", "复盘与申诉流程"],
      accessibility: ["电梯可达", "在线字幕可申请", "可提前提交问题"],
      sourceId: "src-teacher-confirmed",
      updatedAt: "2026-07-23T16:20:00+08:00",
      expiresAt: "2026-08-31T23:59:00+08:00",
      status: "active",
    },
    {
      id: "office-hours-expired",
      instructorAssignmentId: "assignment-lin-sls201-2026sp",
      schedule: "周四 12:30–13:00",
      location: "旧线上链接",
      appointmentMethod: "已停用",
      suitableTopics: ["历史记录"],
      accessibility: ["已过期，不应继续导航"],
      sourceId: "src-history-2025",
      updatedAt: "2025-06-01T08:00:00+08:00",
      expiresAt: "2025-07-01T00:00:00+08:00",
      status: "expired",
    },
  ],
  workload: [
    {
      id: "workload-teacher",
      label: "教师说明",
      minimum: 5,
      maximum: 8,
      unit: "hours_per_week",
      sampleSize: null,
      minimumSample: null,
      timeRange: "2026 Spring 课程设计",
      sourceId: "src-teacher-confirmed",
      publishable: true,
      caveat: "范围不是对个人用时的承诺。",
    },
    {
      id: "workload-aggregate",
      label: "学生自愿汇总",
      minimum: 6,
      maximum: 9,
      unit: "hours_per_week",
      sampleSize: 8,
      minimumSample: 5,
      timeRange: "2026-03-01 至 2026-06-20",
      sourceId: "src-student-aggregate",
      publishable: true,
      caveat: "仅代表 8 份结构化 Fixture 反馈，不代表全部学生。",
    },
    {
      id: "workload-insufficient",
      label: "实验周额外负荷",
      minimum: 2,
      maximum: 4,
      unit: "hours_per_week",
      sampleSize: 3,
      minimumSample: 5,
      timeRange: "2026-05 实验周",
      sourceId: "src-student-aggregate",
      publishable: false,
      caveat: "样本不足，暂不公开聚合结论。",
    },
  ],
  scouting: {
    offeringId: "offering-sls201-2026sp",
    preparedFor: [
      field(
        "prepared-math",
        "适合的准备",
        "愿意把微积分与线性代数用于解释具体系统。",
        "src-official-syllabus",
      ),
      field(
        "prepared-evidence",
        "适合的准备",
        "能保留推导、实验记录和来源。",
        "src-teacher-confirmed",
      ),
    ],
    challenges: [
      field(
        "challenge-abstraction",
        "可能挑战",
        "时域与频域之间需要反复切换；当前没有个人难度预测。",
        "src-system-inference",
      ),
      field(
        "challenge-group",
        "可能挑战",
        "项目包含小组协作，但个人证据仍需单独提交。",
        "src-official-syllabus",
      ),
    ],
    actions: [
      field(
        "action-preview",
        "建议动作",
        "开课前用一页例题核对卷积、复数与线性代数基础。",
        "src-teacher-confirmed",
      ),
      field(
        "action-office",
        "建议动作",
        "若先修证据不完整，带问题清单去 Office Hours，而不是自我淘汰。",
        "src-teacher-confirmed",
      ),
    ],
    unknowns: [
      field(
        "unknown-equipment",
        "未知",
        "下一学期实验设备清单尚待院系发布。",
        "src-system-inference",
      ),
      field(
        "unknown-section",
        "未知",
        "其他班次的教学结构不能从本班自动推断。",
        "src-system-inference",
      ),
    ],
  },
  versions: [
    {
      id: "version-2025sp",
      courseId: "SLS201",
      offeringId: "offering-sls201-2025sp",
      term: "2025 Spring",
      instructorId: "faculty-zhou-fixture",
      instructorAssignmentId: "assignment-zhou-sls201-2025sp",
      profileVersion: "SLS201-2025SP-v4",
      assessmentSummary: "作业 25% · 实验 20% · 期中 20% · 期末 35%",
      teachingSummary: "讲授 50% · 讨论 10% · 实验 25% · 项目 15%",
      sourceIds: ["src-history-2025"],
    },
    {
      id: "version-2026sp",
      courseId: "SLS201",
      offeringId: "offering-sls201-2026sp",
      term: "2026 Spring",
      instructorId: "faculty-lin-fixture",
      instructorAssignmentId: "assignment-lin-sls201-2026sp",
      profileVersion: "SLS201-2026SP-v2",
      assessmentSummary: "作业 20% · 实验 25% · 期中 20% · 期末综合任务 35%",
      teachingSummary: "讲授 40% · 讨论 20% · 实验 25% · 项目 15%",
      sourceIds: ["src-official-syllabus", "src-teacher-confirmed"],
    },
  ],
  feedbackAggregates: [
    {
      id: "aggregate-clarity",
      offeringId: "offering-sls201-2026sp",
      dimension: "assignment_clarity",
      sampleSize: 8,
      minimumSample: 5,
      timeRange: "2026-03-01 至 2026-06-20",
      summary: "多数反馈认为作业目标清楚，但实验报告示例需要更早发布。",
      suggestedAction: "在实验开始前一周发布去标识示例结构。",
      sourceId: "src-student-aggregate",
      published: true,
    },
    {
      id: "aggregate-accessibility",
      offeringId: "offering-sls201-2026sp",
      dimension: "accessibility",
      sampleSize: 3,
      minimumSample: 5,
      timeRange: "2026-05-01 至 2026-06-20",
      summary: "样本不足，不能形成公开结论。",
      suggestedAction: "继续自愿收集，不显示方向性判断。",
      sourceId: "src-student-aggregate",
      published: false,
    },
  ],
  teamFields: [
    {
      id: "team-skill-signal",
      label: "技能 · 信号建模",
      kind: "skill",
      value: "signal_modeling",
      selectable: true,
      private: true,
    },
    {
      id: "team-skill-ui",
      label: "技能 · UI / 可视化",
      kind: "skill",
      value: "ui_visualization",
      selectable: true,
      private: true,
    },
    {
      id: "team-availability",
      label: "时间 · 每周 5 小时",
      kind: "availability",
      value: "5_hours",
      selectable: true,
      private: true,
    },
    {
      id: "team-communication",
      label: "沟通 · 异步文档 + 每周一次会议",
      kind: "communication",
      value: "async_weekly",
      selectable: true,
      private: true,
    },
    {
      id: "team-sensitive-gender",
      label: "敏感字段 · 性别（禁止匹配）",
      kind: "sensitive",
      value: "withheld",
      selectable: false,
      private: true,
    },
    {
      id: "team-sensitive-nationality",
      label: "敏感字段 · 国籍（禁止匹配）",
      kind: "sensitive",
      value: "withheld",
      selectable: false,
      private: true,
    },
  ],
  teamNeeds: [
    {
      id: "need-lab-story",
      offeringId: "offering-sls201-2026sp",
      projectTitle: "实验数据故事板",
      roleGap: "需要一位把实验结果转成可读交互的人",
      skills: ["ui_visualization"],
      hoursPerWeek: 4,
      communication: ["async_weekly"],
      sourceIds: ["src-teacher-confirmed"],
    },
    {
      id: "need-filter-model",
      offeringId: "offering-sls201-2026sp",
      projectTitle: "滤波器 What-if",
      roleGap: "需要一位能解释信号模型假设的人",
      skills: ["signal_modeling"],
      hoursPerWeek: 6,
      communication: ["async_weekly"],
      sourceIds: ["src-official-syllabus"],
    },
  ],
  reminders: [
    {
      id: "reminder-equipment",
      offeringId: "offering-sls201-2026sp",
      type: "equipment",
      title: "设备清单尚未定稿",
      detail: "不要提前购买；等待院系正式清单。",
      dueAt: "2026-08-20T12:00:00+08:00",
      sourceId: "src-system-inference",
      required: false,
    },
    {
      id: "reminder-material",
      offeringId: "offering-sls201-2026sp",
      type: "material",
      title: "开课前复核讲义版本",
      detail: "只使用 SLS201-2026SP-v2 或之后的官方版本。",
      dueAt: "2026-08-28T18:00:00+08:00",
      sourceId: "src-official-syllabus",
      required: true,
    },
    {
      id: "reminder-attendance",
      offeringId: "offering-sls201-2026sp",
      type: "attendance",
      title: "实验出勤规则",
      detail: "缺席补做路径需提前向教师确认；本页不能批准例外。",
      dueAt: "2026-09-01T08:00:00+08:00",
      sourceId: "src-teacher-confirmed",
      required: true,
    },
    {
      id: "reminder-safety",
      offeringId: "offering-sls201-2026sp",
      type: "safety",
      title: "实验室安全说明",
      detail: "首次进入实验室前完成正式安全说明；Fixture 不授予门禁。",
      dueAt: "2026-09-03T08:00:00+08:00",
      sourceId: "src-official-syllabus",
      required: true,
    },
  ],
  audit: [
    {
      id: "coach-event-001",
      sequence: 1,
      action: "view",
      targetId: "course-profile-sls201-2026sp",
      detail:
        "loaded course and instructor-assignment Fixture as separate records",
      occurredAt: "2026-07-24T08:45:00+08:00",
      previousEventHash: null,
      eventHash: "fnv1a-coach-event-001",
    },
  ],
  invariants: {
    noTeacherRating: true,
    noPersonalityLabels: true,
    separateCourseAndTeacher: true,
    noFeedbackCarryForward: true,
    minimumFeedbackSample: 5,
    noSensitiveTeamMatching: true,
    noFabricatedAdvisorReply: true,
    severeContentHiddenFirst: true,
  },
};
