import type { OpportunityMarketFixture } from "./types";

export const OPPORTUNITY_MARKET_FIXTURE: OpportunityMarketFixture = {
  schemaVersion: "1.0",
  dataMode: "demo_fixture",
  generatedAt: "2026-07-24T08:00:00+08:00",
  lastUpdatedAt: "2026-07-24T20:40:00+08:00",
  studentId: "student-nan-fixture",
  profileVisibility: "private",
  selectedStage: "market",
  selectedOpportunityId: "opp-signal-lab",
  categoryFilter: "all",
  query: "",
  showActiveOnly: true,
  selectedProfileFieldIds: [
    "field-goal-research",
    "field-interest-signal",
    "field-course-sls201",
    "field-portfolio-signal",
  ],
  forbiddenProfileFieldIds: [
    "health",
    "family",
    "financial_account",
    "campus_access_log",
    "payment_history",
  ],
  opportunities: [
    {
      id: "opp-signal-lab",
      title: "信号系统开放研究助理",
      summary: "围绕传感与时序分析完成 6 周公开研究 Sprint。",
      provider: "示例大学 · 开放信号实验室",
      category: "research",
      packId: "pack-research-starter",
      sourceUrl: "https://opportunities.example.edu/signal-lab-2026",
      sourceVersion: "2026.07-r2",
      fetchedAt: "2026-07-24T07:20:00+08:00",
      verifiedAt: "2026-07-24T07:40:00+08:00",
      deadline: "2026-08-18T23:59:00+08:00",
      location: "混合 · 每周一次实验室",
      cost: {
        amount: 0,
        currency: "CNY",
        description: "不收申请费；通勤成本自理，可申请 Fixture 差旅权益。",
      },
      benefits: ["研究导师反馈", "可公开作品证据", "实验室时段"],
      obligations: ["每周投入 8 小时", "遵守数据与实验室安全规范"],
      risks: ["时段可能与课程冲突", "最终成果不承诺发表"],
      eligibilityRuleIds: [
        "rule-signal-course",
        "rule-signal-interest",
        "rule-signal-time",
        "rule-signal-language",
      ],
      eligibilitySummary: "课程基础、研究兴趣、每周 8 小时与英文摘要阅读",
      status: "active",
      correctionRoute: "opportunity-office@example.edu · Fixture 纠错入口",
      externalApplicationUrl:
        "https://apply.example.edu/opportunities/signal-lab-2026",
      paidRankingFactor: 0,
      randomAllocation: false,
      auctionEnabled: false,
      createdAt: "2026-07-20T09:00:00+08:00",
      updatedAt: "2026-07-24T07:40:00+08:00",
    },
    {
      id: "opp-adventurex",
      title: "AdventureX 2026 · 大学生活 Reverse",
      summary:
        "University2K26 当前参赛事件彩蛋：用 Reverse 把被动教务翻转为学生可解释、可回放的大学生涯。",
      provider: "AdventureX（官方信息待现场复核）",
      searchAliases: [
        "AdventureX",
        "Adventure X",
        "Reverse",
        "逆转课堂",
        "大学2K26",
        "University2K26",
      ],
      category: "competition",
      packId: "pack-build-and-show",
      sourceUrl:
        "https://adventurex.feishu.cn/docx/FOhLdr0Y3okbATxWvBQcoFx0nEd",
      sourceVersion: "2026 终极指南链接 · 正文待现场复核",
      fetchedAt: "2026-07-23T20:00:00+08:00",
      verifiedAt: null,
      deadline: null,
      location: "AdventureX 2026 现场 · 以终极指南为准",
      cost: {
        amount: 0,
        currency: "CNY",
        description: "当前 Demo 不声明费用；报名、交通、餐食与硬件规则以官方指南为准。",
      },
      benefits: ["真实参赛 Demo 语境", "现场反馈", "Reverse 主命题叙事"],
      obligations: ["现场重新核对提交要求", "公开说明素材、数据与 AI 使用来源"],
      risks: [
        "官方 Playbook 公开不等于赛事 Logo、商标或视觉资产获得再使用许可",
        "提交时间、队伍与硬件规则仍需用终极指南逐项确认",
      ],
      eligibilityRuleIds: [
        "rule-adventurex-team",
        "rule-adventurex-time",
        "rule-adventurex-submission",
      ],
      eligibilitySummary:
        "参赛资格、时间和提交要求尚未从官方终极指南逐条核对",
      status: "active",
      correctionRoute: "AdventureX 官方渠道 · 提交前人工复核",
      externalApplicationUrl:
        "https://adventurex.feishu.cn/docx/FOhLdr0Y3okbATxWvBQcoFx0nEd",
      paidRankingFactor: 0,
      randomAllocation: false,
      auctionEnabled: false,
      createdAt: "2026-07-19T08:00:00+08:00",
      updatedAt: "2026-07-24T06:30:00+08:00",
      rightsGate: {
        participantStatus: "demo_participant_fixture",
        permissionStatus: "pending_official_confirmation",
        allowedScope: [],
        requiredActions: [
          "找到主办方明确的视觉素材使用许可或取得书面确认",
          "记录可用素材、范围、署名、期限与撤回条件",
          "不得暗示 AdventureX 对 University2K26 的官方背书",
        ],
        noEndorsement: true,
        evidenceUrl:
          "https://github.com/AdventureX-RGE/Playbook",
        lastReviewedAt: "2026-07-24T20:40:00+08:00",
      },
    },
    {
      id: "opp-hci-workshop",
      title: "包容性 HCI 设计工作坊",
      summary: "两日可访问性与多输入原型工作坊，含可用性测试门诊。",
      provider: "示例人机交互协会",
      category: "workshop",
      packId: "pack-build-and-show",
      sourceUrl: "https://opportunities.example.edu/hci-accessibility-workshop",
      sourceVersion: "2026.06-r4",
      fetchedAt: "2026-07-22T09:30:00+08:00",
      verifiedAt: "2026-07-23T10:00:00+08:00",
      deadline: "2026-08-10T17:00:00+08:00",
      location: "线上 + 无障碍字幕",
      cost: {
        amount: 120,
        currency: "CNY",
        description: "学生票 120 元；可使用已获 Workshop Entitlement，不能购买资格。",
      },
      benefits: ["两日工作坊", "可访问性审查模板", "导师门诊"],
      obligations: ["完成课前 30 分钟材料", "遵守共同体行为准则"],
      risks: ["名额以官方确认邮件为准"],
      eligibilityRuleIds: [
        "rule-hci-interest",
        "rule-hci-time",
      ],
      eligibilitySummary: "HCI 兴趣与两日可用时间",
      status: "active",
      correctionRoute: "hci-workshop@example.edu · Fixture 纠错入口",
      externalApplicationUrl:
        "https://apply.example.edu/workshops/hci-accessibility",
      paidRankingFactor: 0,
      randomAllocation: false,
      auctionEnabled: false,
      createdAt: "2026-07-01T09:00:00+08:00",
      updatedAt: "2026-07-23T10:00:00+08:00",
    },
    {
      id: "opp-open-source-intern",
      title: "教育开源工程实习",
      summary: "参与跨平台学习工具的合同、测试与可访问性实现。",
      provider: "示例开放软件基金会",
      category: "internship",
      packId: "pack-build-and-show",
      sourceUrl: "https://opportunities.example.edu/open-education-intern",
      sourceVersion: "2026-summer-v3",
      fetchedAt: "2026-07-21T13:00:00+08:00",
      verifiedAt: "2026-07-24T07:00:00+08:00",
      deadline: "2026-08-25T23:59:00+08:00",
      location: "远程",
      cost: {
        amount: 0,
        currency: "CNY",
        description: "无申请费；带薪标准以外部正式岗位页为准。",
      },
      benefits: ["代码审查", "开源协作", "公开贡献记录"],
      obligations: ["每周至少 12 小时", "遵守开源行为准则"],
      risks: ["Fixture 不承诺录取或薪酬"],
      eligibilityRuleIds: [
        "rule-intern-portfolio",
        "rule-intern-language",
        "rule-intern-time",
      ],
      eligibilitySummary: "公开作品、英文协作与每周 12 小时",
      status: "active",
      correctionRoute: "internships@example.edu · Fixture 纠错入口",
      externalApplicationUrl:
        "https://apply.example.edu/internships/open-education",
      paidRankingFactor: 0,
      randomAllocation: false,
      auctionEnabled: false,
      createdAt: "2026-07-10T09:00:00+08:00",
      updatedAt: "2026-07-24T07:00:00+08:00",
    },
    {
      id: "opp-student-conference",
      title: "本科生研究海报论坛",
      summary: "跨学科海报展示与公开同行反馈，不要求已有论文发表。",
      provider: "示例本科生研究办公室",
      category: "conference",
      packId: "pack-research-starter",
      sourceUrl: "https://opportunities.example.edu/student-poster-forum",
      sourceVersion: "2026-call-v2",
      fetchedAt: "2026-07-20T14:00:00+08:00",
      verifiedAt: "2026-07-23T15:30:00+08:00",
      deadline: "2026-09-05T23:59:00+08:00",
      location: "线下 · 示例图书馆",
      cost: {
        amount: 0,
        currency: "CNY",
        description: "学生展示免费；差旅不适用。",
      },
      benefits: ["海报反馈", "跨学科交流", "公开展示证明"],
      obligations: ["提交 300 字摘要", "本人确认素材公开权利"],
      risks: ["公开展示前需完成教师或导师审核"],
      eligibilityRuleIds: [
        "rule-poster-portfolio",
        "rule-poster-review",
      ],
      eligibilitySummary: "摘要作品与公开权利审核",
      status: "active",
      correctionRoute: "research-office@example.edu · Fixture 纠错入口",
      externalApplicationUrl:
        "https://apply.example.edu/conferences/student-poster",
      paidRankingFactor: 0,
      randomAllocation: false,
      auctionEnabled: false,
      createdAt: "2026-07-05T09:00:00+08:00",
      updatedAt: "2026-07-23T15:30:00+08:00",
    },
    {
      id: "opp-maker-scholarship",
      title: "开放制造微型资助",
      summary: "支持学生原型的材料费与开放文档成本，按规则人工审核。",
      provider: "示例工程教育基金",
      category: "scholarship",
      packId: "pack-build-and-show",
      sourceUrl: "https://opportunities.example.edu/maker-microgrant",
      sourceVersion: "2026-round-3",
      fetchedAt: "2026-07-19T11:00:00+08:00",
      verifiedAt: "2026-07-22T12:00:00+08:00",
      deadline: "2026-08-30T20:00:00+08:00",
      location: "校内",
      cost: {
        amount: 0,
        currency: "CNY",
        description: "不收申请费；资助不可用于购买课程资格或排名。",
      },
      benefits: ["最高 2,000 元材料预算", "制造顾问门诊"],
      obligations: ["提交预算", "公开非敏感成果摘要"],
      risks: ["资助以正式书面批准为准"],
      eligibilityRuleIds: [
        "rule-grant-portfolio",
        "rule-grant-budget",
      ],
      eligibilitySummary: "原型证据与透明预算",
      status: "active",
      correctionRoute: "maker-fund@example.edu · Fixture 纠错入口",
      externalApplicationUrl:
        "https://apply.example.edu/grants/maker-microgrant",
      paidRankingFactor: 0,
      randomAllocation: false,
      auctionEnabled: false,
      createdAt: "2026-07-02T09:00:00+08:00",
      updatedAt: "2026-07-22T12:00:00+08:00",
    },
    {
      id: "opp-campus-data-project",
      title: "校园服务数据共创项目",
      summary: "在匿名聚合边界内研究排队与服务可达性。",
      provider: "示例校园服务办公室",
      category: "campus_project",
      packId: "pack-research-starter",
      sourceUrl: "https://opportunities.example.edu/campus-data-cocreate",
      sourceVersion: "2026.07-r1",
      fetchedAt: "2026-07-18T16:00:00+08:00",
      verifiedAt: "2026-07-21T09:00:00+08:00",
      deadline: "2026-08-15T18:00:00+08:00",
      location: "校内 + 远程",
      cost: {
        amount: 0,
        currency: "CNY",
        description: "无费用；不要求提交个人门禁、支付或健康数据。",
      },
      benefits: ["服务设计经验", "公开方法报告"],
      obligations: ["完成数据伦理培训", "每周 5 小时"],
      risks: ["真实数据访问须另行批准"],
      eligibilityRuleIds: [
        "rule-campus-interest",
        "rule-campus-time",
        "rule-campus-ethics",
      ],
      eligibilitySummary: "服务设计兴趣、每周 5 小时与伦理培训",
      status: "active",
      correctionRoute: "campus-data@example.edu · Fixture 纠错入口",
      externalApplicationUrl:
        "https://apply.example.edu/projects/campus-data",
      paidRankingFactor: 0,
      randomAllocation: false,
      auctionEnabled: false,
      createdAt: "2026-07-08T09:00:00+08:00",
      updatedAt: "2026-07-21T09:00:00+08:00",
    },
    {
      id: "opp-journal-clinic",
      title: "学生期刊开放投稿门诊",
      summary: "已结束的投稿准备门诊，保留为过期规则演示样例。",
      provider: "示例学生学术期刊",
      category: "journal",
      packId: "pack-research-starter",
      sourceUrl: "https://opportunities.example.edu/journal-clinic-archive",
      sourceVersion: "2026-spring-closed",
      fetchedAt: "2026-06-20T10:00:00+08:00",
      verifiedAt: "2026-07-01T10:00:00+08:00",
      deadline: "2026-07-10T18:00:00+08:00",
      location: "线上",
      cost: {
        amount: 0,
        currency: "CNY",
        description: "已结束；不得以制造紧迫感的方式继续推广。",
      },
      benefits: ["投稿结构反馈"],
      obligations: ["准备一页摘要"],
      risks: ["机会已过期，不接受申请"],
      eligibilityRuleIds: ["rule-journal-abstract"],
      eligibilitySummary: "一页摘要",
      status: "expired",
      correctionRoute: "journal@example.edu · Fixture 归档纠错入口",
      externalApplicationUrl:
        "https://apply.example.edu/archive/journal-clinic",
      paidRankingFactor: 0,
      randomAllocation: false,
      auctionEnabled: false,
      createdAt: "2026-05-01T09:00:00+08:00",
      updatedAt: "2026-07-11T08:00:00+08:00",
    },
  ],
  packs: [
    {
      id: "pack-research-starter",
      title: "研究起步 · 透明机会包",
      description: "完整列出 4 项研究与发表准备机会；没有抽取、稀有度或付费解锁。",
      opportunityIds: [
        "opp-signal-lab",
        "opp-student-conference",
        "opp-campus-data-project",
        "opp-journal-clinic",
      ],
      transparent: true,
      paidRandom: false,
    },
    {
      id: "pack-build-and-show",
      title: "建造与展示 · 透明机会包",
      description: "完整列出 4 项原型、实习、工作坊与资助机会；排序不受付费影响。",
      opportunityIds: [
        "opp-adventurex",
        "opp-hci-workshop",
        "opp-open-source-intern",
        "opp-maker-scholarship",
      ],
      transparent: true,
      paidRandom: false,
    },
  ],
  rules: [
    {
      id: "rule-signal-course",
      opportunityId: "opp-signal-lab",
      fieldId: "field-course-sls201",
      operator: "eq",
      expectedValue: "completed",
      description: "已完成或正在完成信号与线性系统基础课程",
      sourceRef: "https://opportunities.example.edu/signal-lab-2026#eligibility-course",
      required: true,
    },
    {
      id: "rule-signal-interest",
      opportunityId: "opp-signal-lab",
      fieldId: "field-interest-signal",
      operator: "contains",
      expectedValue: "信号",
      description: "能说明对信号、传感或时序分析的兴趣",
      sourceRef: "https://opportunities.example.edu/signal-lab-2026#eligibility-interest",
      required: true,
    },
    {
      id: "rule-signal-time",
      opportunityId: "opp-signal-lab",
      fieldId: "field-availability-hours",
      operator: "gte",
      expectedValue: 8,
      description: "连续 6 周每周可投入至少 8 小时",
      sourceRef: "https://opportunities.example.edu/signal-lab-2026#eligibility-time",
      required: true,
    },
    {
      id: "rule-signal-language",
      opportunityId: "opp-signal-lab",
      fieldId: "field-language-english",
      operator: "eq",
      expectedValue: "reading_ready",
      description: "可阅读英文技术摘要；不要求标准化考试分数",
      sourceRef: "https://opportunities.example.edu/signal-lab-2026#eligibility-language",
      required: false,
    },
    {
      id: "rule-adventurex-team",
      opportunityId: "opp-adventurex",
      fieldId: "field-adventurex-official-eligibility",
      operator: "eq",
      expectedValue: "official_confirmed",
      description: "队伍人数与成员资格：待按官方终极指南核对",
      sourceRef:
        "https://adventurex.feishu.cn/docx/FOhLdr0Y3okbATxWvBQcoFx0nEd",
      required: true,
    },
    {
      id: "rule-adventurex-time",
      opportunityId: "opp-adventurex",
      fieldId: "field-adventurex-official-eligibility",
      operator: "eq",
      expectedValue: "official_confirmed",
      description: "开放、截止与现场时间：待按官方终极指南核对",
      sourceRef:
        "https://adventurex.feishu.cn/docx/FOhLdr0Y3okbATxWvBQcoFx0nEd",
      required: true,
    },
    {
      id: "rule-adventurex-submission",
      opportunityId: "opp-adventurex",
      fieldId: "field-adventurex-official-eligibility",
      operator: "eq",
      expectedValue: "official_confirmed",
      description: "提交物、仓库与素材使用要求：待按官方终极指南核对",
      sourceRef:
        "https://adventurex.feishu.cn/docx/FOhLdr0Y3okbATxWvBQcoFx0nEd",
      required: true,
    },
    {
      id: "rule-hci-interest",
      opportunityId: "opp-hci-workshop",
      fieldId: "field-interest-hci",
      operator: "contains",
      expectedValue: "HCI",
      description: "对 HCI 或可访问性有明确兴趣",
      sourceRef: "https://opportunities.example.edu/hci-accessibility-workshop#interest",
      required: false,
    },
    {
      id: "rule-hci-time",
      opportunityId: "opp-hci-workshop",
      fieldId: "field-availability-hours",
      operator: "gte",
      expectedValue: 6,
      description: "两日合计可投入至少 6 小时",
      sourceRef: "https://opportunities.example.edu/hci-accessibility-workshop#time",
      required: true,
    },
    {
      id: "rule-intern-portfolio",
      opportunityId: "opp-open-source-intern",
      fieldId: "field-portfolio-signal",
      operator: "eq",
      expectedValue: "available",
      description: "有可公开审阅的工程作品",
      sourceRef: "https://opportunities.example.edu/open-education-intern#portfolio",
      required: true,
    },
    {
      id: "rule-intern-language",
      opportunityId: "opp-open-source-intern",
      fieldId: "field-language-english",
      operator: "eq",
      expectedValue: "collaboration_ready",
      description: "可进行英文异步协作",
      sourceRef: "https://opportunities.example.edu/open-education-intern#language",
      required: true,
    },
    {
      id: "rule-intern-time",
      opportunityId: "opp-open-source-intern",
      fieldId: "field-availability-hours",
      operator: "gte",
      expectedValue: 12,
      description: "每周可投入至少 12 小时",
      sourceRef: "https://opportunities.example.edu/open-education-intern#time",
      required: true,
    },
    {
      id: "rule-poster-portfolio",
      opportunityId: "opp-student-conference",
      fieldId: "field-portfolio-signal",
      operator: "eq",
      expectedValue: "available",
      description: "有可整理为 300 字摘要的项目证据",
      sourceRef: "https://opportunities.example.edu/student-poster-forum#abstract",
      required: true,
    },
    {
      id: "rule-poster-review",
      opportunityId: "opp-student-conference",
      fieldId: "field-review-rights",
      operator: "eq",
      expectedValue: "approved_fixture",
      description: "公开素材已经完成人工审核与权利确认",
      sourceRef: "https://opportunities.example.edu/student-poster-forum#rights",
      required: true,
    },
    {
      id: "rule-grant-portfolio",
      opportunityId: "opp-maker-scholarship",
      fieldId: "field-portfolio-signal",
      operator: "eq",
      expectedValue: "available",
      description: "有原型与材料需求说明",
      sourceRef: "https://opportunities.example.edu/maker-microgrant#prototype",
      required: true,
    },
    {
      id: "rule-grant-budget",
      opportunityId: "opp-maker-scholarship",
      fieldId: "field-budget-draft",
      operator: "eq",
      expectedValue: "ready",
      description: "提交透明材料预算；不读取家庭财务账户",
      sourceRef: "https://opportunities.example.edu/maker-microgrant#budget",
      required: true,
    },
    {
      id: "rule-campus-interest",
      opportunityId: "opp-campus-data-project",
      fieldId: "field-interest-hci",
      operator: "contains",
      expectedValue: "服务设计",
      description: "对校园服务设计或可达性研究有兴趣",
      sourceRef: "https://opportunities.example.edu/campus-data-cocreate#interest",
      required: false,
    },
    {
      id: "rule-campus-time",
      opportunityId: "opp-campus-data-project",
      fieldId: "field-availability-hours",
      operator: "gte",
      expectedValue: 5,
      description: "每周可投入至少 5 小时",
      sourceRef: "https://opportunities.example.edu/campus-data-cocreate#time",
      required: true,
    },
    {
      id: "rule-campus-ethics",
      opportunityId: "opp-campus-data-project",
      fieldId: "field-ethics-training",
      operator: "eq",
      expectedValue: "complete",
      description: "完成数据伦理培训",
      sourceRef: "https://opportunities.example.edu/campus-data-cocreate#ethics",
      required: true,
    },
    {
      id: "rule-journal-abstract",
      opportunityId: "opp-journal-clinic",
      fieldId: "field-portfolio-signal",
      operator: "eq",
      expectedValue: "available",
      description: "准备一页摘要",
      sourceRef: "https://opportunities.example.edu/journal-clinic-archive#abstract",
      required: true,
    },
  ],
  profileFields: [
    {
      id: "field-goal-research",
      label: "目标 · 尝试一段可回滚研究经历",
      kind: "goal",
      value: "research_exploration",
      valueLabel: "研究体验，不承诺发表",
      authority: "self_declared",
      sourceId: null,
      verifiedAt: null,
      expiresAt: null,
      private: true,
      selectable: true,
    },
    {
      id: "field-interest-signal",
      label: "兴趣 · 信号 / 传感 / 时序分析",
      kind: "interest",
      value: ["信号", "传感", "时序分析"],
      valueLabel: "本人声明",
      authority: "self_declared",
      sourceId: null,
      verifiedAt: null,
      expiresAt: null,
      private: true,
      selectable: true,
    },
    {
      id: "field-interest-hci",
      label: "兴趣 · HCI / 服务设计 / 可访问性",
      kind: "interest",
      value: ["HCI", "服务设计", "可访问性"],
      valueLabel: "本人声明",
      authority: "self_declared",
      sourceId: null,
      verifiedAt: null,
      expiresAt: null,
      private: true,
      selectable: true,
    },
    {
      id: "field-availability-hours",
      label: "可用时间 · 每周 6 小时",
      kind: "availability",
      value: 6,
      valueLabel: "本人声明 · 本周",
      authority: "self_declared",
      sourceId: "F-006:ev-self-capacity-001",
      verifiedAt: "2026-07-24T07:30:00+08:00",
      expiresAt: "2026-07-31T23:59:00+08:00",
      private: true,
      selectable: true,
    },
    {
      id: "field-course-sls201",
      label: "课程 · 信号与线性系统",
      kind: "verified_evidence",
      value: "completed",
      valueLabel: "Fixture 镜像 · 已完成",
      authority: "verified_fixture",
      sourceId: "F-003:nr-course-sls201",
      verifiedAt: "2026-07-23T16:00:00+08:00",
      expiresAt: "2026-08-23T16:00:00+08:00",
      private: true,
      selectable: true,
    },
    {
      id: "field-portfolio-signal",
      label: "作品 · University2K26 信号课程 Demo",
      kind: "verified_evidence",
      value: "available",
      valueLabel: "教师审核 Fixture · 可选导出",
      authority: "verified_fixture",
      sourceId: "F-001:publication-sls-001",
      verifiedAt: "2026-07-24T06:00:00+08:00",
      expiresAt: null,
      private: true,
      selectable: true,
    },
    {
      id: "field-language-english",
      label: "语言 · 英文技术阅读",
      kind: "self_declared",
      value: "reading_ready",
      valueLabel: "本人声明 · 未验证异步协作",
      authority: "self_declared",
      sourceId: null,
      verifiedAt: null,
      expiresAt: null,
      private: true,
      selectable: true,
    },
    {
      id: "field-adventurex-official-eligibility",
      label: "AdventureX 官方资格规则 · 待人工核对",
      kind: "verified_evidence",
      value: "unknown",
      valueLabel: "终极指南正文尚未形成可追溯核对回执",
      authority: "demo_fixture",
      sourceId: "adventurex-final-guide:pending-review",
      verifiedAt: null,
      expiresAt: null,
      private: true,
      selectable: true,
    },
    {
      id: "field-team-size",
      label: "团队 · 当前 1 位已确认",
      kind: "self_declared",
      value: 1,
      valueLabel: "本人声明 · 不抓取通讯录",
      authority: "self_declared",
      sourceId: null,
      verifiedAt: null,
      expiresAt: "2026-07-28T23:59:00+08:00",
      private: true,
      selectable: true,
    },
    {
      id: "field-review-rights",
      label: "公开权利 · 仅 Fixture 教师审核",
      kind: "verified_evidence",
      value: "approved_fixture",
      valueLabel: "不等于真实公开许可",
      authority: "verified_fixture",
      sourceId: "F-001:review-revision-3",
      verifiedAt: "2026-07-24T06:00:00+08:00",
      expiresAt: null,
      private: true,
      selectable: true,
    },
    {
      id: "field-budget-draft",
      label: "材料预算 · 尚未准备",
      kind: "self_declared",
      value: "missing",
      valueLabel: "不读取家庭或银行卡信息",
      authority: "self_declared",
      sourceId: null,
      verifiedAt: null,
      expiresAt: null,
      private: true,
      selectable: true,
    },
    {
      id: "field-ethics-training",
      label: "数据伦理培训 · 未知",
      kind: "verified_evidence",
      value: "unknown",
      valueLabel: "Academic Mirror 无记录",
      authority: "demo_fixture",
      sourceId: "F-003:gap-ethics-training",
      verifiedAt: "2026-07-23T16:00:00+08:00",
      expiresAt: "2026-08-23T16:00:00+08:00",
      private: true,
      selectable: true,
    },
  ],
  eligibilityChecks: [],
  matchResults: [],
  savedOpportunities: [],
  disclosureGrants: [],
  applicationMirrors: [],
  entitlements: [
    {
      id: "ent-workshop-2026",
      title: "HCI Workshop 学生权益",
      provider: "示例学生发展办公室",
      scope: "抵扣一次已确认工作坊学生票，不影响资格或排序",
      conditions: ["本人主动使用", "仅限 opp-hci-workshop", "以提供方确认邮件为准"],
      validFrom: "2026-07-24T00:00:00+08:00",
      expiresAt: "2026-08-10T17:00:00+08:00",
      status: "available",
      sourceId: "fixture:entitlement-workshop-2026",
      purchasableQualification: false,
    },
    {
      id: "ent-lab-slot",
      title: "开放实验室 2 小时时段",
      provider: "示例工程实验室",
      scope: "一次设备预约入口；不代表已经预约或获准进入",
      conditions: ["完成安全培训", "在正式预约系统确认"],
      validFrom: "2026-07-24T00:00:00+08:00",
      expiresAt: "2026-08-31T23:59:00+08:00",
      status: "available",
      sourceId: "fixture:entitlement-lab-slot",
      purchasableQualification: false,
    },
    {
      id: "ent-travel",
      title: "校内展示差旅候选",
      provider: "示例本科生研究办公室",
      scope: "最高 300 元报销候选；须另走政策审批",
      conditions: ["仅限已批准展示", "保留票据", "不兑换现金或资格"],
      validFrom: "2026-08-01T00:00:00+08:00",
      expiresAt: "2026-10-01T23:59:00+08:00",
      status: "available",
      sourceId: "fixture:entitlement-travel",
      purchasableQualification: false,
    },
  ],
  capacity: [
    {
      id: "time",
      label: "每周时间",
      available: 18,
      committed: 12,
      unit: "小时",
      sourceLabel: "本人声明 · 7 天有效",
      canPurchaseEligibility: false,
    },
    {
      id: "energy",
      label: "可持续精力",
      available: 5,
      committed: 3,
      unit: "档",
      sourceLabel: "本人私密选择 · 非健康指标",
      canPurchaseEligibility: false,
    },
    {
      id: "lab_slot",
      label: "实验室时段",
      available: 2,
      committed: 0,
      unit: "小时",
      sourceLabel: "Fixture 权益 · 需正式预约",
      canPurchaseEligibility: false,
    },
    {
      id: "funding",
      label: "已获资助容量",
      available: 300,
      committed: 0,
      unit: "CNY",
      sourceLabel: "Fixture 政策候选 · 非现金余额",
      canPurchaseEligibility: false,
    },
  ],
  capacityPlans: [],
  pathways: [
    {
      id: "path-major-change",
      title: "A · 转向交互技术方向",
      type: "major_change",
      inheritedCredits: "预计保留 72–78 学分；6 学分需院系确认",
      estimatedTime: "可能增加 0–1 学期",
      estimatedCost: "仅展示学费与机会成本区间；当前无正式费率",
      assumptions: ["当前课程 Fixture 可映射", "目标院系允许跨专业申请"],
      risks: ["学分映射未获批准", "容量与先修可能变化"],
      rollbackPoint: "提交正式转专业申请前可回到当前培养路径",
      approvalPath: ["学业顾问复核", "目标院系审核", "权威系统正式提交"],
      authoritative: false,
    },
    {
      id: "path-exchange",
      title: "B · 一学期交换",
      type: "exchange",
      inheritedCredits: "预估 12–16 学分；逐门课程预审",
      estimatedTime: "不延长或增加 1 学期，取决于学分确认",
      estimatedCost: "差旅、住宿、保险均为未知项",
      assumptions: ["语言材料可补齐", "目标课程仍开放"],
      risks: ["课程变更", "签证与住宿不确定"],
      rollbackPoint: "正式提名前可删除方案，不影响当前课表",
      approvalPath: ["国际处咨询", "课程预审", "提名", "外部申请"],
      authoritative: false,
    },
    {
      id: "path-accelerated",
      title: "C · 提前修读研究生课程",
      type: "accelerated_study",
      inheritedCredits: "最多 6 学分候选；政策需逐条核验",
      estimatedTime: "可能缩短后续培养，但增加当前负荷",
      estimatedCost: "费用与学分双计规则未知",
      assumptions: ["先修满足", "课程有容量", "学院批准"],
      risks: ["高负荷", "课程不计入目标学位"],
      rollbackPoint: "选课交易确认前保持 What-if",
      approvalPath: ["导师建议", "研究生院规则核验", "院系批准", "正式选课"],
      authoritative: false,
    },
  ],
  selectedPathwayId: null,
  portfolioArtifacts: [
    {
      id: "artifact-smartcourse",
      title: "智课工坊 · 来源约束讲解对象",
      sourceModule: "F-001",
      sourceId: "publication-sls-001",
      reviewStatus: "teacher_approved_fixture",
      includesOriginalMaterial: false,
      selected: false,
    },
    {
      id: "artifact-world-exam",
      title: "World Exam · 本人来源挑战复盘",
      sourceModule: "F-005",
      sourceId: "reflection-sls-final-001",
      reviewStatus: "private_reflection",
      includesOriginalMaterial: false,
      selected: false,
    },
  ],
  reports: [],
  fairnessAudits: [],
  notifications: [
    {
      id: "notice-expired-journal",
      opportunityId: "opp-journal-clinic",
      kind: "expiry",
      message: "学生期刊开放投稿门诊已过期，已从默认发现结果移除。",
      createdAt: "2026-07-11T08:00:00+08:00",
      read: false,
    },
  ],
  audit: [
    {
      id: "opp-event-001",
      sequence: 1,
      action: "view",
      targetId: "market",
      detail: "loaded eight transparent opportunities; one expired item excluded by default",
      occurredAt: "2026-07-24T08:00:00+08:00",
      previousEventHash: null,
      eventHash: "fnv1a-opp-event-001",
    },
  ],
  offline: false,
  simplified: false,
  reducedMotion: false,
  message:
    "已载入 8 条完全透明的 Fixture 机会；默认只显示 7 条有效项，不使用抽卡、付费排序或自动投递。",
  invariants: {
    noPaidRanking: true,
    noRandomQualification: true,
    noHumanAuction: true,
    noAutoApply: true,
    noFomoCountdown: true,
    noCompositeEligibilityScore: true,
  },
};
