import type { OpportunityMarketFixture } from "./types";

export const OPPORTUNITY_MARKET_FIXTURE: OpportunityMarketFixture = {
  schemaVersion: "1.0",
  dataMode: "demo_fixture",
  generatedAt: "2026-07-24T08:00:00+08:00",
  lastUpdatedAt: "2026-07-25T18:30:00+08:00",
  studentId: "student-nan-fixture",
  profileVisibility: "private",
  selectedStage: "market",
  selectedOpportunityId: "opp-signal-lab",
  scopeFilter: "all",
  categoryFilter: "all",
  query: "",
  showActiveOnly: true,
  selectedProfileFieldIds: [
    "field-goal-research",
    "field-interest-signal",
    "field-interest-hci",
    "field-current-student",
    "field-course-sls201",
    "field-portfolio-signal",
    "field-review-rights",
    "field-team-size",
    "field-adventurex-attendance",
    "field-adventurex-submission",
  ],
  forbiddenProfileFieldIds: [
    "health",
    "family",
    "financial_account",
    "campus_access_log",
    "payment_history",
  ],
  opportunities: [
    {
      id: "opp-signal-lab",
      title: "信号系统开放研究助理",
      summary: "围绕传感与时序分析完成 6 周公开研究 Sprint。",
      provider: "示例大学 · 开放信号实验室",
      scope: "campus",
      category: "research",
      packId: "pack-research-starter",
      sourceUrl: "https://opportunities.example.edu/signal-lab-2026",
      sourceVersion: "2026.07-r2",
      fetchedAt: "2026-07-24T07:20:00+08:00",
      verifiedAt: "2026-07-24T07:40:00+08:00",
      deadline: "2026-08-18T23:59:00+08:00",
      location: "混合 · 每周一次实验室",
      cost: {
        amount: 0,
        currency: "CNY",
        description: "不收申请费；通勤成本自理，演示中提供差旅支持入口。",
      },
      benefits: ["研究导师反馈", "可公开作品证据", "实验室时段"],
      obligations: ["每周投入 8 小时", "遵守数据与实验室安全规范"],
      risks: ["时段可能与课程冲突", "最终成果不承诺发表"],
      eligibilityRuleIds: [
        "rule-signal-course",
        "rule-signal-interest",
        "rule-signal-time",
        "rule-signal-language",
      ],
      eligibilitySummary: "课程基础、研究兴趣、每周 8 小时与英文摘要阅读",
      status: "active",
      correctionRoute: "opportunity-office@example.edu · 演示纠错入口",
      externalApplicationUrl:
        "https://apply.example.edu/opportunities/signal-lab-2026",
      paidRankingFactor: 0,
      randomAllocation: false,
      auctionEnabled: false,
      createdAt: "2026-07-20T09:00:00+08:00",
      updatedAt: "2026-07-24T07:40:00+08:00",
    },
    {
      id: "opp-adventurex",
      title: "AdventureX 2026 · 大学生活 Reverse",
      summary:
        "University2K26 当前参赛事件彩蛋：用 Reverse 把被动教务翻转为学生可解释、可回放的大学生涯。",
      provider: "AdventureX · 2026 终极指南核验快照",
      scope: "external",
      searchAliases: [
        "AdventureX",
        "Adventure X",
        "Reverse",
        "逆转课堂",
        "大学2K26",
        "University2K26",
      ],
      category: "competition",
      packId: "pack-build-and-show",
      sourceUrl:
        "https://adventurex.feishu.cn/docx/FOhLdr0Y3okbATxWvBQcoFx0nEd",
      sourceVersion: "2026 终极指南 · 2026-07-23 核验快照",
      fetchedAt: "2026-07-23T20:00:00+08:00",
      verifiedAt: "2026-07-23T23:00:00+08:00",
      deadline: "2026-07-26T01:00:00+08:00",
      location: "杭州未来科技城 · Expo 07-26 09:00–15:00",
      cost: {
        amount: 0,
        currency: "CNY",
        description:
          "当前参赛条目不收申请费；交通、餐食、住宿和硬件以录取通知及现场规则为准。",
      },
      benefits: ["真实参赛 Demo 语境", "现场反馈", "Reverse 主命题叙事"],
      obligations: [
        "2–4 人组队；每人只能参加一队",
        "07-26 01:00 前完成 United Portal 提交",
        "提交 GitHub、至少 1 项轮播图（首图 16:9）和小红书链接",
      ],
      risks: [
        "官方 Playbook 公开不等于赛事 Logo、商标或视觉资产获得再使用许可",
        "官方提交窗口仅 07-25 12:00 至 07-26 01:00，共 13 小时",
        "动态字段和赛道附加要求仍须以 United Portal 当次页面为准",
      ],
      eligibilityRuleIds: [
        "rule-adventurex-team-min",
        "rule-adventurex-team-max",
        "rule-adventurex-time",
        "rule-adventurex-submission",
      ],
      eligibilitySummary:
        "队伍 2–4 人；07-25 12:00 开放、07-26 01:00 截止；需 GitHub、轮播图与小红书链接",
      status: "active",
      correctionRoute: "AdventureX 官方渠道 · 提交前人工复核",
      externalApplicationUrl:
        "https://adventurex.feishu.cn/docx/FOhLdr0Y3okbATxWvBQcoFx0nEd",
      paidRankingFactor: 0,
      randomAllocation: false,
      auctionEnabled: false,
      createdAt: "2026-07-19T08:00:00+08:00",
      updatedAt: "2026-07-25T10:30:00+08:00",
      rightsGate: {
        participantStatus: "demo_participant_fixture",
        permissionStatus: "pending_official_confirmation",
        allowedScope: [],
        requiredActions: [
          "找到主办方明确的视觉素材使用许可或取得书面确认",
          "记录可用素材、范围、署名、期限与撤回条件",
          "不得暗示 AdventureX 对 University2K26 的官方背书",
        ],
        noEndorsement: true,
        evidenceUrl:
          "https://github.com/AdventureX-RGE/Playbook",
        lastReviewedAt: "2026-07-24T20:40:00+08:00",
      },
    },
    {
      id: "opp-hci-workshop",
      title: "包容性 HCI 设计工作坊",
      summary: "两日可访问性与多输入原型工作坊，含可用性测试门诊。",
      provider: "示例人机交互协会",
      scope: "external",
      category: "workshop",
      packId: "pack-build-and-show",
      sourceUrl: "https://opportunities.example.edu/hci-accessibility-workshop",
      sourceVersion: "2026.06-r4",
      fetchedAt: "2026-07-22T09:30:00+08:00",
      verifiedAt: "2026-07-23T10:00:00+08:00",
      deadline: "2026-08-10T17:00:00+08:00",
      location: "线上 + 无障碍字幕",
      cost: {
        amount: 120,
        currency: "CNY",
        description: "学生票 120 元；可使用已获 Workshop Entitlement，不能购买资格。",
      },
      benefits: ["两日工作坊", "可访问性审查模板", "导师门诊"],
      obligations: ["完成课前 30 分钟材料", "遵守共同体行为准则"],
      risks: ["名额以官方确认邮件为准"],
      eligibilityRuleIds: [
        "rule-hci-interest",
        "rule-hci-time",
      ],
      eligibilitySummary: "HCI 兴趣与两日可用时间",
      status: "active",
      correctionRoute: "hci-workshop@example.edu · 演示纠错入口",
      externalApplicationUrl:
        "https://apply.example.edu/workshops/hci-accessibility",
      paidRankingFactor: 0,
      randomAllocation: false,
      auctionEnabled: false,
      createdAt: "2026-07-01T09:00:00+08:00",
      updatedAt: "2026-07-23T10:00:00+08:00",
    },
    {
      id: "opp-open-source-intern",
      title: "教育开源工程实习",
      summary: "参与跨平台学习工具的合同、测试与可访问性实现。",
      provider: "示例开放软件基金会",
      scope: "external",
      category: "internship",
      packId: "pack-build-and-show",
      sourceUrl: "https://opportunities.example.edu/open-education-intern",
      sourceVersion: "2026-summer-v3",
      fetchedAt: "2026-07-21T13:00:00+08:00",
      verifiedAt: "2026-07-24T07:00:00+08:00",
      deadline: "2026-08-25T23:59:00+08:00",
      location: "远程",
      cost: {
        amount: 0,
        currency: "CNY",
        description: "无申请费；带薪标准以外部正式岗位页为准。",
      },
      benefits: ["代码审查", "开源协作", "公开贡献记录"],
      obligations: ["每周至少 12 小时", "遵守开源行为准则"],
      risks: ["演示信息不承诺录取或薪酬"],
      eligibilityRuleIds: [
        "rule-intern-portfolio",
        "rule-intern-language",
        "rule-intern-time",
      ],
      eligibilitySummary: "公开作品、英文协作与每周 12 小时",
      status: "active",
      correctionRoute: "internships@example.edu · 演示纠错入口",
      externalApplicationUrl:
        "https://apply.example.edu/internships/open-education",
      paidRankingFactor: 0,
      randomAllocation: false,
      auctionEnabled: false,
      createdAt: "2026-07-10T09:00:00+08:00",
      updatedAt: "2026-07-24T07:00:00+08:00",
    },
    {
      id: "opp-maker-scholarship",
      title: "开放制造微型资助",
      summary: "支持学生原型的材料费与开放文档成本，按规则人工审核。",
      provider: "示例大学 · 工程教育基金",
      scope: "campus",
      category: "scholarship",
      packId: "pack-build-and-show",
      sourceUrl: "https://opportunities.example.edu/maker-microgrant",
      sourceVersion: "2026-round-3",
      fetchedAt: "2026-07-19T11:00:00+08:00",
      verifiedAt: "2026-07-22T12:00:00+08:00",
      deadline: "2026-08-30T20:00:00+08:00",
      location: "校内",
      cost: {
        amount: 0,
        currency: "CNY",
        description: "不收申请费；资助不可用于购买课程资格或排名。",
      },
      benefits: ["最高 2,000 元材料预算", "制造顾问门诊"],
      obligations: ["提交预算", "公开非敏感成果摘要"],
      risks: ["资助以正式书面批准为准"],
      eligibilityRuleIds: [
        "rule-grant-portfolio",
        "rule-grant-budget",
      ],
      eligibilitySummary: "原型证据与透明预算",
      status: "active",
      correctionRoute: "maker-fund@example.edu · 演示纠错入口",
      externalApplicationUrl:
        "https://apply.example.edu/grants/maker-microgrant",
      paidRankingFactor: 0,
      randomAllocation: false,
      auctionEnabled: false,
      createdAt: "2026-07-02T09:00:00+08:00",
      updatedAt: "2026-07-22T12:00:00+08:00",
    },
    {
      id: "opp-campus-data-project",
      title: "校园服务数据共创项目",
      summary: "在匿名聚合边界内研究排队与服务可达性。",
      provider: "示例校园服务办公室",
      scope: "campus",
      category: "campus_project",
      packId: "pack-research-starter",
      sourceUrl: "https://opportunities.example.edu/campus-data-cocreate",
      sourceVersion: "2026.07-r1",
      fetchedAt: "2026-07-18T16:00:00+08:00",
      verifiedAt: "2026-07-21T09:00:00+08:00",
      deadline: "2026-08-15T18:00:00+08:00",
      location: "校内 + 远程",
      cost: {
        amount: 0,
        currency: "CNY",
        description: "无费用；不要求提交个人门禁、支付或健康数据。",
      },
      benefits: ["服务设计经验", "公开方法报告"],
      obligations: ["完成数据伦理培训", "每周 5 小时"],
      risks: ["真实数据访问须另行批准"],
      eligibilityRuleIds: [
        "rule-campus-interest",
        "rule-campus-time",
        "rule-campus-ethics",
      ],
      eligibilitySummary: "服务设计兴趣、每周 5 小时与伦理培训",
      status: "active",
      correctionRoute: "campus-data@example.edu · 演示纠错入口",
      externalApplicationUrl:
        "https://apply.example.edu/projects/campus-data",
      paidRankingFactor: 0,
      randomAllocation: false,
      auctionEnabled: false,
      createdAt: "2026-07-08T09:00:00+08:00",
      updatedAt: "2026-07-21T09:00:00+08:00",
    },
    {
      id: "opp-chi-2027-src",
      title: "ACM CHI 2027 · Student Research Competition",
      summary:
        "面向在校本科生与研究生的学生研究竞赛；University2K26 可从人因、学习体验与可访问性研究切入。",
      provider: "ACM SIGCHI · 官方征稿页",
      scope: "external",
      searchAliases: ["CHI 2027", "SRC", "HCI", "学生研究竞赛", "人机交互"],
      category: "conference",
      packId: "pack-research-starter",
      sourceUrl:
        "https://chi2027.acm.org/authors/student-research-competition/",
      sourceVersion: "CHI 2027 SRC · 2026-07-25 核验",
      fetchedAt: "2026-07-25T17:20:00+08:00",
      verifiedAt: "2026-07-25T17:20:00+08:00",
      deadline: "2027-01-21T23:59:00-12:00",
      location: "Pittsburgh · 录取后须线下参赛",
      cost: {
        amount: null,
        currency: null,
        description:
          "Extended Abstract 不收开放获取 APC；注册、会员与差旅成本须在录取后按官方页面另行核验。",
      },
      benefits: ["学生研究反馈", "海报展示", "ACM SRC 竞赛通道"],
      obligations: [
        "初次提交截止时须为在校学生并提供证明",
        "提交不超过 5 页的研究材料并遵守可访问性要求",
        "录取后展示者须持有效 ACM 学生会员并线下注册参赛",
      ],
      risks: [
        "导师不可作为 SRC 共同作者；研究生项目须单作者",
        "涉及人的研究须满足所在机构伦理审查要求",
        "公开素材、隐私与 AI 使用政策需逐项人工复核",
      ],
      eligibilityRuleIds: [
        "rule-chi-src-student",
        "rule-chi-src-portfolio",
        "rule-chi-src-interest",
        "rule-chi-src-rights",
      ],
      eligibilitySummary:
        "在校身份、可整理为学生研究的证据、HCI 相关性与公开权利；作者结构和伦理要求需人工核验",
      status: "active",
      correctionRoute: "CHI 2027 SRC 官方 Contact Us",
      externalApplicationUrl:
        "https://chi2027.acm.org/authors/student-research-competition/",
      paidRankingFactor: 0,
      randomAllocation: false,
      auctionEnabled: false,
      createdAt: "2026-07-25T17:20:00+08:00",
      updatedAt: "2026-07-25T17:20:00+08:00",
    },
    {
      id: "opp-chi-2027-demo",
      title: "ACM CHI 2027 · Interactive Demos",
      summary:
        "面向可现场体验的交互系统、装置与设计；适合把 University2K26 打磨成多输入、可访问、可解释的现场体验。",
      provider: "ACM SIGCHI · 官方征稿页",
      scope: "external",
      searchAliases: ["CHI 2027", "Interactive Demos", "HCI", "交互演示"],
      category: "conference",
      packId: "pack-build-and-show",
      sourceUrl: "https://chi2027.acm.org/authors/interactive-demos/",
      sourceVersion: "CHI 2027 Interactive Demos · 2026-07-25 核验",
      fetchedAt: "2026-07-25T17:20:00+08:00",
      verifiedAt: "2026-07-25T17:20:00+08:00",
      deadline: "2027-01-21T23:59:00-12:00",
      location: "Pittsburgh · 录取后须线下演示",
      cost: {
        amount: null,
        currency: null,
        description:
          "Extended Abstract 不收开放获取 APC；注册、差旅、设备运输与现场制作成本未知。",
      },
      benefits: ["现场交互展示", "跨学科反馈", "ACM Digital Library 展示条目"],
      obligations: [
        "提交不超过 6 页的 Proposal",
        "提供不超过 5 分钟 Walkthrough 视频与宣传静帧",
        "说明现场交互、展位平面和设备，并在录取后线下展示",
      ],
      risks: [
        "现场可行性、责任检查、空间和设备运输会影响方案",
        "涉及人的研究须满足伦理要求",
        "视频、人物与第三方素材权利由作者负责",
      ],
      eligibilityRuleIds: [
        "rule-chi-demo-portfolio",
        "rule-chi-demo-interest",
        "rule-chi-demo-rights",
      ],
      eligibilitySummary:
        "可运行原型、HCI/交互价值和可公开演示权利；现场物流与伦理要求需人工核验",
      status: "active",
      correctionRoute: "demos@chi2027.acm.org",
      externalApplicationUrl:
        "https://chi2027.acm.org/authors/interactive-demos/",
      paidRankingFactor: 0,
      randomAllocation: false,
      auctionEnabled: false,
      createdAt: "2026-07-25T17:20:00+08:00",
      updatedAt: "2026-07-25T17:20:00+08:00",
    },
    {
      id: "opp-icra-2027-paper",
      title: "IEEE ICRA 2027 · Technical Papers",
      summary:
        "机器人与自动化旗舰会议技术论文通道；可承接机器人传感、实时系统与可解释学习工作台的工程研究线。",
      provider: "IEEE Robotics and Automation Society · 官方征稿页",
      scope: "external",
      searchAliases: ["ICRA 2027", "robotics", "机器人", "automation", "IEEE"],
      category: "conference",
      packId: "pack-research-starter",
      sourceUrl:
        "https://2027.ieee-icra.org/contribute/call-for-icra-2027-papers-now-accepting-submissions/",
      sourceVersion: "ICRA 2027 Call for Papers · 2026-07-25 核验",
      fetchedAt: "2026-07-25T17:20:00+08:00",
      verifiedAt: "2026-07-25T17:20:00+08:00",
      deadline: "2026-09-15T23:59:00-08:00",
      location: "Seoul · 2027-05-24 至 05-28 · 线下",
      cost: {
        amount: null,
        currency: null,
        description:
          "投稿阶段费用与录取后的注册、差旅、开放获取选择均须以官方后续页面核验。",
      },
      benefits: ["机器人研究同行评审", "论文与视频展示", "产业与学术交流"],
      obligations: [
        "完整稿最多 8 页并使用 ICRA 双栏模板",
        "遵守双匿名审稿与 IEEE-RAS AI 使用披露政策",
        "录取后须有作者线下注册与报告",
      ],
      risks: [
        "当前原型不等于具备可投稿的原创研究贡献",
        "审稿中的机密内容不得交给 AI 系统处理",
        "视频有独立上传窗口与格式限制，需人工复核",
      ],
      eligibilityRuleIds: [
        "rule-icra-portfolio",
        "rule-icra-interest",
        "rule-icra-rights",
      ],
      eligibilitySummary:
        "机器人方向、可复现实验证据和公开权利；原创性、作者关系与双匿名合规需人工核验",
      status: "active",
      correctionRoute: "ICRA 2027 官方 Contact",
      externalApplicationUrl:
        "https://2027.ieee-icra.org/contribute/call-for-icra-2027-papers-now-accepting-submissions/",
      paidRankingFactor: 0,
      randomAllocation: false,
      auctionEnabled: false,
      createdAt: "2026-07-25T17:20:00+08:00",
      updatedAt: "2026-07-25T17:20:00+08:00",
    },
    {
      id: "opp-ua-bear-down-camp-2026",
      title: "Bear Down Camp 2026",
      summary:
        "面向新生的四日校园过渡体验，用同伴网络、校园资源和 Wildcat 传统完成大学生涯开局。",
      provider: "UArizona ASUA · 官方项目页",
      scope: "campus",
      searchAliases: [
        "Bear Down",
        "Bear Down Camp",
        "UArizona",
        "Wildcats",
        "新生营",
      ],
      category: "campus_event",
      packId: "pack-bear-down-campus",
      sourceUrl:
        "https://asuatoday.arizona.edu/what-we-do/bear-down-camp",
      sourceVersion: "Bear Down Camp 2026 · 2026-07-25 核验",
      fetchedAt: "2026-07-25T08:55:00+08:00",
      verifiedAt: "2026-07-25T08:55:00+08:00",
      deadline: "2026-08-16T10:00:00-07:00",
      location: "UArizona Tucson 校园 · 08-16 至 08-19",
      cost: {
        amount: 375,
        currency: "USD",
        description:
          "项目费 375 美元；早到住宿另计 30 美元/日。官方列有有限的全额或部分减免，但本年度减免截止已过。",
      },
      benefits: ["同伴与导师网络", "校园资源导览", "Wildcat 传统与归属感"],
      obligations: [
        "核验本人是否属于 incoming freshman / first-year 范围",
        "按官方确认完成注册、付款与住宿安排",
      ],
      risks: [
        "官方页面未给出统一注册关闭时间，名额和付款状态须人工确认",
        "活动日期使用 Arizona Time，不随夏令时切换",
      ],
      eligibilityRuleIds: ["rule-ua-bdc-first-year"],
      eligibilitySummary: "仅面向 incoming freshmen / first-year；当前档案尚未确认",
      status: "active",
      correctionRoute: "beardowncamp@arizona.edu",
      externalApplicationUrl:
        "https://asuatoday.arizona.edu/what-we-do/bear-down-camp",
      paidRankingFactor: 0,
      randomAllocation: false,
      auctionEnabled: false,
      createdAt: "2026-07-25T08:55:00+08:00",
      updatedAt: "2026-07-25T08:55:00+08:00",
    },
    {
      id: "opp-ua-wildcat-employment-research-fair",
      title: "Wildcat Student Employment & Research Fair",
      summary:
        "秋季第一周的校内就业与本科科研见面会，连接 UArizona 学生、校内岗位和 Tucson 雇主。",
      provider: "UArizona Center for Career Readiness · 官方活动页",
      scope: "campus",
      searchAliases: [
        "Wildcat",
        "Employment",
        "Research Fair",
        "Handshake",
        "UArizona",
        "校内工作",
        "本科科研",
      ],
      category: "career_event",
      packId: "pack-bear-down-campus",
      sourceUrl: "https://career.arizona.edu/channels/career-fairs/",
      sourceVersion: "Fall 2026 Career Fairs · 2026-07-25 核验",
      fetchedAt: "2026-07-25T08:55:00+08:00",
      verifiedAt: "2026-07-25T08:55:00+08:00",
      deadline: "2026-08-26T12:00:00-07:00",
      location: "Bear Down Building · 08-26 12:00–15:00 Arizona Time",
      cost: {
        amount: null,
        currency: null,
        description:
          "官方页面未列学生参加费用；是否需在 Handshake 注册须在出发前复核。",
      },
      benefits: ["校内兼职", "Tucson 本地岗位", "本科科研机会"],
      obligations: ["查看 Handshake 当次要求", "准备可选简历与岗位问题"],
      risks: ["页面同时包含雇主注册信息，学生不得误用雇主报名入口"],
      eligibilityRuleIds: ["rule-ua-current-student-fair"],
      eligibilitySummary: "面向各专业 UArizona 学生；学生报名流程需在 Handshake 复核",
      status: "active",
      correctionRoute: "career@arizona.edu",
      externalApplicationUrl:
        "https://career.arizona.edu/channels/career-fairs/",
      paidRankingFactor: 0,
      randomAllocation: false,
      auctionEnabled: false,
      createdAt: "2026-07-25T08:55:00+08:00",
      updatedAt: "2026-07-25T08:55:00+08:00",
    },
    {
      id: "opp-ua-bear-down-week-2026",
      title: "Bear Down Week 2026",
      summary:
        "秋季学期中点的校园支持周，把社群连接、期中准备与互助资源放进同一条校内赛程。",
      provider: "UArizona Student Affairs · 官方活动页",
      scope: "campus",
      searchAliases: [
        "Bear Down Week",
        "UArizona",
        "Wildcats",
        "midterms",
        "期中",
        "校园支持",
      ],
      category: "campus_event",
      packId: "pack-bear-down-campus",
      sourceUrl: "https://studentaffairs.arizona.edu/bear-down-week",
      sourceVersion: "Bear Down Week 2026 · 2026-07-25 核验",
      fetchedAt: "2026-07-25T08:55:00+08:00",
      verifiedAt: "2026-07-25T08:55:00+08:00",
      deadline: "2026-09-28T00:00:00-07:00",
      location: "UArizona 校园 · 09-28 至 10-02",
      cost: {
        amount: null,
        currency: null,
        description: "官方页面未列统一费用；各子活动规则需逐项查看。",
      },
      benefits: ["期中准备支持", "校园社群连接", "学生服务资源发现"],
      obligations: ["按子活动核验地点、容量和无障碍安排"],
      risks: ["这是活动周入口，不代表所有子活动自动开放或免费"],
      eligibilityRuleIds: ["rule-ua-current-student-week"],
      eligibilitySummary: "UArizona 校园社群活动；各子活动可能有独立条件",
      status: "active",
      correctionRoute: "UArizona Student Affairs 官方活动页",
      externalApplicationUrl:
        "https://studentaffairs.arizona.edu/bear-down-week",
      paidRankingFactor: 0,
      randomAllocation: false,
      auctionEnabled: false,
      createdAt: "2026-07-25T08:55:00+08:00",
      updatedAt: "2026-07-25T08:55:00+08:00",
    },
    {
      id: "opp-ua-bear-down-fall-festival-2026",
      title: "Bear Down Fall Festival 2026",
      summary:
        "Bear Down Week 的校园节庆节点，可作为社团、服务、同伴连接与期中减压的线下集结点。",
      provider: "UArizona Student Affairs · 官方日历入口",
      scope: "campus",
      searchAliases: [
        "Bear Down Fall Festival",
        "UArizona",
        "Wildcats",
        "festival",
        "校园节",
      ],
      category: "campus_event",
      packId: "pack-bear-down-campus",
      sourceUrl: "https://studentaffairs.arizona.edu/",
      sourceVersion: "Student Affairs Events · 2026-07-25 核验",
      fetchedAt: "2026-07-25T08:55:00+08:00",
      verifiedAt: "2026-07-25T08:55:00+08:00",
      deadline: "2026-10-02T09:00:00-07:00",
      location: "UArizona 校园 · 10-02 09:00–14:00 Arizona Time",
      cost: {
        amount: null,
        currency: null,
        description: "官方入口未列费用、报名与容量，参加前须打开详情复核。",
      },
      benefits: ["校园组织发现", "同伴连接", "期中阶段减压"],
      obligations: ["活动前复核具体地点、报名、容量与天气安排"],
      risks: ["当前官方入口只给出日期与时段，细节可能继续更新"],
      eligibilityRuleIds: ["rule-ua-current-student-festival"],
      eligibilitySummary: "UArizona 校园活动；具体入场规则等待官方详情",
      status: "active",
      correctionRoute: "UArizona Student Affairs 官方日历入口",
      externalApplicationUrl: "https://studentaffairs.arizona.edu/",
      paidRankingFactor: 0,
      randomAllocation: false,
      auctionEnabled: false,
      createdAt: "2026-07-25T08:55:00+08:00",
      updatedAt: "2026-07-25T08:55:00+08:00",
    },
    {
      id: "opp-ua-clubs-organizations",
      title: "Bear Down Life · Clubs & Organizations",
      summary:
        "UArizona 校园社团发现入口，覆盖 STEM、职业发展、运动、创意、健康与特殊兴趣组织。",
      provider: "The University of Arizona · 官方校园参与入口",
      scope: "campus",
      searchAliases: [
        "Bear Down Life",
        "clubs",
        "organizations",
        "UArizona",
        "社团",
        "学生组织",
      ],
      category: "campus_event",
      packId: "pack-bear-down-campus",
      sourceUrl:
        "https://www.arizona.edu/student-life/getting-involved?publication=20260106",
      sourceVersion: "Getting Involved · 2026-07-25 核验",
      fetchedAt: "2026-07-25T08:55:00+08:00",
      verifiedAt: "2026-07-25T08:55:00+08:00",
      deadline: null,
      location: "UArizona 校园与各组织公布地点",
      cost: {
        amount: null,
        currency: null,
        description: "入口本身免费浏览；各社团会费、试训或活动成本分别核验。",
      },
      benefits: ["500+ 组织发现入口", "跨学科社群", "领导力与项目经历"],
      obligations: ["逐个核验会费、时间、行为准则与学业要求"],
      risks: ["组织数量和活跃状态会变化，目录不等于当前招新承诺"],
      eligibilityRuleIds: ["rule-ua-current-student-clubs"],
      eligibilitySummary: "校内参与入口；各组织资格和成本独立",
      status: "active",
      correctionRoute: "UArizona Campus Life & Involvement 官方入口",
      externalApplicationUrl:
        "https://www.arizona.edu/student-life/getting-involved?publication=20260106",
      paidRankingFactor: 0,
      randomAllocation: false,
      auctionEnabled: false,
      createdAt: "2026-07-25T08:55:00+08:00",
      updatedAt: "2026-07-25T08:55:00+08:00",
    },
    {
      id: "opp-ua-bear-down-music-festival-2026",
      title: "Bear Down Music Festival 2026 · Replay",
      summary:
        "已结束的 UArizona 学生主导音乐节，保留为校内活动归档与 Replay 样例。",
      provider: "UArizona ASUA & Wildcat Events Board · 官方项目页",
      scope: "campus",
      searchAliases: [
        "Bear Down Music Festival",
        "BDMF26",
        "Wildcat Events Board",
        "UArizona",
        "音乐节",
      ],
      category: "campus_event",
      packId: "pack-bear-down-campus",
      sourceUrl:
        "https://asuatoday.arizona.edu/programs-services/bear-down-music-festival",
      sourceVersion: "BDMF 2026 · 2026-07-25 归档核验",
      fetchedAt: "2026-07-25T08:55:00+08:00",
      verifiedAt: "2026-07-25T08:55:00+08:00",
      deadline: "2026-03-27T17:00:00-07:00",
      location: "UA Mall · 03-27 17:00–22:30 Arizona Time",
      cost: {
        amount: null,
        currency: null,
        description: "活动已结束；官方页曾提供 wristband 入口，历史价格未在本快照中确认。",
      },
      benefits: ["学生策划案例", "校园社群", "音乐制作与活动运营观察"],
      obligations: ["仅作历史 Replay，不再触发报名或紧迫提醒"],
      risks: ["活动已过期，不得展示为仍可参加"],
      eligibilityRuleIds: ["rule-ua-current-student-music"],
      eligibilitySummary: "历史校内活动；仅用于 Replay",
      status: "expired",
      correctionRoute: "UArizona ASUA 官方项目页",
      externalApplicationUrl:
        "https://asuatoday.arizona.edu/programs-services/bear-down-music-festival",
      paidRankingFactor: 0,
      randomAllocation: false,
      auctionEnabled: false,
      createdAt: "2026-03-01T09:00:00-07:00",
      updatedAt: "2026-07-25T08:55:00+08:00",
    },
    {
      id: "opp-journal-clinic",
      title: "学生期刊开放投稿门诊",
      summary: "已结束的投稿准备门诊，保留为过期规则演示样例。",
      provider: "示例大学 · 学生学术期刊",
      scope: "campus",
      category: "journal",
      packId: "pack-research-starter",
      sourceUrl: "https://opportunities.example.edu/journal-clinic-archive",
      sourceVersion: "2026-spring-closed",
      fetchedAt: "2026-06-20T10:00:00+08:00",
      verifiedAt: "2026-07-01T10:00:00+08:00",
      deadline: "2026-07-10T18:00:00+08:00",
      location: "线上",
      cost: {
        amount: 0,
        currency: "CNY",
        description: "已结束；不得以制造紧迫感的方式继续推广。",
      },
      benefits: ["投稿结构反馈"],
      obligations: ["准备一页摘要"],
      risks: ["机会已过期，不接受申请"],
      eligibilityRuleIds: ["rule-journal-abstract"],
      eligibilitySummary: "一页摘要",
      status: "expired",
      correctionRoute: "journal@example.edu · 演示归档纠错入口",
      externalApplicationUrl:
        "https://apply.example.edu/archive/journal-clinic",
      paidRankingFactor: 0,
      randomAllocation: false,
      auctionEnabled: false,
      createdAt: "2026-05-01T09:00:00+08:00",
      updatedAt: "2026-07-11T08:00:00+08:00",
    },
  ],
  packs: [
    {
      id: "pack-research-starter",
      title: "研究起步 · 透明机会包",
      description: "完整列出 5 项研究与发表准备机会；没有抽取、稀有度或付费解锁。",
      opportunityIds: [
        "opp-signal-lab",
        "opp-chi-2027-src",
        "opp-icra-2027-paper",
        "opp-campus-data-project",
        "opp-journal-clinic",
      ],
      transparent: true,
      paidRandom: false,
    },
    {
      id: "pack-build-and-show",
      title: "建造与展示 · 透明机会包",
      description: "完整列出 5 项原型、实习、工作坊与资助机会；排序不受付费影响。",
      opportunityIds: [
        "opp-adventurex",
        "opp-chi-2027-demo",
        "opp-hci-workshop",
        "opp-open-source-intern",
        "opp-maker-scholarship",
      ],
      transparent: true,
      paidRandom: false,
    },
    {
      id: "pack-bear-down-campus",
      title: "Bear Down · 校园活动包",
      description:
        "列出 6 项 UArizona 官方校园入口：新生、职业、期中支持、节庆、社团与历史 Replay；不读取私人邮箱。",
      opportunityIds: [
        "opp-ua-bear-down-camp-2026",
        "opp-ua-wildcat-employment-research-fair",
        "opp-ua-bear-down-week-2026",
        "opp-ua-bear-down-fall-festival-2026",
        "opp-ua-clubs-organizations",
        "opp-ua-bear-down-music-festival-2026",
      ],
      transparent: true,
      paidRandom: false,
    },
  ],
  rules: [
    {
      id: "rule-chi-src-student",
      opportunityId: "opp-chi-2027-src",
      fieldId: "field-current-student",
      operator: "eq",
      expectedValue: "undergraduate_enrolled",
      description: "初次提交截止时仍为大学在校学生，并可提供证明",
      sourceRef:
        "https://chi2027.acm.org/authors/student-research-competition/#eligibility-and-guidelines",
      required: true,
    },
    {
      id: "rule-chi-src-portfolio",
      opportunityId: "opp-chi-2027-src",
      fieldId: "field-portfolio-signal",
      operator: "eq",
      expectedValue: "available",
      description: "有可整理为本人学生研究贡献的证据",
      sourceRef:
        "https://chi2027.acm.org/authors/student-research-competition/",
      required: true,
    },
    {
      id: "rule-chi-src-interest",
      opportunityId: "opp-chi-2027-src",
      fieldId: "field-interest-hci",
      operator: "contains",
      expectedValue: "HCI",
      description: "主题能与 HCI、人因或可访问性交叉",
      sourceRef:
        "https://chi2027.acm.org/authors/student-research-competition/",
      required: false,
    },
    {
      id: "rule-chi-src-rights",
      opportunityId: "opp-chi-2027-src",
      fieldId: "field-review-rights",
      operator: "eq",
      expectedValue: "approved_fixture",
      description: "公开内容已做素材权利与隐私检查；演示结果仍要正式复核",
      sourceRef:
        "https://chi2027.acm.org/authors/student-research-competition/",
      required: true,
    },
    {
      id: "rule-chi-demo-portfolio",
      opportunityId: "opp-chi-2027-demo",
      fieldId: "field-portfolio-signal",
      operator: "eq",
      expectedValue: "available",
      description: "有可现场操作的交互原型与演示证据",
      sourceRef: "https://chi2027.acm.org/authors/interactive-demos/",
      required: true,
    },
    {
      id: "rule-chi-demo-interest",
      opportunityId: "opp-chi-2027-demo",
      fieldId: "field-interest-hci",
      operator: "contains",
      expectedValue: "HCI",
      description: "原型能够说明清晰的 HCI 或交互体验贡献",
      sourceRef: "https://chi2027.acm.org/authors/interactive-demos/",
      required: false,
    },
    {
      id: "rule-chi-demo-rights",
      opportunityId: "opp-chi-2027-demo",
      fieldId: "field-review-rights",
      operator: "eq",
      expectedValue: "approved_fixture",
      description: "视频、人物、第三方素材与公开演示权利完成复核",
      sourceRef: "https://chi2027.acm.org/authors/interactive-demos/",
      required: true,
    },
    {
      id: "rule-icra-portfolio",
      opportunityId: "opp-icra-2027-paper",
      fieldId: "field-portfolio-signal",
      operator: "eq",
      expectedValue: "available",
      description: "有机器人或实时系统方向的可复现实验证据",
      sourceRef:
        "https://2027.ieee-icra.org/contribute/call-for-icra-2027-papers-now-accepting-submissions/",
      required: true,
    },
    {
      id: "rule-icra-interest",
      opportunityId: "opp-icra-2027-paper",
      fieldId: "field-interest-signal",
      operator: "contains",
      expectedValue: "传感",
      description: "研究方向与机器人传感、控制或自动化相关",
      sourceRef:
        "https://2027.ieee-icra.org/contribute/call-for-icra-2027-papers-now-accepting-submissions/",
      required: false,
    },
    {
      id: "rule-icra-rights",
      opportunityId: "opp-icra-2027-paper",
      fieldId: "field-review-rights",
      operator: "eq",
      expectedValue: "approved_fixture",
      description: "论文与视频素材具备投稿权利，且不向 AI 暴露审稿机密",
      sourceRef:
        "https://2027.ieee-icra.org/contribute/call-for-icra-2027-papers-now-accepting-submissions/",
      required: true,
    },
    {
      id: "rule-signal-course",
      opportunityId: "opp-signal-lab",
      fieldId: "field-course-sls201",
      operator: "eq",
      expectedValue: "completed",
      description: "已完成或正在完成信号与线性系统基础课程",
      sourceRef: "https://opportunities.example.edu/signal-lab-2026#eligibility-course",
      required: true,
    },
    {
      id: "rule-signal-interest",
      opportunityId: "opp-signal-lab",
      fieldId: "field-interest-signal",
      operator: "contains",
      expectedValue: "信号",
      description: "能说明对信号、传感或时序分析的兴趣",
      sourceRef: "https://opportunities.example.edu/signal-lab-2026#eligibility-interest",
      required: true,
    },
    {
      id: "rule-signal-time",
      opportunityId: "opp-signal-lab",
      fieldId: "field-availability-hours",
      operator: "gte",
      expectedValue: 8,
      description: "连续 6 周每周可投入至少 8 小时",
      sourceRef: "https://opportunities.example.edu/signal-lab-2026#eligibility-time",
      required: true,
    },
    {
      id: "rule-signal-language",
      opportunityId: "opp-signal-lab",
      fieldId: "field-language-english",
      operator: "eq",
      expectedValue: "reading_ready",
      description: "可阅读英文技术摘要；不要求标准化考试分数",
      sourceRef: "https://opportunities.example.edu/signal-lab-2026#eligibility-language",
      required: false,
    },
    {
      id: "rule-adventurex-team-min",
      opportunityId: "opp-adventurex",
      fieldId: "field-team-size",
      operator: "gte",
      expectedValue: 2,
      description: "团队至少 2 人；成员须已录入最终参赛名单",
      sourceRef:
        "https://adventurex.feishu.cn/docx/FOhLdr0Y3okbATxWvBQcoFx0nEd",
      required: true,
    },
    {
      id: "rule-adventurex-team-max",
      opportunityId: "opp-adventurex",
      fieldId: "field-team-size",
      operator: "lte",
      expectedValue: 4,
      description: "团队最多 4 人；每人只能参加一队",
      sourceRef:
        "https://adventurex.feishu.cn/docx/FOhLdr0Y3okbATxWvBQcoFx0nEd",
      required: true,
    },
    {
      id: "rule-adventurex-time",
      opportunityId: "opp-adventurex",
      fieldId: "field-adventurex-attendance",
      operator: "eq",
      expectedValue: "ready",
      description:
        "已确认 07-26 01:00 提交截止与 09:00–15:00 Expo 时段",
      sourceRef:
        "https://adventurex.feishu.cn/docx/FOhLdr0Y3okbATxWvBQcoFx0nEd",
      required: true,
    },
    {
      id: "rule-adventurex-submission",
      opportunityId: "opp-adventurex",
      fieldId: "field-adventurex-submission",
      operator: "eq",
      expectedValue: "ready",
      description:
        "项目说明、技术栈、16:9 首图、GitHub 与小红书链接均已就绪",
      sourceRef:
        "https://adventurex.feishu.cn/docx/FOhLdr0Y3okbATxWvBQcoFx0nEd",
      required: true,
    },
    {
      id: "rule-hci-interest",
      opportunityId: "opp-hci-workshop",
      fieldId: "field-interest-hci",
      operator: "contains",
      expectedValue: "HCI",
      description: "对 HCI 或可访问性有明确兴趣",
      sourceRef: "https://opportunities.example.edu/hci-accessibility-workshop#interest",
      required: false,
    },
    {
      id: "rule-hci-time",
      opportunityId: "opp-hci-workshop",
      fieldId: "field-availability-hours",
      operator: "gte",
      expectedValue: 6,
      description: "两日合计可投入至少 6 小时",
      sourceRef: "https://opportunities.example.edu/hci-accessibility-workshop#time",
      required: true,
    },
    {
      id: "rule-intern-portfolio",
      opportunityId: "opp-open-source-intern",
      fieldId: "field-portfolio-signal",
      operator: "eq",
      expectedValue: "available",
      description: "有可公开审阅的工程作品",
      sourceRef: "https://opportunities.example.edu/open-education-intern#portfolio",
      required: true,
    },
    {
      id: "rule-intern-language",
      opportunityId: "opp-open-source-intern",
      fieldId: "field-language-english",
      operator: "eq",
      expectedValue: "collaboration_ready",
      description: "可进行英文异步协作",
      sourceRef: "https://opportunities.example.edu/open-education-intern#language",
      required: true,
    },
    {
      id: "rule-intern-time",
      opportunityId: "opp-open-source-intern",
      fieldId: "field-availability-hours",
      operator: "gte",
      expectedValue: 12,
      description: "每周可投入至少 12 小时",
      sourceRef: "https://opportunities.example.edu/open-education-intern#time",
      required: true,
    },
    {
      id: "rule-grant-portfolio",
      opportunityId: "opp-maker-scholarship",
      fieldId: "field-portfolio-signal",
      operator: "eq",
      expectedValue: "available",
      description: "有原型与材料需求说明",
      sourceRef: "https://opportunities.example.edu/maker-microgrant#prototype",
      required: true,
    },
    {
      id: "rule-grant-budget",
      opportunityId: "opp-maker-scholarship",
      fieldId: "field-budget-draft",
      operator: "eq",
      expectedValue: "ready",
      description: "提交透明材料预算；不读取家庭财务账户",
      sourceRef: "https://opportunities.example.edu/maker-microgrant#budget",
      required: true,
    },
    {
      id: "rule-campus-interest",
      opportunityId: "opp-campus-data-project",
      fieldId: "field-interest-hci",
      operator: "contains",
      expectedValue: "服务设计",
      description: "对校园服务设计或可达性研究有兴趣",
      sourceRef: "https://opportunities.example.edu/campus-data-cocreate#interest",
      required: false,
    },
    {
      id: "rule-campus-time",
      opportunityId: "opp-campus-data-project",
      fieldId: "field-availability-hours",
      operator: "gte",
      expectedValue: 5,
      description: "每周可投入至少 5 小时",
      sourceRef: "https://opportunities.example.edu/campus-data-cocreate#time",
      required: true,
    },
    {
      id: "rule-campus-ethics",
      opportunityId: "opp-campus-data-project",
      fieldId: "field-ethics-training",
      operator: "eq",
      expectedValue: "complete",
      description: "完成数据伦理培训",
      sourceRef: "https://opportunities.example.edu/campus-data-cocreate#ethics",
      required: true,
    },
    {
      id: "rule-journal-abstract",
      opportunityId: "opp-journal-clinic",
      fieldId: "field-portfolio-signal",
      operator: "eq",
      expectedValue: "available",
      description: "准备一页摘要",
      sourceRef: "https://opportunities.example.edu/journal-clinic-archive#abstract",
      required: true,
    },
    {
      id: "rule-ua-bdc-first-year",
      opportunityId: "opp-ua-bear-down-camp-2026",
      fieldId: "field-ua-first-year",
      operator: "eq",
      expectedValue: "incoming_first_year",
      description:
        "Bear Down Camp 面向 incoming freshmen / first-year；当前脱敏档案未确认该状态",
      sourceRef:
        "https://asuatoday.arizona.edu/what-we-do/bear-down-camp",
      required: true,
    },
    {
      id: "rule-ua-current-student-fair",
      opportunityId: "opp-ua-wildcat-employment-research-fair",
      fieldId: "field-current-student",
      operator: "eq",
      expectedValue: "undergraduate_enrolled",
      description: "当前为在校学生；具体参会登记仍以 Handshake 当次页面为准",
      sourceRef: "https://career.arizona.edu/channels/career-fairs/",
      required: true,
    },
    {
      id: "rule-ua-current-student-week",
      opportunityId: "opp-ua-bear-down-week-2026",
      fieldId: "field-current-student",
      operator: "eq",
      expectedValue: "undergraduate_enrolled",
      description: "当前为在校学生；活动周子项目可能另有条件",
      sourceRef: "https://studentaffairs.arizona.edu/bear-down-week",
      required: false,
    },
    {
      id: "rule-ua-current-student-festival",
      opportunityId: "opp-ua-bear-down-fall-festival-2026",
      fieldId: "field-current-student",
      operator: "eq",
      expectedValue: "undergraduate_enrolled",
      description: "当前为在校学生；入场与容量须等待官方详情",
      sourceRef: "https://studentaffairs.arizona.edu/",
      required: false,
    },
    {
      id: "rule-ua-current-student-clubs",
      opportunityId: "opp-ua-clubs-organizations",
      fieldId: "field-current-student",
      operator: "eq",
      expectedValue: "undergraduate_enrolled",
      description: "当前为在校学生；每个组织独立核验会员条件",
      sourceRef:
        "https://www.arizona.edu/student-life/getting-involved?publication=20260106",
      required: false,
    },
    {
      id: "rule-ua-current-student-music",
      opportunityId: "opp-ua-bear-down-music-festival-2026",
      fieldId: "field-current-student",
      operator: "eq",
      expectedValue: "undergraduate_enrolled",
      description: "历史活动身份条件仅供 Replay，不再用于报名",
      sourceRef:
        "https://asuatoday.arizona.edu/programs-services/bear-down-music-festival",
      required: false,
    },
  ],
  profileFields: [
    {
      id: "field-current-student",
      label: "身份 · 当前本科在读（脱敏演示）",
      kind: "verified_evidence",
      value: "undergraduate_enrolled",
      valueLabel: "Academic Mirror 演示镜像 · 正式投稿需学校证明",
      authority: "verified_fixture",
      sourceId: "F-003:nr-profile-student-nan",
      verifiedAt: "2026-07-24T07:00:00+08:00",
      expiresAt: "2027-01-21T23:59:00-12:00",
      private: true,
      selectable: true,
    },
    {
      id: "field-ua-first-year",
      label: "身份 · UArizona incoming first-year",
      kind: "self_declared",
      value: "not_confirmed",
      valueLabel: "未选择；Bear Down Camp 资格需本人确认",
      authority: "self_declared",
      sourceId: null,
      verifiedAt: null,
      expiresAt: null,
      private: true,
      selectable: true,
    },
    {
      id: "field-goal-research",
      label: "目标 · 尝试一段可回滚研究经历",
      kind: "goal",
      value: "research_exploration",
      valueLabel: "研究体验，不承诺发表",
      authority: "self_declared",
      sourceId: null,
      verifiedAt: null,
      expiresAt: null,
      private: true,
      selectable: true,
    },
    {
      id: "field-interest-signal",
      label: "兴趣 · 信号 / 传感 / 时序分析",
      kind: "interest",
      value: ["信号", "传感", "时序分析"],
      valueLabel: "本人声明",
      authority: "self_declared",
      sourceId: null,
      verifiedAt: null,
      expiresAt: null,
      private: true,
      selectable: true,
    },
    {
      id: "field-interest-hci",
      label: "兴趣 · HCI / 服务设计 / 可访问性",
      kind: "interest",
      value: ["HCI", "服务设计", "可访问性"],
      valueLabel: "本人声明",
      authority: "self_declared",
      sourceId: null,
      verifiedAt: null,
      expiresAt: null,
      private: true,
      selectable: true,
    },
    {
      id: "field-availability-hours",
      label: "可用时间 · 每周 6 小时",
      kind: "availability",
      value: 6,
      valueLabel: "本人声明 · 本周",
      authority: "self_declared",
      sourceId: "F-006:ev-self-capacity-001",
      verifiedAt: "2026-07-24T07:30:00+08:00",
      expiresAt: "2026-07-31T23:59:00+08:00",
      private: true,
      selectable: true,
    },
    {
      id: "field-course-sls201",
      label: "课程 · 信号与线性系统",
      kind: "verified_evidence",
      value: "completed",
      valueLabel: "演示镜像 · 已完成",
      authority: "verified_fixture",
      sourceId: "F-003:nr-course-sls201",
      verifiedAt: "2026-07-23T16:00:00+08:00",
      expiresAt: "2026-08-23T16:00:00+08:00",
      private: true,
      selectable: true,
    },
    {
      id: "field-portfolio-signal",
      label: "作品 · University2K26 信号课程 Demo",
      kind: "verified_evidence",
      value: "available",
      valueLabel: "教师审核演示 · 可选导出",
      authority: "verified_fixture",
      sourceId: "F-001:publication-sls-001",
      verifiedAt: "2026-07-24T06:00:00+08:00",
      expiresAt: null,
      private: true,
      selectable: true,
    },
    {
      id: "field-language-english",
      label: "语言 · 英文技术阅读",
      kind: "self_declared",
      value: "reading_ready",
      valueLabel: "本人声明 · 未验证异步协作",
      authority: "self_declared",
      sourceId: null,
      verifiedAt: null,
      expiresAt: null,
      private: true,
      selectable: true,
    },
    {
      id: "field-team-size",
      label: "团队 · 当前 1 位已确认",
      kind: "self_declared",
      value: 1,
      valueLabel: "本人声明 · 不抓取通讯录",
      authority: "self_declared",
      sourceId: null,
      verifiedAt: null,
      expiresAt: "2026-07-28T23:59:00+08:00",
      private: true,
      selectable: true,
    },
    {
      id: "field-adventurex-attendance",
      label: "AdventureX 时段 · 已确认现场投入",
      kind: "self_declared",
      value: "ready",
      valueLabel: "本人声明 · 提交与 Expo 时段已留出",
      authority: "self_declared",
      sourceId: null,
      verifiedAt: null,
      expiresAt: "2026-07-26T15:00:00+08:00",
      private: true,
      selectable: true,
    },
    {
      id: "field-adventurex-submission",
      label: "AdventureX 提交包 · 构建中",
      kind: "self_declared",
      value: "in_progress",
      valueLabel: "代码仓库已就绪；封面、发布链接与 Portal 回执待完成",
      authority: "self_declared",
      sourceId: null,
      verifiedAt: null,
      expiresAt: "2026-07-26T01:00:00+08:00",
      private: true,
      selectable: true,
    },
    {
      id: "field-review-rights",
      label: "公开权利 · 仅演示教师审核",
      kind: "verified_evidence",
      value: "approved_fixture",
      valueLabel: "不等于真实公开许可",
      authority: "verified_fixture",
      sourceId: "F-001:review-revision-3",
      verifiedAt: "2026-07-24T06:00:00+08:00",
      expiresAt: null,
      private: true,
      selectable: true,
    },
    {
      id: "field-budget-draft",
      label: "材料预算 · 尚未准备",
      kind: "self_declared",
      value: "missing",
      valueLabel: "不读取家庭或银行卡信息",
      authority: "self_declared",
      sourceId: null,
      verifiedAt: null,
      expiresAt: null,
      private: true,
      selectable: true,
    },
    {
      id: "field-ethics-training",
      label: "数据伦理培训 · 未知",
      kind: "verified_evidence",
      value: "unknown",
      valueLabel: "Academic Mirror 无记录",
      authority: "demo_fixture",
      sourceId: "F-003:gap-ethics-training",
      verifiedAt: "2026-07-23T16:00:00+08:00",
      expiresAt: "2026-08-23T16:00:00+08:00",
      private: true,
      selectable: true,
    },
  ],
  eligibilityChecks: [],
  matchResults: [],
  savedOpportunities: [],
  disclosureGrants: [],
  applicationMirrors: [],
  entitlements: [
    {
      id: "ent-workshop-2026",
      title: "HCI Workshop 学生权益",
      provider: "示例学生发展办公室",
      scope: "抵扣一次已确认工作坊学生票，不影响资格或排序",
      conditions: ["本人主动使用", "仅限 opp-hci-workshop", "以提供方确认邮件为准"],
      validFrom: "2026-07-24T00:00:00+08:00",
      expiresAt: "2026-08-10T17:00:00+08:00",
      status: "available",
      sourceId: "fixture:entitlement-workshop-2026",
      purchasableQualification: false,
    },
    {
      id: "ent-lab-slot",
      title: "开放实验室 2 小时时段",
      provider: "示例工程实验室",
      scope: "一次设备预约入口；不代表已经预约或获准进入",
      conditions: ["完成安全培训", "在正式预约系统确认"],
      validFrom: "2026-07-24T00:00:00+08:00",
      expiresAt: "2026-08-31T23:59:00+08:00",
      status: "available",
      sourceId: "fixture:entitlement-lab-slot",
      purchasableQualification: false,
    },
    {
      id: "ent-travel",
      title: "校内展示差旅候选",
      provider: "示例本科生研究办公室",
      scope: "最高 300 元报销候选；须另走政策审批",
      conditions: ["仅限已批准展示", "保留票据", "不兑换现金或资格"],
      validFrom: "2026-08-01T00:00:00+08:00",
      expiresAt: "2026-10-01T23:59:00+08:00",
      status: "available",
      sourceId: "fixture:entitlement-travel",
      purchasableQualification: false,
    },
  ],
  capacity: [
    {
      id: "time",
      label: "每周时间",
      available: 18,
      committed: 12,
      unit: "小时",
      sourceLabel: "本人声明 · 7 天有效",
      canPurchaseEligibility: false,
    },
    {
      id: "energy",
      label: "可持续精力",
      available: 5,
      committed: 3,
      unit: "档",
      sourceLabel: "本人私密选择 · 非健康指标",
      canPurchaseEligibility: false,
    },
    {
      id: "lab_slot",
      label: "实验室时段",
      available: 2,
      committed: 0,
      unit: "小时",
      sourceLabel: "演示权益 · 需正式预约",
      canPurchaseEligibility: false,
    },
    {
      id: "funding",
      label: "已获资助容量",
      available: 300,
      committed: 0,
      unit: "CNY",
      sourceLabel: "演示政策候选 · 非现金余额",
      canPurchaseEligibility: false,
    },
  ],
  capacityPlans: [],
  pathways: [
    {
      id: "path-major-change",
      title: "A · 转向交互技术方向",
      type: "major_change",
      inheritedCredits: "预计保留 72–78 学分；6 学分需院系确认",
      estimatedTime: "可能增加 0–1 学期",
      estimatedCost: "仅展示学费与机会成本区间；当前无正式费率",
      assumptions: ["当前演示课程可以映射", "目标院系允许跨专业申请"],
      risks: ["学分映射未获批准", "容量与先修可能变化"],
      rollbackPoint: "提交正式转专业申请前可回到当前培养路径",
      approvalPath: ["学业顾问复核", "目标院系审核", "权威系统正式提交"],
      authoritative: false,
    },
    {
      id: "path-exchange",
      title: "B · 一学期交换",
      type: "exchange",
      inheritedCredits: "预估 12–16 学分；逐门课程预审",
      estimatedTime: "不延长或增加 1 学期，取决于学分确认",
      estimatedCost: "差旅、住宿、保险均为未知项",
      assumptions: ["语言材料可补齐", "目标课程仍开放"],
      risks: ["课程变更", "签证与住宿不确定"],
      rollbackPoint: "正式提名前可删除方案，不影响当前课表",
      approvalPath: ["国际处咨询", "课程预审", "提名", "外部申请"],
      authoritative: false,
    },
    {
      id: "path-accelerated",
      title: "C · 提前修读研究生课程",
      type: "accelerated_study",
      inheritedCredits: "最多 6 学分候选；政策需逐条核验",
      estimatedTime: "可能缩短后续培养，但增加当前负荷",
      estimatedCost: "费用与学分双计规则未知",
      assumptions: ["先修满足", "课程有容量", "学院批准"],
      risks: ["高负荷", "课程不计入目标学位"],
      rollbackPoint: "选课交易确认前保持 What-if",
      approvalPath: ["导师建议", "研究生院规则核验", "院系批准", "正式选课"],
      authoritative: false,
    },
  ],
  selectedPathwayId: null,
  portfolioArtifacts: [
    {
      id: "artifact-smartcourse",
      title: "智课工坊 · 来源约束讲解对象",
      sourceModule: "F-001",
      sourceId: "publication-sls-001",
      reviewStatus: "teacher_approved_fixture",
      includesOriginalMaterial: false,
      selected: false,
    },
    {
      id: "artifact-world-exam",
      title: "World Exam · 本人来源挑战复盘",
      sourceModule: "F-005",
      sourceId: "reflection-sls-final-001",
      reviewStatus: "private_reflection",
      includesOriginalMaterial: false,
      selected: false,
    },
  ],
  reports: [],
  fairnessAudits: [],
  notifications: [
    {
      id: "notice-expired-journal",
      opportunityId: "opp-journal-clinic",
      kind: "expiry",
      message: "学生期刊开放投稿门诊已过期，已从默认发现结果移除。",
      createdAt: "2026-07-11T08:00:00+08:00",
      read: false,
    },
  ],
  audit: [
    {
      id: "opp-event-001",
      sequence: 1,
      action: "view",
      targetId: "market",
      detail:
        "loaded sixteen transparent opportunities across Bear Down campus and external leagues; two expired campus items excluded by default",
      occurredAt: "2026-07-24T08:00:00+08:00",
      previousEventHash: null,
      eventHash: "fnv1a-opp-event-001",
    },
  ],
  offline: false,
  simplified: false,
  reducedMotion: false,
  message:
    "机会板已就位：10 个官方入口，6 个演示条目。条件全都摊开写，也没人能花钱插队。",
  invariants: {
    noPaidRanking: true,
    noRandomQualification: true,
    noHumanAuction: true,
    noAutoApply: true,
    noFomoCountdown: true,
    noCompositeEligibilityScore: true,
  },
};
