import type {
  AuditEvent,
  AuthorityDefinition,
  AuthorityLevel,
  ConflictRecord,
  ConsentRecord,
  MirrorDataSource,
  MirrorFixture,
  NormalizedField,
  NormalizedRecord,
  RawSnapshot,
} from "./types";

const REFERENCE_TIME = "2026-07-24T18:00:00+08:00";

const HASHES = {
  sis: "sha256:6b43a6aa60fb2d35c5907c643e9a519b7f615959b92983c9e649f04c5b51f15f",
  catalog:
    "sha256:fc88bf3c8ef9a5e40e51465b4a89fab6c8320258d911b3178400e7589429f736",
  file: "sha256:423c25d04dd9fd711eb65683f7bca7a52e538245018362875ca9fd6c0958f311",
  self: "sha256:1731c5f2b49199dc82167a8f0d0d0bcf38f91aaab260deef564c866f151b9624",
  model:
    "sha256:5bdabf57a889166430ab6f79d97c918d404665bb20b75fbf08c1a83063b48b9b",
  fixture:
    "sha256:b302d1df0b51c3459e32c33d2f9903fc7693baa373069413607b7ac756010e79",
} as const;

export const AUTHORITY_CATALOG: AuthorityDefinition[] = [
  {
    level: "authoritative",
    title: "权威记录",
    description: "学校正式学籍、成绩等记录；仍需通过正式系统办理更正。",
    highRiskEligible: true,
  },
  {
    level: "official_reference",
    title: "官方参考",
    description: "课程目录、培养方案等官方公开或授权参考。",
    highRiskEligible: true,
  },
  {
    level: "authorized_mirror",
    title: "授权镜像",
    description: "经授权导出的只读副本；高风险用途还需检查新鲜度。",
    highRiskEligible: true,
  },
  {
    level: "self_declared",
    title: "本人声明",
    description: "学生主动填写的兴趣或目标，可撤回，不代替正式记录。",
    highRiskEligible: false,
  },
  {
    level: "model_inferred",
    title: "模型推断",
    description: "AI 生成的建议或推断，只能作为可拒绝的解释线索。",
    highRiskEligible: false,
  },
  {
    level: "demo_fixture",
    title: "演示夹具",
    description: "虚构、脱敏的演示数据，永远不能支持正式决定。",
    highRiskEligible: false,
  },
];

const source = (
  value: Omit<
    MirrorDataSource,
    "authMethod" | "refreshMethod" | "consentRequired" | "status"
  >,
): MirrorDataSource => ({
  ...value,
  authMethod: value.adapterKind === "file_import" ? "file_import" : "manual",
  refreshMethod: value.adapterKind === "file_import" ? "manual" : "on_demand",
  consentRequired: true,
  status: "active",
});

export const MIRROR_SOURCES: MirrorDataSource[] = [
  source({
    id: "ds-sis-demo",
    name: "SIS 权威记录演示源",
    systemType: "sis",
    adapterKind: "demo_fixture",
    responsibleParty: "教务处（Fixture）",
    fieldScope: ["student.name", "student.major", "grade.result"],
    retentionDays: 30,
    correctionRoute: "正式记录请联系学校教务处；本页只能提交镜像校对请求。",
    authorized: true,
    declaredAuthority: "authoritative",
    lastSyncedAt: "2026-07-24T10:30:00+08:00",
    createdAt: "2026-07-24T09:00:00+08:00",
    updatedAt: "2026-07-24T10:30:00+08:00",
  }),
  source({
    id: "ds-catalog-demo",
    name: "课程目录演示源",
    systemType: "sis",
    adapterKind: "demo_fixture",
    responsibleParty: "本科生院（Fixture）",
    fieldScope: ["course.title", "course.credits", "requirement.rules"],
    retentionDays: 90,
    correctionRoute: "课程目录问题请通过本科生院课程目录勘误入口核对。",
    authorized: true,
    declaredAuthority: "official_reference",
    lastSyncedAt: "2026-07-23T16:00:00+08:00",
    createdAt: "2026-07-23T15:30:00+08:00",
    updatedAt: "2026-07-23T16:00:00+08:00",
  }),
  source({
    id: "ds-file-import",
    name: "已授权活动导出文件",
    systemType: "manual_export",
    adapterKind: "file_import",
    responsibleParty: "学生本人",
    fieldScope: ["activity.title", "activity.role", "activity.hours"],
    retentionDays: 14,
    correctionRoute: "重新导入已脱敏文件，或删除此非权威副本。",
    authorized: true,
    declaredAuthority: "authorized_mirror",
    lastSyncedAt: "2026-07-24T11:10:00+08:00",
    createdAt: "2026-07-24T11:00:00+08:00",
    updatedAt: "2026-07-24T11:10:00+08:00",
  }),
  source({
    id: "ds-self-profile",
    name: "本人目标与偏好",
    systemType: "manual_export",
    adapterKind: "file_import",
    responsibleParty: "学生本人",
    fieldScope: ["student.goal", "student.study_preference"],
    retentionDays: 365,
    correctionRoute: "本人可直接更新或删除此声明，不影响学校正式记录。",
    authorized: true,
    declaredAuthority: "self_declared",
    lastSyncedAt: "2026-07-24T11:20:00+08:00",
    createdAt: "2026-07-24T11:15:00+08:00",
    updatedAt: "2026-07-24T11:20:00+08:00",
  }),
  source({
    id: "ds-model-insight",
    name: "本地模型建议输出",
    systemType: "manual_export",
    adapterKind: "file_import",
    responsibleParty: "University2K26 本地 AI",
    fieldScope: ["student.suggested_focus"],
    retentionDays: 7,
    correctionRoute: "可拒绝或删除模型推断；模型无权修改正式记录。",
    authorized: true,
    declaredAuthority: "model_inferred",
    lastSyncedAt: "2026-07-24T11:25:00+08:00",
    createdAt: "2026-07-24T11:22:00+08:00",
    updatedAt: "2026-07-24T11:25:00+08:00",
  }),
  source({
    id: "ds-pure-fixture",
    name: "镜像流程演示夹具",
    systemType: "demo_fixture",
    adapterKind: "demo_fixture",
    responsibleParty: "University2K26 Demo",
    fieldScope: ["term.label", "term.season"],
    retentionDays: 1,
    correctionRoute: "演示夹具可重置，不代表任何学校或学生。",
    authorized: true,
    declaredAuthority: "demo_fixture",
    lastSyncedAt: "2026-07-24T10:00:00+08:00",
    createdAt: "2026-07-24T10:00:00+08:00",
    updatedAt: "2026-07-24T10:00:00+08:00",
  }),
];

const snapshot = (
  id: string,
  dataSourceId: string,
  sourceVersion: string,
  fetchedAt: string,
  contentHash: string,
  format: RawSnapshot["format"],
): RawSnapshot => ({
  id,
  dataSourceId,
  externalId: `${dataSourceId}-student-nan`,
  sourceVersion,
  fetchedAt,
  contentHash,
  rawReference: `fixture://academic-mirror/${id}`,
  format,
  sizeBytes: 512 + id.length * 17,
  immutable: true,
  demoFixture: true,
});

export const MIRROR_SNAPSHOTS: RawSnapshot[] = [
  snapshot(
    "snap-sis-001",
    "ds-sis-demo",
    "sis-fixture-r4",
    "2026-07-24T10:30:00+08:00",
    HASHES.sis,
    "json",
  ),
  snapshot(
    "snap-catalog-001",
    "ds-catalog-demo",
    "catalog-fixture-r3",
    "2026-07-23T16:00:00+08:00",
    HASHES.catalog,
    "json",
  ),
  snapshot(
    "snap-file-001",
    "ds-file-import",
    "authorized-export-r1",
    "2026-07-24T11:10:00+08:00",
    HASHES.file,
    "csv",
  ),
  snapshot(
    "snap-self-001",
    "ds-self-profile",
    "self-declared-r1",
    "2026-07-24T11:20:00+08:00",
    HASHES.self,
    "manual",
  ),
  snapshot(
    "snap-model-001",
    "ds-model-insight",
    "local-model-r1",
    "2026-07-24T11:25:00+08:00",
    HASHES.model,
    "json",
  ),
  snapshot(
    "snap-fixture-001",
    "ds-pure-fixture",
    "fixture-r1",
    "2026-07-24T10:00:00+08:00",
    HASHES.fixture,
    "json",
  ),
];

const field = (
  value: NormalizedField["value"],
  dataSourceId: string,
  externalField: string,
  declaredAuthority: AuthorityLevel,
  rawSnapshotId: string,
  sourceVersion: string,
  fetchedAt: string,
  conversionRule = "原值映射；保留未知字段",
): NormalizedField => ({
  value,
  provenance: {
    sourceSystem:
      MIRROR_SOURCES.find((candidate) => candidate.id === dataSourceId)?.name ??
      dataSourceId,
    dataSourceId,
    externalField,
    sourceVersion,
    fetchedAt,
    declaredAuthority,
    effectiveAuthority: "demo_fixture",
    conversionRule,
    rawSnapshotId,
  },
});

const record = (
  value: Omit<NormalizedRecord, "studentId" | "demoFixture">,
): NormalizedRecord => ({
  ...value,
  studentId: "student-nan-fixture",
  demoFixture: true,
});

export const MIRROR_RECORDS: NormalizedRecord[] = [
  record({
    id: "nr-student-profile",
    snapshotIds: ["snap-sis-001"],
    entityType: "student",
    entityId: "student-nan-fixture",
    label: "南同学（NaN）· 学生档案",
    fields: {
      display_name: field(
        "南同学（NaN）",
        "ds-sis-demo",
        "student.display_name",
        "authoritative",
        "snap-sis-001",
        "sis-fixture-r4",
        "2026-07-24T10:30:00+08:00",
      ),
      major: field(
        "电子信息工程（Fixture）",
        "ds-sis-demo",
        "student.major_name",
        "authoritative",
        "snap-sis-001",
        "sis-fixture-r4",
        "2026-07-24T10:30:00+08:00",
      ),
      unknown_extension: field(
        "retained:campus_cohort_x",
        "ds-sis-demo",
        "extensions.campus_cohort",
        "authoritative",
        "snap-sis-001",
        "sis-fixture-r4",
        "2026-07-24T10:30:00+08:00",
        "未知字段原样保留，不进入正式判断",
      ),
    },
    effectiveAt: "2026-07-24T10:30:00+08:00",
    expiresAt: "2026-08-23T10:30:00+08:00",
    consentBasis: "consent-sis-read",
    correctionRoute: "正式档案请联系教务处；镜像差异可提交校对。",
    removable: false,
  }),
  record({
    id: "nr-course-sls201",
    snapshotIds: ["snap-catalog-001", "snap-file-001"],
    entityType: "course",
    entityId: "SLS201",
    label: "SLS201 · 信号与线性系统",
    fields: {
      title: field(
        "信号与线性系统",
        "ds-catalog-demo",
        "course.name_zh",
        "official_reference",
        "snap-catalog-001",
        "catalog-fixture-r3",
        "2026-07-23T16:00:00+08:00",
      ),
      credits: field(
        3,
        "ds-catalog-demo",
        "course.credit_value",
        "official_reference",
        "snap-catalog-001",
        "catalog-fixture-r3",
        "2026-07-23T16:00:00+08:00",
        "decimal credits → integer when exact",
      ),
      season_role: field(
        "主赛程",
        "ds-pure-fixture",
        "demo.season_role",
        "demo_fixture",
        "snap-fixture-001",
        "fixture-r1",
        "2026-07-24T10:00:00+08:00",
      ),
    },
    effectiveAt: "2026-07-23T16:00:00+08:00",
    expiresAt: "2026-07-24T22:00:00+08:00",
    consentBasis: "consent-sis-read",
    correctionRoute: "请从学校课程目录核对，并向本科生院提交勘误。",
    removable: false,
  }),
  record({
    id: "nr-grade-sls201",
    snapshotIds: ["snap-sis-001"],
    entityType: "grade",
    entityId: "SLS201-grade-demo",
    label: "SLS201 · 历史成绩样例",
    fields: {
      result: field(
        "91.7 / A-（Fixture）",
        "ds-sis-demo",
        "grade.display_result",
        "authoritative",
        "snap-sis-001",
        "sis-fixture-r4",
        "2026-07-24T10:30:00+08:00",
      ),
      formal_status: field(
        false,
        "ds-pure-fixture",
        "demo.is_formal_grade",
        "demo_fixture",
        "snap-fixture-001",
        "fixture-r1",
        "2026-07-24T10:00:00+08:00",
      ),
    },
    effectiveAt: "2026-07-10T08:00:00+08:00",
    expiresAt: "2026-07-22T08:00:00+08:00",
    consentBasis: "consent-sis-read",
    correctionRoute: "此为过期 Fixture；正式成绩必须回到学校成绩系统核对。",
    removable: false,
  }),
  record({
    id: "nr-activity-hackathon",
    snapshotIds: ["snap-file-001"],
    entityType: "activity",
    entityId: "activity-adventurex-demo",
    label: "AdventureX 项目经历（授权导入）",
    fields: {
      title: field(
        "University2K26 原型协作",
        "ds-file-import",
        "activity.title",
        "authorized_mirror",
        "snap-file-001",
        "authorized-export-r1",
        "2026-07-24T11:10:00+08:00",
      ),
      role: field(
        "产品与工程协作",
        "ds-file-import",
        "activity.role",
        "authorized_mirror",
        "snap-file-001",
        "authorized-export-r1",
        "2026-07-24T11:10:00+08:00",
      ),
      hours: field(
        8,
        "ds-file-import",
        "activity.hours",
        "authorized_mirror",
        "snap-file-001",
        "authorized-export-r1",
        "2026-07-24T11:10:00+08:00",
      ),
    },
    effectiveAt: "2026-07-24T11:10:00+08:00",
    expiresAt: null,
    consentBasis: "consent-activity-opportunity",
    correctionRoute: "可重新导入或删除此授权副本。",
    removable: true,
  }),
  record({
    id: "nr-self-goal",
    snapshotIds: ["snap-self-001"],
    entityType: "student",
    entityId: "student-nan-fixture-goal",
    label: "本人方向偏好",
    fields: {
      goal: field(
        "交互设计 × 嵌入式系统",
        "ds-self-profile",
        "student.goal",
        "self_declared",
        "snap-self-001",
        "self-declared-r1",
        "2026-07-24T11:20:00+08:00",
      ),
      study_preference: field(
        ["项目制", "可解释反馈", "午后专注"],
        "ds-self-profile",
        "student.study_preference",
        "self_declared",
        "snap-self-001",
        "self-declared-r1",
        "2026-07-24T11:20:00+08:00",
      ),
    },
    effectiveAt: "2026-07-24T11:20:00+08:00",
    expiresAt: null,
    consentBasis: "consent-self-profile",
    correctionRoute: "本人可随时更新或删除。",
    removable: true,
  }),
  record({
    id: "nr-model-suggestion",
    snapshotIds: ["snap-model-001"],
    entityType: "requirement",
    entityId: "suggestion-focus-demo",
    label: "AI 学习建议（可拒绝）",
    fields: {
      suggested_focus: field(
        "先核对卷积与系统性质的证据链",
        "ds-model-insight",
        "model.suggested_focus",
        "model_inferred",
        "snap-model-001",
        "local-model-r1",
        "2026-07-24T11:25:00+08:00",
      ),
      confidence_label: field(
        "medium · not a decision",
        "ds-model-insight",
        "model.confidence",
        "model_inferred",
        "snap-model-001",
        "local-model-r1",
        "2026-07-24T11:25:00+08:00",
      ),
    },
    effectiveAt: "2026-07-24T11:25:00+08:00",
    expiresAt: "2026-07-31T11:25:00+08:00",
    consentBasis: "consent-model-revoked",
    correctionRoute: "可拒绝或删除；模型不能更改课程、成绩或学籍。",
    removable: true,
  }),
];

export const MIRROR_CONFLICTS: ConflictRecord[] = [
  {
    id: "conf-sls-credits",
    entityId: "SLS201",
    entityLabel: "SLS201 · 信号与线性系统",
    fieldName: "credits",
    status: "detected",
    resolution: null,
    options: [
      {
        id: "opt-catalog-3",
        sourceSystem: "课程目录演示源",
        dataSourceId: "ds-catalog-demo",
        value: 3,
        declaredAuthority: "official_reference",
        fetchedAt: "2026-07-23T16:00:00+08:00",
        rawSnapshotId: "snap-catalog-001",
      },
      {
        id: "opt-file-4",
        sourceSystem: "已授权活动导出文件",
        dataSourceId: "ds-file-import",
        value: 4,
        declaredAuthority: "authorized_mirror",
        fetchedAt: "2026-07-24T11:10:00+08:00",
        rawSnapshotId: "snap-file-001",
      },
    ],
  },
  {
    id: "conf-major-label",
    entityId: "student-nan-fixture",
    entityLabel: "南同学（NaN）· 学生档案",
    fieldName: "major",
    status: "detected",
    resolution: null,
    options: [
      {
        id: "opt-sis-major",
        sourceSystem: "SIS 权威记录演示源",
        dataSourceId: "ds-sis-demo",
        value: "电子信息工程（Fixture）",
        declaredAuthority: "authoritative",
        fetchedAt: "2026-07-24T10:30:00+08:00",
        rawSnapshotId: "snap-sis-001",
      },
      {
        id: "opt-self-major",
        sourceSystem: "本人目标与偏好",
        dataSourceId: "ds-self-profile",
        value: "电子信息工程 + 交互设计方向",
        declaredAuthority: "self_declared",
        fetchedAt: "2026-07-24T11:20:00+08:00",
        rawSnapshotId: "snap-self-001",
      },
    ],
  },
];

export const MIRROR_CONSENTS: ConsentRecord[] = [
  {
    id: "consent-sis-read",
    studentId: "student-nan-fixture",
    dataSourceId: "ds-sis-demo",
    allowedModules: ["F-002", "F-004"],
    purpose: "在赛季中心展示课程状态，并为 Roster Lab 提供只读 Prefix。",
    grantedAt: "2026-07-24T09:40:00+08:00",
    expiresAt: "2026-08-24T09:40:00+08:00",
    revokedAt: null,
    scope: "read_only",
  },
  {
    id: "consent-catalog-read",
    studentId: "student-nan-fixture",
    dataSourceId: "ds-catalog-demo",
    allowedModules: ["F-002", "F-004"],
    purpose: "显示课程目录并解释培养方案约束。",
    grantedAt: "2026-07-24T09:42:00+08:00",
    expiresAt: "2026-10-24T09:42:00+08:00",
    revokedAt: null,
    scope: "read_only",
  },
  {
    id: "consent-activity-opportunity",
    studentId: "student-nan-fixture",
    dataSourceId: "ds-file-import",
    allowedModules: ["F-009"],
    purpose: "用于机会匹配资格解释；不自动投递。",
    grantedAt: "2026-07-24T11:12:00+08:00",
    expiresAt: "2026-08-07T11:12:00+08:00",
    revokedAt: null,
    scope: "matching",
  },
  {
    id: "consent-self-profile",
    studentId: "student-nan-fixture",
    dataSourceId: "ds-self-profile",
    allowedModules: ["F-004", "F-006", "F-009"],
    purpose: "用于本人可撤回的规划偏好与机会匹配。",
    grantedAt: "2026-07-24T11:22:00+08:00",
    expiresAt: null,
    revokedAt: null,
    scope: "matching",
  },
  {
    id: "consent-model-revoked",
    studentId: "student-nan-fixture",
    dataSourceId: "ds-model-insight",
    allowedModules: ["F-006"],
    purpose: "曾用于学习建议，现已撤回。",
    grantedAt: "2026-07-24T11:26:00+08:00",
    expiresAt: "2026-07-31T11:26:00+08:00",
    revokedAt: "2026-07-24T11:30:00+08:00",
    scope: "read_only",
  },
];

const audit = (
  sequence: number,
  action: AuditEvent["action"],
  targetEntity: string,
  timestamp: string,
  detail: string,
  previousEventHash: string | null,
  eventHash: string,
): AuditEvent => ({
  id: `aud-${String(sequence).padStart(3, "0")}`,
  sequence,
  action,
  actorId: "student-nan-fixture",
  targetEntity,
  timestamp,
  detail,
  previousEventHash,
  eventHash,
  appendOnly: true,
});

export const MIRROR_AUDIT: AuditEvent[] = [
  audit(
    1,
    "sync",
    "source:ds-sis-demo",
    "2026-07-24T10:30:00+08:00",
    "DemoFixtureAdapter 生成不可变快照 snap-sis-001。",
    null,
    "fnv1a-aud-001",
  ),
  audit(
    2,
    "map",
    "snapshot:snap-sis-001",
    "2026-07-24T10:31:00+08:00",
    "映射 2 条标准记录；字段级来源已保留。",
    "fnv1a-aud-001",
    "fnv1a-aud-002",
  ),
  audit(
    3,
    "sync",
    "source:ds-file-import",
    "2026-07-24T11:10:00+08:00",
    "FileImportAdapter 读取已脱敏授权样例，未上传原文件。",
    "fnv1a-aud-002",
    "fnv1a-aud-003",
  ),
  audit(
    4,
    "consent_revoke",
    "consent:consent-model-revoked",
    "2026-07-24T11:30:00+08:00",
    "撤回 F-006 对模型推断源的读取同意。",
    "fnv1a-aud-003",
    "fnv1a-aud-004",
  ),
];

export const ACADEMIC_MIRROR_FIXTURE: MirrorFixture = {
  schemaVersion: "1.0.0",
  dataMode: "fixture",
  studentId: "student-nan-fixture",
  referenceTime: REFERENCE_TIME,
  sourceBoundary:
    "Academic Mirror 当前只使用虚构、脱敏 Fixture。它是带来源的只读副本，不是 SIS/URP/LMS，不写回成绩、学籍、选课或审批。",
  readOnly: true,
  authorityCatalog: AUTHORITY_CATALOG,
  sources: MIRROR_SOURCES,
  snapshots: MIRROR_SNAPSHOTS,
  records: MIRROR_RECORDS,
  conflicts: MIRROR_CONFLICTS,
  consents: MIRROR_CONSENTS,
  audit: MIRROR_AUDIT,
};
