import type {
  AuditEvent,
  AuthorityDefinition,
  AuthorityLevel,
  ConflictRecord,
  ConsentRecord,
  MirrorDataSource,
  MirrorFixture,
  NormalizedField,
  NormalizedRecord,
  RawSnapshot,
} from "./types";

const REFERENCE_TIME = "2026-07-25T00:30:00+08:00";

const HASHES = {
  sis: "sha256:6b43a6aa60fb2d35c5907c643e9a519b7f615959b92983c9e649f04c5b51f15f",
  uaTranscript:
    "sha256:9c939c0a1078223cf7f356ae2089eb157b1b119dacdbfb07f35cad8b57145da1",
  catalog:
    "sha256:fc88bf3c8ef9a5e40e51465b4a89fab6c8320258d911b3178400e7589429f736",
  file: "sha256:423c25d04dd9fd711eb65683f7bca7a52e538245018362875ca9fd6c0958f311",
  self: "sha256:1731c5f2b49199dc82167a8f0d0d0bcf38f91aaab260deef564c866f151b9624",
  model:
    "sha256:5bdabf57a889166430ab6f79d97c918d404665bb20b75fbf08c1a83063b48b9b",
  fixture:
    "sha256:b302d1df0b51c3459e32c33d2f9903fc7693baa373069413607b7ac756010e79",
} as const;

export const AUTHORITY_CATALOG: AuthorityDefinition[] = [
  {
    level: "authoritative",
    title: "权威记录",
    description: "学校正式学籍、成绩等记录；仍需通过正式系统办理更正。",
    highRiskEligible: true,
  },
  {
    level: "official_reference",
    title: "官方参考",
    description: "课程目录、培养方案等官方公开或授权参考。",
    highRiskEligible: true,
  },
  {
    level: "authorized_mirror",
    title: "授权镜像",
    description: "经授权导出的只读副本；高风险用途还需检查新鲜度。",
    highRiskEligible: true,
  },
  {
    level: "self_declared",
    title: "本人声明",
    description: "学生主动填写的兴趣或目标，可撤回，不代替正式记录。",
    highRiskEligible: false,
  },
  {
    level: "model_inferred",
    title: "模型推断",
    description: "AI 生成的建议或推断，只能作为可拒绝的解释线索。",
    highRiskEligible: false,
  },
  {
    level: "demo_fixture",
    title: "演示夹具",
    description: "虚构、脱敏的演示数据，永远不能支持正式决定。",
    highRiskEligible: false,
  },
];

const source = (
  value: Omit<
    MirrorDataSource,
    "authMethod" | "refreshMethod" | "consentRequired" | "status"
  >,
): MirrorDataSource => ({
  ...value,
  authMethod: value.adapterKind === "file_import" ? "file_import" : "manual",
  refreshMethod: value.adapterKind === "file_import" ? "manual" : "on_demand",
  consentRequired: true,
  status: "active",
});

export const MIRROR_SOURCES: MirrorDataSource[] = [
  source({
    id: "ds-sis-demo",
    name: "脱敏 HEBUT 成绩快照",
    systemType: "manual_export",
    adapterKind: "file_import",
    responsibleParty: "学生本人授权导入",
    fieldScope: [
      "student.program",
      "academic.earned_credits",
      "academic.gpa",
      "grade.history",
    ],
    retentionDays: 365,
    correctionRoute:
      "演示差异回到原成绩单核对；正式更正仍需学校权威系统办理。",
    authorized: true,
    declaredAuthority: "authoritative",
    lastSyncedAt: "2026-07-24T23:30:00+08:00",
    createdAt: "2026-07-24T23:20:00+08:00",
    updatedAt: "2026-07-24T23:30:00+08:00",
  }),
  source({
    id: "ds-catalog-demo",
    name: "UArizona 2026 公开课程目录",
    systemType: "sis",
    adapterKind: "demo_fixture",
    responsibleParty: "University of Arizona Courses public API",
    fieldScope: [
      "course.title",
      "course.description",
      "offering.schedule",
      "offering.enrollment_snapshot",
    ],
    retentionDays: 90,
    correctionRoute:
      "重新抓取公开 API 快照；正式选课状态与地点需回到 UAccess 核对。",
    authorized: true,
    declaredAuthority: "official_reference",
    lastSyncedAt: "2026-07-24T21:14:56+08:00",
    createdAt: "2026-07-24T20:21:16+08:00",
    updatedAt: "2026-07-24T21:14:56+08:00",
  }),
  source({
    id: "ds-uarizona-transcript",
    name: "脱敏 UArizona 非官方成绩快照",
    systemType: "manual_export",
    adapterKind: "file_import",
    responsibleParty: "学生本人授权导入",
    fieldScope: [
      "academic.earned_credits",
      "academic.gpa",
      "academic.transfer_credits",
      "grade.history",
    ],
    retentionDays: 365,
    correctionRoute:
      "演示差异回到原非官方成绩单核对；正式用途必须使用学校正式记录。",
    authorized: true,
    declaredAuthority: "authorized_mirror",
    lastSyncedAt: "2026-07-24T23:35:00+08:00",
    createdAt: "2026-07-24T23:32:00+08:00",
    updatedAt: "2026-07-24T23:35:00+08:00",
  }),
  source({
    id: "ds-file-import",
    name: "已核验项目与经历事实表",
    systemType: "manual_export",
    adapterKind: "file_import",
    responsibleParty: "学生本人",
    fieldScope: [
      "experience.title",
      "experience.role",
      "experience.evidence_boundary",
      "experience.status",
    ],
    retentionDays: 14,
    correctionRoute: "重新导入已脱敏文件，或删除此非权威副本。",
    authorized: true,
    declaredAuthority: "authorized_mirror",
    lastSyncedAt: "2026-07-24T23:42:00+08:00",
    createdAt: "2026-07-24T23:40:00+08:00",
    updatedAt: "2026-07-24T23:42:00+08:00",
  }),
  source({
    id: "ds-self-profile",
    name: "本人目标与偏好",
    systemType: "manual_export",
    adapterKind: "file_import",
    responsibleParty: "学生本人",
    fieldScope: ["student.goal", "student.research_direction"],
    retentionDays: 365,
    correctionRoute: "本人可直接更新或删除此声明，不影响学校正式记录。",
    authorized: true,
    declaredAuthority: "self_declared",
    lastSyncedAt: "2026-07-24T23:45:00+08:00",
    createdAt: "2026-07-24T23:44:00+08:00",
    updatedAt: "2026-07-24T23:45:00+08:00",
  }),
  source({
    id: "ds-model-insight",
    name: "本地模型建议输出",
    systemType: "manual_export",
    adapterKind: "file_import",
    responsibleParty: "University2K26 本地 AI",
    fieldScope: ["student.suggested_focus"],
    retentionDays: 7,
    correctionRoute: "可拒绝或删除模型推断；模型无权修改正式记录。",
    authorized: true,
    declaredAuthority: "model_inferred",
    lastSyncedAt: "2026-07-24T23:48:00+08:00",
    createdAt: "2026-07-24T23:47:00+08:00",
    updatedAt: "2026-07-24T23:48:00+08:00",
  }),
  source({
    id: "ds-pure-fixture",
    name: "NAN 去标识身份夹具",
    systemType: "demo_fixture",
    adapterKind: "demo_fixture",
    responsibleParty: "University2K26 Demo",
    fieldScope: ["student.alias", "demo.boundary"],
    retentionDays: 1,
    correctionRoute: "演示夹具可重置，不代表任何学校或学生。",
    authorized: true,
    declaredAuthority: "demo_fixture",
    lastSyncedAt: "2026-07-24T23:50:00+08:00",
    createdAt: "2026-07-24T23:50:00+08:00",
    updatedAt: "2026-07-24T23:50:00+08:00",
  }),
];

const snapshot = (
  id: string,
  dataSourceId: string,
  sourceVersion: string,
  fetchedAt: string,
  contentHash: string,
  format: RawSnapshot["format"],
): RawSnapshot => ({
  id,
  dataSourceId,
  externalId: `${dataSourceId}-student-nan`,
  sourceVersion,
  fetchedAt,
  contentHash,
  rawReference: `fixture://academic-mirror/${id}`,
  format,
  sizeBytes: 512 + id.length * 17,
  immutable: true,
  demoFixture: true,
});

export const MIRROR_SNAPSHOTS: RawSnapshot[] = [
  snapshot(
    "snap-sis-001",
    "ds-sis-demo",
    "hebut-transcript-deidentified-2026-03-r1",
    "2026-07-24T23:30:00+08:00",
    HASHES.sis,
    "json",
  ),
  snapshot(
    "snap-catalog-001",
    "ds-catalog-demo",
    "uarizona-public-courses-2026-r1",
    "2026-07-24T21:14:56+08:00",
    HASHES.catalog,
    "json",
  ),
  snapshot(
    "snap-uarizona-transcript-001",
    "ds-uarizona-transcript",
    "uarizona-unofficial-transcript-deidentified-2026-03-r1",
    "2026-07-24T23:35:00+08:00",
    HASHES.uaTranscript,
    "json",
  ),
  snapshot(
    "snap-file-001",
    "ds-file-import",
    "verified-experience-facts-2026-07-17-r1",
    "2026-07-24T23:42:00+08:00",
    HASHES.file,
    "csv",
  ),
  snapshot(
    "snap-self-001",
    "ds-self-profile",
    "self-declared-r1",
    "2026-07-24T23:45:00+08:00",
    HASHES.self,
    "manual",
  ),
  snapshot(
    "snap-model-001",
    "ds-model-insight",
    "local-model-r1",
    "2026-07-24T23:48:00+08:00",
    HASHES.model,
    "json",
  ),
  snapshot(
    "snap-fixture-001",
    "ds-pure-fixture",
    "nan-alias-fixture-r1",
    "2026-07-24T23:50:00+08:00",
    HASHES.fixture,
    "json",
  ),
];

const field = (
  value: NormalizedField["value"],
  dataSourceId: string,
  externalField: string,
  declaredAuthority: AuthorityLevel,
  rawSnapshotId: string,
  sourceVersion: string,
  fetchedAt: string,
  conversionRule = "原值映射；保留未知字段",
): NormalizedField => ({
  value,
  provenance: {
    sourceSystem:
      MIRROR_SOURCES.find((candidate) => candidate.id === dataSourceId)?.name ??
      dataSourceId,
    dataSourceId,
    externalField,
    sourceVersion,
    fetchedAt,
    declaredAuthority,
    effectiveAuthority: "demo_fixture",
    conversionRule,
    rawSnapshotId,
  },
});

const record = (
  value: Omit<NormalizedRecord, "studentId" | "demoFixture">,
): NormalizedRecord => ({
  ...value,
  studentId: "student-nan-fixture",
  demoFixture: true,
});

export const MIRROR_RECORDS: NormalizedRecord[] = [
  record({
    id: "nr-student-profile",
    snapshotIds: ["snap-sis-001"],
    entityType: "student",
    entityId: "student-nan-fixture",
    label: "南同学（NaN）· 学生档案",
    fields: {
      display_name: field(
        "南同学（NaN）",
        "ds-sis-demo",
        "student.display_name",
        "authoritative",
        "snap-sis-001",
        "sis-fixture-r4",
        "2026-07-24T10:30:00+08:00",
      ),
      major: field(
        "电子信息工程（演示）",
        "ds-sis-demo",
        "student.major_name",
        "authoritative",
        "snap-sis-001",
        "sis-fixture-r4",
        "2026-07-24T10:30:00+08:00",
      ),
      unknown_extension: field(
        "retained:campus_cohort_x",
        "ds-sis-demo",
        "extensions.campus_cohort",
        "authoritative",
        "snap-sis-001",
        "sis-fixture-r4",
        "2026-07-24T10:30:00+08:00",
        "未知字段原样保留，不进入正式判断",
      ),
    },
    effectiveAt: "2026-07-24T10:30:00+08:00",
    expiresAt: "2026-08-23T10:30:00+08:00",
    consentBasis: "consent-sis-read",
    correctionRoute: "正式档案请联系教务处；镜像差异可提交校对。",
    removable: false,
  }),
  record({
    id: "nr-course-sls201",
    snapshotIds: ["snap-catalog-001", "snap-file-001"],
    entityType: "course",
    entityId: "SLS201",
    label: "SLS201 · 信号与线性系统",
    fields: {
      title: field(
        "信号与线性系统",
        "ds-catalog-demo",
        "course.name_zh",
        "official_reference",
        "snap-catalog-001",
        "catalog-fixture-r3",
        "2026-07-23T16:00:00+08:00",
      ),
      credits: field(
        3,
        "ds-catalog-demo",
        "course.credit_value",
        "official_reference",
        "snap-catalog-001",
        "catalog-fixture-r3",
        "2026-07-23T16:00:00+08:00",
        "decimal credits → integer when exact",
      ),
      season_role: field(
        "主赛程",
        "ds-pure-fixture",
        "demo.season_role",
        "demo_fixture",
        "snap-fixture-001",
        "fixture-r1",
        "2026-07-24T10:00:00+08:00",
      ),
    },
    effectiveAt: "2026-07-23T16:00:00+08:00",
    expiresAt: "2026-07-24T22:00:00+08:00",
    consentBasis: "consent-sis-read",
    correctionRoute: "请从学校课程目录核对，并向本科生院提交勘误。",
    removable: false,
  }),
  record({
    id: "nr-grade-sls201",
    snapshotIds: ["snap-sis-001"],
    entityType: "grade",
    entityId: "SLS201-grade-demo",
    label: "SLS201 · 历史成绩样例",
    fields: {
      result: field(
        "91.7 / A-（演示）",
        "ds-sis-demo",
        "grade.display_result",
        "authoritative",
        "snap-sis-001",
        "sis-fixture-r4",
        "2026-07-24T10:30:00+08:00",
      ),
      formal_status: field(
        false,
        "ds-pure-fixture",
        "demo.is_formal_grade",
        "demo_fixture",
        "snap-fixture-001",
        "fixture-r1",
        "2026-07-24T10:00:00+08:00",
      ),
    },
    effectiveAt: "2026-07-10T08:00:00+08:00",
    expiresAt: "2026-07-22T08:00:00+08:00",
    consentBasis: "consent-sis-read",
    correctionRoute: "这份演示记录已经过期；正式成绩请回学校成绩系统核对。",
    removable: false,
  }),
  record({
    id: "nr-activity-hackathon",
    snapshotIds: ["snap-file-001"],
    entityType: "activity",
    entityId: "activity-adventurex-demo",
    label: "AdventureX 项目经历（授权导入）",
    fields: {
      title: field(
        "University2K26 原型协作",
        "ds-file-import",
        "activity.title",
        "authorized_mirror",
        "snap-file-001",
        "authorized-export-r1",
        "2026-07-24T11:10:00+08:00",
      ),
      role: field(
        "产品与工程协作",
        "ds-file-import",
        "activity.role",
        "authorized_mirror",
        "snap-file-001",
        "authorized-export-r1",
        "2026-07-24T11:10:00+08:00",
      ),
      hours: field(
        8,
        "ds-file-import",
        "activity.hours",
        "authorized_mirror",
        "snap-file-001",
        "authorized-export-r1",
        "2026-07-24T11:10:00+08:00",
      ),
    },
    effectiveAt: "2026-07-24T11:10:00+08:00",
    expiresAt: null,
    consentBasis: "consent-activity-opportunity",
    correctionRoute: "可重新导入或删除此授权副本。",
    removable: true,
  }),
  record({
    id: "nr-self-goal",
    snapshotIds: ["snap-self-001"],
    entityType: "student",
    entityId: "student-nan-fixture-goal",
    label: "本人方向偏好",
    fields: {
      goal: field(
        "交互设计 × 嵌入式系统",
        "ds-self-profile",
        "student.goal",
        "self_declared",
        "snap-self-001",
        "self-declared-r1",
        "2026-07-24T11:20:00+08:00",
      ),
      study_preference: field(
        ["项目制", "可解释反馈", "午后专注"],
        "ds-self-profile",
        "student.study_preference",
        "self_declared",
        "snap-self-001",
        "self-declared-r1",
        "2026-07-24T11:20:00+08:00",
      ),
    },
    effectiveAt: "2026-07-24T11:20:00+08:00",
    expiresAt: null,
    consentBasis: "consent-self-profile",
    correctionRoute: "本人可随时更新或删除。",
    removable: true,
  }),
  record({
    id: "nr-model-suggestion",
    snapshotIds: ["snap-model-001"],
    entityType: "requirement",
    entityId: "suggestion-focus-demo",
    label: "AI 学习建议（可拒绝）",
    fields: {
      suggested_focus: field(
        "先核对卷积与系统性质的证据链",
        "ds-model-insight",
        "model.suggested_focus",
        "model_inferred",
        "snap-model-001",
        "local-model-r1",
        "2026-07-24T11:25:00+08:00",
      ),
      confidence_label: field(
        "medium · not a decision",
        "ds-model-insight",
        "model.confidence",
        "model_inferred",
        "snap-model-001",
        "local-model-r1",
        "2026-07-24T11:25:00+08:00",
      ),
    },
    effectiveAt: "2026-07-24T11:25:00+08:00",
    expiresAt: "2026-07-31T11:25:00+08:00",
    consentBasis: "consent-model-revoked",
    correctionRoute: "可拒绝或删除；模型不能更改课程、成绩或学籍。",
    removable: true,
  }),
];

export const PERSONAL_MIRROR_RECORDS: NormalizedRecord[] = [
  record({
    id: "nr-student-profile",
    snapshotIds: ["snap-sis-001", "snap-fixture-001"],
    entityType: "student",
    entityId: "student-nan-fixture",
    label: "南同学（NAN）· 去标识学术档案",
    fields: {
      display_name: field(
        "南同学（NAN）",
        "ds-pure-fixture",
        "student.alias",
        "demo_fixture",
        "snap-fixture-001",
        "nan-alias-fixture-r1",
        "2026-07-24T23:50:00+08:00",
        "移除直接标识后生成公开演示别名",
      ),
      major: field(
        "应用物理学",
        "ds-sis-demo",
        "student.program.major",
        "authoritative",
        "snap-sis-001",
        "hebut-transcript-deidentified-2026-03-r1",
        "2026-07-24T23:30:00+08:00",
      ),
      program_window: field(
        "本科 2023-2027 · 成绩记录覆盖 5 个 HEBUT 学期",
        "ds-sis-demo",
        "student.program.window",
        "authoritative",
        "snap-sis-001",
        "hebut-transcript-deidentified-2026-03-r1",
        "2026-07-24T23:30:00+08:00",
      ),
      privacy_boundary: field(
        "不含姓名、学号、证件号、生日、班级或联系方式；去标识不等于绝对匿名",
        "ds-pure-fixture",
        "demo.privacy_boundary",
        "demo_fixture",
        "snap-fixture-001",
        "nan-alias-fixture-r1",
        "2026-07-24T23:50:00+08:00",
      ),
    },
    effectiveAt: "2026-07-24T23:50:00+08:00",
    expiresAt: "2026-08-24T23:50:00+08:00",
    consentBasis: "consent-sis-read",
    correctionRoute: "对照本人授权原件核对；正式更正回到学校权威系统。",
    removable: false,
  }),
  record({
    id: "nr-hebut-academic-summary",
    snapshotIds: ["snap-sis-001"],
    entityType: "grade",
    entityId: "hebut-academic-summary-2026-03",
    label: "HEBUT · 成绩与学分总览",
    fields: {
      earned_credits: field(
        128.5,
        "ds-sis-demo",
        "academic.earned_credits",
        "authoritative",
        "snap-sis-001",
        "hebut-transcript-deidentified-2026-03-r1",
        "2026-07-24T23:30:00+08:00",
      ),
      cumulative_gpa: field(
        "3.18",
        "ds-sis-demo",
        "academic.cumulative_gpa",
        "authoritative",
        "snap-sis-001",
        "hebut-transcript-deidentified-2026-03-r1",
        "2026-07-24T23:30:00+08:00",
      ),
      covered_terms: field(
        5,
        "ds-sis-demo",
        "academic.covered_terms",
        "authoritative",
        "snap-sis-001",
        "hebut-transcript-deidentified-2026-03-r1",
        "2026-07-24T23:30:00+08:00",
      ),
      grading_scales: field(
        ["百分制", "优秀 / 良好 / 中等"],
        "ds-sis-demo",
        "academic.grading_scales",
        "authoritative",
        "snap-sis-001",
        "hebut-transcript-deidentified-2026-03-r1",
        "2026-07-24T23:30:00+08:00",
        "不同计分制保持原样，不自动互换",
      ),
    },
    effectiveAt: "2026-03-14T16:29:51+08:00",
    expiresAt: "2026-07-25T02:30:00+08:00",
    consentBasis: "consent-sis-read",
    correctionRoute: "对照 HEBUT 原成绩单核对。",
    removable: false,
  }),
  record({
    id: "nr-uarizona-academic-summary",
    snapshotIds: ["snap-uarizona-transcript-001"],
    entityType: "grade",
    entityId: "uarizona-academic-summary-2026-03",
    label: "UArizona · 非官方成绩镜像",
    fields: {
      earned_credits: field(
        16,
        "ds-uarizona-transcript",
        "academic.earned_hours",
        "authorized_mirror",
        "snap-uarizona-transcript-001",
        "uarizona-unofficial-transcript-deidentified-2026-03-r1",
        "2026-07-24T23:35:00+08:00",
      ),
      cumulative_gpa: field(
        "3.40",
        "ds-uarizona-transcript",
        "academic.cumulative_gpa",
        "authorized_mirror",
        "snap-uarizona-transcript-001",
        "uarizona-unofficial-transcript-deidentified-2026-03-r1",
        "2026-07-24T23:35:00+08:00",
      ),
      transfer_credits: field(
        78,
        "ds-uarizona-transcript",
        "academic.transfer_credits",
        "authorized_mirror",
        "snap-uarizona-transcript-001",
        "uarizona-unofficial-transcript-deidentified-2026-03-r1",
        "2026-07-24T23:35:00+08:00",
        "保留为 UArizona 系统中的 Transfer Credits；不与 HEBUT 已获学分相加",
      ),
      course_results: field(
        [
          "ENGL 106 · A",
          "ENGL 107 · A",
          "ENGL 108 · A",
          "PHYS 204 · C",
          "PHYS 240 · B",
          "PHYS 321 · WC",
        ],
        "ds-uarizona-transcript",
        "grade.history",
        "authorized_mirror",
        "snap-uarizona-transcript-001",
        "uarizona-unofficial-transcript-deidentified-2026-03-r1",
        "2026-07-24T23:35:00+08:00",
        "P/F 与 WC 状态在学期明细中另行保留",
      ),
    },
    effectiveAt: "2026-03-08T00:00:00-07:00",
    expiresAt: "2026-07-24T23:00:00+08:00",
    consentBasis: "consent-uarizona-transcript-read",
    correctionRoute: "对照 UArizona 原非官方成绩单核对；正式用途需正式成绩单。",
    removable: false,
  }),
  record({
    id: "nr-verified-experience-portfolio",
    snapshotIds: ["snap-file-001"],
    entityType: "activity",
    entityId: "verified-experience-portfolio",
    label: "项目与科研经历 · 已核验边界",
    fields: {
      verified_projects: field(
        [
          "杨氏模量光学测量仪 · C# / WinUI 3",
          "Raspberry Pi 5 智能救援机器人 · 软件集成",
          "智能车视觉组 · PCB 设计与焊接",
          "Lumi Buddy 8051 · 图形时钟",
          "BoHack / projectLETTER · 42 小时原型",
        ],
        "ds-file-import",
        "experience.verified_projects",
        "authorized_mirror",
        "snap-file-001",
        "verified-experience-facts-2026-07-17-r1",
        "2026-07-24T23:42:00+08:00",
      ),
      in_progress: field(
        ["OpenCamp 操作系统方向科研 / 训练"],
        "ds-file-import",
        "experience.in_progress",
        "authorized_mirror",
        "snap-file-001",
        "verified-experience-facts-2026-07-17-r1",
        "2026-07-24T23:42:00+08:00",
        "保留进行中状态，不写成已完成成果",
      ),
      boundary: field(
        "只陈述个人负责部分；团队奖项不等于个人完成全部工作",
        "ds-file-import",
        "experience.evidence_boundary",
        "authorized_mirror",
        "snap-file-001",
        "verified-experience-facts-2026-07-17-r1",
        "2026-07-24T23:42:00+08:00",
      ),
    },
    effectiveAt: "2026-07-17T12:00:00+08:00",
    expiresAt: null,
    consentBasis: "consent-activity-opportunity",
    correctionRoute: "回到事实主表与原始证据核对；可删除本地副本。",
    removable: true,
  }),
  record({
    id: "nr-self-goal",
    snapshotIds: ["snap-self-001"],
    entityType: "student",
    entityId: "student-nan-fixture-goal",
    label: "本人方向偏好",
    fields: {
      goal: field(
        "操作系统基础能力 × 机器人系统软件",
        "ds-self-profile",
        "student.goal",
        "self_declared",
        "snap-self-001",
        "self-declared-r1",
        "2026-07-24T23:45:00+08:00",
      ),
      research_direction: field(
        [
          "ROS 2 / DDS 通信",
          "调度与实时性",
          "驱动接口",
          "控制链可观测性",
        ],
        "ds-self-profile",
        "student.research_direction",
        "self_declared",
        "snap-self-001",
        "self-declared-r1",
        "2026-07-24T23:45:00+08:00",
      ),
    },
    effectiveAt: "2026-07-24T23:45:00+08:00",
    expiresAt: null,
    consentBasis: "consent-self-profile",
    correctionRoute: "本人可随时更新或删除；方向偏好不改写正式专业。",
    removable: true,
  }),
  record({
    id: "nr-uarizona-catalog-2026",
    snapshotIds: ["snap-catalog-001"],
    entityType: "course",
    entityId: "uarizona-public-catalog-2026",
    label: "UArizona 2026 · 公开课程目录快照",
    fields: {
      schedule_rows: field(
        57_857,
        "ds-catalog-demo",
        "catalog.schedule_rows",
        "official_reference",
        "snap-catalog-001",
        "uarizona-public-courses-2026-r1",
        "2026-07-24T21:14:56+08:00",
      ),
      unique_courses: field(
        11_347,
        "ds-catalog-demo",
        "catalog.unique_courses",
        "official_reference",
        "snap-catalog-001",
        "uarizona-public-courses-2026-r1",
        "2026-07-24T21:14:56+08:00",
      ),
      selected_scout_courses: field(
        ["AME 455", "AME 551", "CSC 280", "CSC 352", "CSC 452", "CSC 480"],
        "ds-catalog-demo",
        "catalog.selected_scout_courses",
        "official_reference",
        "snap-catalog-001",
        "uarizona-public-courses-2026-r1",
        "2026-07-24T21:14:56+08:00",
        "按南同学方向筛选的演示子集；不是选课结果",
      ),
      location_boundary: field(
        "地点字段需要 UAccess 登录，公开快照未提供",
        "ds-catalog-demo",
        "catalog.location_boundary",
        "official_reference",
        "snap-catalog-001",
        "uarizona-public-courses-2026-r1",
        "2026-07-24T21:14:56+08:00",
      ),
    },
    effectiveAt: "2026-07-24T21:14:56+08:00",
    expiresAt: "2026-10-24T21:14:56+08:00",
    consentBasis: "consent-catalog-read",
    correctionRoute: "重新抓取公开 API；正式选课状态回 UAccess 核对。",
    removable: false,
  }),
  record({
    id: "nr-model-suggestion",
    snapshotIds: ["snap-model-001"],
    entityType: "requirement",
    entityId: "suggestion-focus-demo",
    label: "AI 路线建议 · 可拒绝",
    fields: {
      suggested_sequence: field(
        "CSC 352 → CSC 452 → AME 455",
        "ds-model-insight",
        "model.suggested_sequence",
        "model_inferred",
        "snap-model-001",
        "local-model-r1",
        "2026-07-24T23:48:00+08:00",
      ),
      rationale: field(
        "先补系统编程，再进入操作系统，最后把控制与机器人项目收束成闭环证据",
        "ds-model-insight",
        "model.rationale",
        "model_inferred",
        "snap-model-001",
        "local-model-r1",
        "2026-07-24T23:48:00+08:00",
      ),
      confidence_label: field(
        "medium · suggestion only",
        "ds-model-insight",
        "model.confidence",
        "model_inferred",
        "snap-model-001",
        "local-model-r1",
        "2026-07-24T23:48:00+08:00",
      ),
    },
    effectiveAt: "2026-07-24T23:48:00+08:00",
    expiresAt: "2026-07-31T23:48:00+08:00",
    consentBasis: "consent-model-revoked",
    correctionRoute: "可拒绝或删除；模型不能更改课程、成绩、学籍或选课。",
    removable: true,
  }),
];

export const MIRROR_CONFLICTS: ConflictRecord[] = [
  {
    id: "conf-sls-credits",
    entityId: "SLS201",
    entityLabel: "SLS201 · 信号与线性系统",
    fieldName: "credits",
    status: "detected",
    resolution: null,
    options: [
      {
        id: "opt-catalog-3",
        sourceSystem: "课程目录演示源",
        dataSourceId: "ds-catalog-demo",
        value: 3,
        declaredAuthority: "official_reference",
        fetchedAt: "2026-07-23T16:00:00+08:00",
        rawSnapshotId: "snap-catalog-001",
      },
      {
        id: "opt-file-4",
        sourceSystem: "已授权活动导出文件",
        dataSourceId: "ds-file-import",
        value: 4,
        declaredAuthority: "authorized_mirror",
        fetchedAt: "2026-07-24T11:10:00+08:00",
        rawSnapshotId: "snap-file-001",
      },
    ],
  },
  {
    id: "conf-major-label",
    entityId: "student-nan-fixture",
    entityLabel: "南同学（NaN）· 学生档案",
    fieldName: "major",
    status: "detected",
    resolution: null,
    options: [
      {
        id: "opt-sis-major",
        sourceSystem: "SIS 权威记录演示源",
        dataSourceId: "ds-sis-demo",
        value: "电子信息工程（演示）",
        declaredAuthority: "authoritative",
        fetchedAt: "2026-07-24T10:30:00+08:00",
        rawSnapshotId: "snap-sis-001",
      },
      {
        id: "opt-self-major",
        sourceSystem: "本人目标与偏好",
        dataSourceId: "ds-self-profile",
        value: "电子信息工程 + 交互设计方向",
        declaredAuthority: "self_declared",
        fetchedAt: "2026-07-24T11:20:00+08:00",
        rawSnapshotId: "snap-self-001",
      },
    ],
  },
];

export const PERSONAL_MIRROR_CONFLICTS: ConflictRecord[] = [
  {
    id: "conf-credit-semantics",
    entityId: "student-nan-fixture",
    entityLabel: "南同学 · 跨校学分字段",
    fieldName: "credits",
    status: "detected",
    resolution: null,
    options: [
      {
        id: "opt-hebut-earned-credits",
        sourceSystem: "脱敏 HEBUT 成绩快照",
        dataSourceId: "ds-sis-demo",
        value: "128.5 · HEBUT 已获总学分",
        declaredAuthority: "authoritative",
        fetchedAt: "2026-07-24T23:30:00+08:00",
        rawSnapshotId: "snap-sis-001",
      },
      {
        id: "opt-uarizona-transfer-credits",
        sourceSystem: "脱敏 UArizona 非官方成绩快照",
        dataSourceId: "ds-uarizona-transcript",
        value: "78 · UArizona Transfer Credits",
        declaredAuthority: "authorized_mirror",
        fetchedAt: "2026-07-24T23:35:00+08:00",
        rawSnapshotId: "snap-uarizona-transcript-001",
      },
    ],
  },
  {
    id: "conf-major-vs-direction",
    entityId: "student-nan-fixture",
    entityLabel: "南同学 · 专业与研究方向",
    fieldName: "major_or_direction",
    status: "detected",
    resolution: null,
    options: [
      {
        id: "opt-formal-major",
        sourceSystem: "脱敏 HEBUT 成绩快照",
        dataSourceId: "ds-sis-demo",
        value: "应用物理学（正式专业）",
        declaredAuthority: "authoritative",
        fetchedAt: "2026-07-24T23:30:00+08:00",
        rawSnapshotId: "snap-sis-001",
      },
      {
        id: "opt-self-direction",
        sourceSystem: "本人目标与偏好",
        dataSourceId: "ds-self-profile",
        value: "操作系统 × 机器人系统软件（本人方向）",
        declaredAuthority: "self_declared",
        fetchedAt: "2026-07-24T23:45:00+08:00",
        rawSnapshotId: "snap-self-001",
      },
    ],
  },
];

export const MIRROR_CONSENTS: ConsentRecord[] = [
  {
    id: "consent-sis-read",
    studentId: "student-nan-fixture",
    dataSourceId: "ds-sis-demo",
    allowedModules: ["F-002", "F-004"],
    purpose: "在赛季中心展示课程状态，并为 Roster Lab 提供只读 Prefix。",
    grantedAt: "2026-07-24T09:40:00+08:00",
    expiresAt: "2026-08-24T09:40:00+08:00",
    revokedAt: null,
    scope: "read_only",
  },
  {
    id: "consent-catalog-read",
    studentId: "student-nan-fixture",
    dataSourceId: "ds-catalog-demo",
    allowedModules: ["F-002", "F-004"],
    purpose: "显示课程目录并解释培养方案约束。",
    grantedAt: "2026-07-24T09:42:00+08:00",
    expiresAt: "2026-10-24T09:42:00+08:00",
    revokedAt: null,
    scope: "read_only",
  },
  {
    id: "consent-uarizona-transcript-read",
    studentId: "student-nan-fixture",
    dataSourceId: "ds-uarizona-transcript",
    allowedModules: ["F-002", "F-004", "F-007"],
    purpose:
      "显示本人 UArizona 历史记录并做课程匹配；不把公开目录误写为已修课程。",
    grantedAt: "2026-07-24T23:35:00+08:00",
    expiresAt: "2026-08-24T23:35:00+08:00",
    revokedAt: null,
    scope: "read_only",
  },
  {
    id: "consent-activity-opportunity",
    studentId: "student-nan-fixture",
    dataSourceId: "ds-file-import",
    allowedModules: ["F-009"],
    purpose: "用于机会匹配资格解释；不自动投递。",
    grantedAt: "2026-07-24T11:12:00+08:00",
    expiresAt: "2026-08-07T11:12:00+08:00",
    revokedAt: null,
    scope: "matching",
  },
  {
    id: "consent-self-profile",
    studentId: "student-nan-fixture",
    dataSourceId: "ds-self-profile",
    allowedModules: ["F-004", "F-006", "F-009"],
    purpose: "用于本人可撤回的规划偏好与机会匹配。",
    grantedAt: "2026-07-24T11:22:00+08:00",
    expiresAt: null,
    revokedAt: null,
    scope: "matching",
  },
  {
    id: "consent-model-revoked",
    studentId: "student-nan-fixture",
    dataSourceId: "ds-model-insight",
    allowedModules: ["F-006"],
    purpose: "曾用于学习建议，现已撤回。",
    grantedAt: "2026-07-24T11:26:00+08:00",
    expiresAt: "2026-07-31T11:26:00+08:00",
    revokedAt: "2026-07-24T11:30:00+08:00",
    scope: "read_only",
  },
];

const audit = (
  sequence: number,
  action: AuditEvent["action"],
  targetEntity: string,
  timestamp: string,
  detail: string,
  previousEventHash: string | null,
  eventHash: string,
): AuditEvent => ({
  id: `aud-${String(sequence).padStart(3, "0")}`,
  sequence,
  action,
  actorId: "student-nan-fixture",
  targetEntity,
  timestamp,
  detail,
  previousEventHash,
  eventHash,
  appendOnly: true,
});

export const MIRROR_AUDIT: AuditEvent[] = [
  audit(
    1,
    "sync",
    "source:ds-sis-demo",
    "2026-07-24T10:30:00+08:00",
    "已生成演示快照 snap-sis-001；旧版本不会被覆盖。",
    null,
    "fnv1a-aud-001",
  ),
  audit(
    2,
    "map",
    "snapshot:snap-sis-001",
    "2026-07-24T10:31:00+08:00",
    "映射 2 条标准记录；字段级来源已保留。",
    "fnv1a-aud-001",
    "fnv1a-aud-002",
  ),
  audit(
    3,
    "sync",
    "source:ds-file-import",
    "2026-07-24T11:10:00+08:00",
    "已读取脱敏样例，原文件没有上传。",
    "fnv1a-aud-002",
    "fnv1a-aud-003",
  ),
  audit(
    4,
    "consent_revoke",
    "consent:consent-model-revoked",
    "2026-07-24T11:30:00+08:00",
    "撤回 F-006 对模型推断源的读取同意。",
    "fnv1a-aud-003",
    "fnv1a-aud-004",
  ),
];

export const ACADEMIC_MIRROR_FIXTURE: MirrorFixture = {
  schemaVersion: "1.1.0",
  dataMode: "fixture",
  studentId: "student-nan-fixture",
  referenceTime: REFERENCE_TIME,
  sourceBoundary:
    "这份镜像来自本人有权使用的材料和 UArizona 公开课表。它不是学校的 SIS、URP 或 LMS，也不会改成绩、学籍、选课和审批记录；去标识仍不等于绝对匿名。",
  readOnly: true,
  authorityCatalog: AUTHORITY_CATALOG,
  sources: MIRROR_SOURCES,
  snapshots: MIRROR_SNAPSHOTS,
  records: PERSONAL_MIRROR_RECORDS,
  conflicts: PERSONAL_MIRROR_CONFLICTS,
  consents: MIRROR_CONSENTS,
  audit: MIRROR_AUDIT,
};
